package adapterdocker

// dockerfileTemplate is a multi-stage Dockerfile producing a minimal
// runtime image. The build stage uses the official golang image; the
// runtime stage uses gcr.io/distroless/static-debian12 (no shell, no
// package manager, ~2MB) and runs the binary as a non-root user.
//
// The HEALTHCHECK targets /healthz on port 8080. The user is expected
// to expose that endpoint via a `_server.go` file under
// `src/routes/healthz/`. The framework does not provide one because the
// liveness contract belongs to the application.
const dockerfileTemplate = `# syntax=docker/dockerfile:1.7
# Generated by sveltego adapter-docker. Edit if you need a custom shape;
# regenerating overwrites this file.

ARG GO_VERSION={{GoVersion}}

FROM golang:${GO_VERSION}-alpine AS builder
WORKDIR /src
COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags='-s -w' -o /out/{{BinaryName}} {{MainPackage}}

FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /app
COPY --from=builder /out/{{BinaryName}} /app/{{BinaryName}}
{{AssetsCopy}}
EXPOSE {{Port}}
USER nonroot:nonroot
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD ["/app/{{BinaryName}}", "--healthcheck"]
ENTRYPOINT ["/app/{{BinaryName}}"]
`

// dockerignoreTemplate covers the typical sveltego project layout: skip
// VCS, build outputs, IDE state, and node_modules so the build context
// stays small.
const dockerignoreTemplate = `# Generated by sveltego adapter-docker.
.git
.gitignore
.github
.vscode
.idea
.claude
node_modules
.DS_Store
*.log
dist
build
out
.gen/embed/_dev
playgrounds
benchmarks
test-utils
docs
README.md
CHANGELOG.md
*.test
coverage.out
`
