package typegen

import "strings"

// emitDeclaration renders a complete `.d.ts` body. dataIdent is the
// runtime value name (always `data`); typeIdent is the interface name
// (`PageData` or `LayoutData`). The output is deterministic for a
// given input shape — drift tests rely on this.
func emitDeclaration(shape RouteShape, dataIdent, typeIdent string) string {
	var b strings.Builder
	b.WriteString("// Code generated by sveltego typegen. DO NOT EDIT.\n")
	b.WriteString("// Source: ")
	b.WriteString(shapeSourceComment(typeIdent))
	b.WriteString("\n\n")
	for _, nt := range shape.NamedTypes {
		writeInterface(&b, nt.Name, nt.Fields)
		b.WriteString("\n")
	}
	writeInterface(&b, typeIdent, shape.Fields)
	b.WriteString("\nexport const ")
	b.WriteString(dataIdent)
	b.WriteString(": ")
	b.WriteString(typeIdent)
	b.WriteString(";\n")
	return b.String()
}

func shapeSourceComment(typeIdent string) string {
	if typeIdent == "LayoutData" {
		return "_layout.server.go (Load return type)"
	}
	return "_page.server.go (Load return type)"
}

// writeInterface renders one TypeScript interface declaration. An
// empty field list yields an `Record<string, never>` alias so the
// `data` value typechecks as a structurally empty object — the
// SvelteKit-style convention when a route declares no Load.
func writeInterface(b *strings.Builder, name string, fields []Field) {
	if len(fields) == 0 {
		b.WriteString("export type ")
		b.WriteString(name)
		b.WriteString(" = Record<string, never>;\n")
		return
	}
	b.WriteString("export interface ")
	b.WriteString(name)
	b.WriteString(" {\n")
	for _, f := range fields {
		b.WriteString("\t")
		b.WriteString(quoteIfNeeded(f.Name))
		b.WriteString(": ")
		b.WriteString(f.TSType)
		b.WriteString(";\n")
	}
	b.WriteString("}\n")
}

// quoteIfNeeded wraps a property key in double quotes when it is not
// a valid bare TypeScript identifier. The check is conservative —
// anything outside `[A-Za-z_$][A-Za-z0-9_$]*` quotes — but JSON tags
// in practice rarely contain weird characters so quoting is rare.
func quoteIfNeeded(name string) string {
	if name == "" {
		return `""`
	}
	for i, r := range name {
		if i == 0 {
			if !isIdentStart(r) {
				return quote(name)
			}
			continue
		}
		if !isIdentPart(r) {
			return quote(name)
		}
	}
	return name
}

func isIdentStart(r rune) bool {
	return r == '_' || r == '$' ||
		(r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z')
}

func isIdentPart(r rune) bool {
	return isIdentStart(r) || (r >= '0' && r <= '9')
}

func quote(s string) string {
	return "\"" + strings.ReplaceAll(s, "\"", "\\\"") + "\""
}
