// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/lowered/optional-chain-shallow

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/lowered/optional-chain-shallow.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push(server.Stringify(server.EscapeHTML(func() any {
		if data.User == nil {
			return nil
		}
		return data.User.Profile
	}())))
}
