package sveltejs2go

// CompanionFile returns a small runtime companion the generated render
// files depend on. It is written once per package alongside the
// per-route render files. The companion only contains type-cast
// helpers — never logic — so it can change with the emitter without
// breaking the runtime/svelte/server stability contract.
//
// Phase 6 (#428) is responsible for placing this file once per
// generated package directory. The Transpile entrypoint exposes the
// content via this function so callers don't need to maintain a
// duplicated copy.
func CompanionFile(pkgName string) []byte {
	if pkgName == "" {
		pkgName = "gen"
	}
	src := `// Code generated by sveltego svelte_js2go. DO NOT EDIT.

package ` + pkgName + `

func toMapStringAny(v any) map[string]any {
	if v == nil {
		return nil
	}
	if m, ok := v.(map[string]any); ok {
		return m
	}
	return nil
}

func toMapStringBool(v any) map[string]bool {
	if v == nil {
		return nil
	}
	if m, ok := v.(map[string]bool); ok {
		return m
	}
	if m, ok := v.(map[string]any); ok {
		out := make(map[string]bool, len(m))
		for k, val := range m {
			b, _ := val.(bool)
			out[k] = b
		}
		return out
	}
	return nil
}

func toMapStringString(v any) map[string]string {
	if v == nil {
		return nil
	}
	if m, ok := v.(map[string]string); ok {
		return m
	}
	if m, ok := v.(map[string]any); ok {
		out := make(map[string]string, len(m))
		for k, val := range m {
			s, _ := val.(string)
			out[k] = s
		}
		return out
	}
	return nil
}
`
	return []byte(src)
}
