// Code generated by sveltego typegen. DO NOT EDIT.
// Source: _page.server.go (Load return type)

export interface Post {
	id: string;
	title: string;
}

export interface PageData {
	slowPosts: Promise<Post[]>;
	count: number;
}

export const data: PageData;
