// Code generated by sveltego typegen. DO NOT EDIT.
// Source: _page.server.go (Load return type)

export interface User {
	id: string;
	name: string;
	email: string;
}

export interface Post {
	id: string;
	title: string;
}

export interface PageData {
	user: User;
	posts: Post[];
}

export const data: PageData;
