// Package scaffold writes a fresh sveltego project tree into a target
// directory. It owns both the baseline project files (src/routes, src/lib,
// hooks, config, go.mod, README) and the optional AI-assistant templates
// sourced from github.com/binsarjr/sveltego/templates/ai.
package scaffold

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	aitemplates "github.com/binsarjr/sveltego/templates/ai"
)

const fileMode = 0o600

// Options controls what Run writes and how it handles conflicts.
type Options struct {
	// Dir is the target project directory. Created if missing.
	Dir string
	// Module is the Go module path written into the generated go.mod.
	// Empty falls back to the directory base name.
	Module string
	// AI copies the templates/ai/embed.FS contents into Dir.
	AI bool
	// Force overwrites existing files. Default skips them and reports
	// the list via the returned Result.
	Force bool
}

// Result reports what Run wrote and what it skipped.
type Result struct {
	Written []string
	Skipped []string
}

// Run materializes the scaffold described by opts. It returns the
// per-file outcome and the first I/O error it could not skip past.
func Run(opts Options) (Result, error) {
	res := Result{}
	if opts.Dir == "" {
		return res, errors.New("scaffold: empty target dir")
	}
	if err := os.MkdirAll(opts.Dir, 0o755); err != nil {
		return res, fmt.Errorf("scaffold: mkdir %s: %w", opts.Dir, err)
	}

	module := opts.Module
	if module == "" {
		module = filepath.Base(opts.Dir)
		if module == "." || module == "/" || module == "" {
			module = "sveltego-app"
		}
	}

	for _, f := range baseFiles(module) {
		if err := writeFile(opts.Dir, f.path, f.body, opts.Force, &res); err != nil {
			return res, err
		}
	}

	if opts.AI {
		if err := writeAITemplates(opts.Dir, opts.Force, &res); err != nil {
			return res, err
		}
	}

	sort.Strings(res.Written)
	sort.Strings(res.Skipped)
	return res, nil
}

// WriteAITemplates copies every file in [aitemplates.FS] into dir.
// Existing files are skipped unless force is true; their paths are
// returned in Result.Skipped.
func WriteAITemplates(dir string, force bool) (Result, error) {
	res := Result{}
	if dir == "" {
		return res, errors.New("scaffold: empty target dir")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return res, fmt.Errorf("scaffold: mkdir %s: %w", dir, err)
	}
	if err := writeAITemplates(dir, force, &res); err != nil {
		return res, err
	}
	sort.Strings(res.Written)
	sort.Strings(res.Skipped)
	return res, nil
}

func writeAITemplates(dir string, force bool, res *Result) error {
	for _, name := range aitemplates.Files {
		body, err := fs.ReadFile(aitemplates.FS, name)
		if err != nil {
			return fmt.Errorf("scaffold: read template %q: %w", name, err)
		}
		if err := writeFile(dir, name, body, force, res); err != nil {
			return err
		}
	}
	return nil
}

type file struct {
	path string
	body []byte
}

func baseFiles(module string) []file {
	return []file{
		{path: "go.mod", body: []byte(renderGoMod(module))},
		{path: "README.md", body: []byte(renderReadme(module))},
		{path: ".gitignore", body: []byte(gitignoreBody)},
		{path: "sveltego.config.go", body: []byte(configBody)},
		{path: "hooks.server.go", body: []byte(hooksBody)},
		{path: "src/routes/+page.svelte", body: []byte(pageSvelteBody)},
		{path: "src/routes/page.server.go", body: []byte(pageServerBody)},
		{path: "src/routes/+layout.svelte", body: []byte(layoutSvelteBody)},
		{path: "src/lib/.gitkeep", body: []byte{}},
	}
}

func writeFile(root, rel string, body []byte, force bool, res *Result) error {
	target := filepath.Join(root, filepath.FromSlash(rel))
	if !force {
		if _, err := os.Stat(target); err == nil {
			res.Skipped = append(res.Skipped, rel)
			return nil
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("scaffold: stat %s: %w", target, err)
		}
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("scaffold: mkdir %s: %w", filepath.Dir(target), err)
	}
	if err := os.WriteFile(target, body, fileMode); err != nil {
		return fmt.Errorf("scaffold: write %s: %w", target, err)
	}
	res.Written = append(res.Written, rel)
	return nil
}

func renderGoMod(module string) string {
	var b strings.Builder
	b.WriteString("module ")
	b.WriteString(module)
	b.WriteString("\n\ngo 1.22\n\nrequire github.com/binsarjr/sveltego v0.0.0\n")
	return b.String()
}

func renderReadme(module string) string {
	var b strings.Builder
	b.WriteString("# ")
	b.WriteString(module)
	b.WriteString("\n\n")
	b.WriteString("Generated by `sveltego-init`.\n\n")
	b.WriteString("## Develop\n\n")
	b.WriteString("```sh\nsveltego compile\ngo run ./cmd/app\n```\n\n")
	b.WriteString("## Layout\n\n")
	b.WriteString("- `src/routes/` — pages, layouts, server load/actions.\n")
	b.WriteString("- `src/lib/` — shared modules (`$lib` alias).\n")
	b.WriteString("- `hooks.server.go` — request lifecycle hooks.\n")
	b.WriteString("- `sveltego.config.go` — project config.\n")
	b.WriteString("- `.gen/` — generated Go from `.svelte` (gitignored).\n")
	return b.String()
}

const gitignoreBody = `.gen/
node_modules/
dist/
*.test
`

const configBody = `//go:build sveltego

// Package config holds the sveltego project configuration. The build tool
// reads this file at compile time.
package config

// Config returns the project-level settings consumed by ` + "`sveltego compile`" + `.
func Config() map[string]any {
	return map[string]any{
		"appDir": "_app",
	}
}
`

const hooksBody = `//go:build sveltego

package hooks

import "github.com/binsarjr/sveltego/exports/kit"

var Handle kit.HandleFn = func(ev *kit.RequestEvent, resolve kit.ResolveFn) (*kit.Response, error) {
	return resolve(ev)
}
`

const pageSvelteBody = `<script lang="go"></script>

<h1>{Data.Greeting}</h1>
`

const pageServerBody = `//go:build sveltego

package routes

import "github.com/binsarjr/sveltego/exports/kit"

type PageData struct {
	Greeting string
}

func Load(ctx *kit.LoadCtx) (PageData, error) {
	_ = ctx
	return PageData{Greeting: "Hello, sveltego!"}, nil
}
`

const layoutSvelteBody = `<script lang="go"></script>

<slot />
`
