// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /eachtest

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /eachtest.
func Render(payload *server.Payload, data PageData) {
	each_array := data.Links
	ssvar_length := len(each_array)
	for ssvar_index := 0; ssvar_index < ssvar_length; ssvar_index++ {
		link := each_array[ssvar_index]
		payload.Push("<a href=\"")
		payload.Push(server.EscapeHTML(link.Href))
		payload.Push("\">")
		payload.Push(server.EscapeHTML(link.Label))
		payload.Push("</a>")
	}
}
