// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /__error__/test

package errorsrc

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /__error__/test.
func Render(payload *server.Payload, data ErrorData) {
	error := data
	payload.Push(server.Stringify(server.EscapeHTML(error.Message)))
}
