// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /optchain

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /optchain.
func Render(payload *server.Payload, data PageData) {
	active := server.Fallback(data.Active, false)
	payload.Push(server.Stringify(server.EscapeHTML(active)))
}
