// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /undef

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /undef.
func Render(payload *server.Payload, data PageData) {
	payload.Push("<a")
	payload.Push(server.Attr("aria-current", func() any {
		if server.Truthy(data.Active) {
			return "page"
		}
		return nil
	}(), false))
	payload.Push(">Home</a>")
}
