// Code generated by sveltego typegen. DO NOT EDIT.
// Source: _page.server.go (Load return type)

export interface PageData {
	createdAt: string;
	updated: string | null;
}

export const data: PageData;
