package vite

import (
	"fmt"
	"strings"
)

// GenerateClientEntry returns the contents of a per-route entry.ts that
// hydrates the Svelte 5 component from the server-injected payload, then
// hands control to the shared SPA router for subsequent navigations.
// relSveltePath is the path to the .svelte file relative to the directory
// that will contain entry.ts; relRouterPath is the path to the shared
// router.ts module (without extension) likewise relative to entry.ts.
//
// The generated script reads the JSON payload injected by the server as
// <script id="sveltego-data" type="application/json">, calls Svelte 5's
// mount() to attach the component to document.body with the data and
// form props (#35, #36), then calls startRouter() so click and popstate
// take over for subsequent navigations (#37).
func GenerateClientEntry(relSveltePath, relRouterPath string) string {
	var b strings.Builder
	b.WriteString("// Code generated by sveltego — DO NOT EDIT.\n\n")
	b.WriteString("import { mount } from 'svelte';\n")
	fmt.Fprintf(&b, "import Page from %q;\n", relSveltePath)
	fmt.Fprintf(&b, "import { startRouter } from %q;\n\n", relRouterPath)
	b.WriteString("const el = document.getElementById('sveltego-data');\n")
	b.WriteString("const payload = el ? JSON.parse(el.textContent ?? '{}') : {};\n")
	b.WriteString("(window as any).__sveltego__ = payload;\n\n")
	b.WriteString("const component = mount(Page, {\n")
	b.WriteString("  target: document.body,\n")
	b.WriteString("  props: { data: payload.data, form: payload.form ?? null },\n")
	b.WriteString("});\n\n")
	b.WriteString("startRouter({ component, payload, target: document.body });\n")
	return b.String()
}

// RelativeSveltePath returns the relative path from a generated client entry
// directory to the .svelte source file at svelteSrcFromRoot (relative to
// project root). depth is how many directory levels the entry dir sits below
// the project root (e.g. .gen/client/routes/+page → depth=4).
func RelativeSveltePath(svelteSrcFromRoot string, depth int) string {
	prefix := strings.Repeat("../", depth)
	return prefix + svelteSrcFromRoot
}
