package vite

import (
	"fmt"
	"strings"
)

// ClientEntryOptions controls the per-route entry.ts emitted by
// GenerateClientEntry. RelSveltePath and RelRouterPath are paths from
// the entry directory; HasSnapshot opts the route into snapshot
// capture/restore via the SPA router (#84).
type ClientEntryOptions struct {
	RelSveltePath string
	RelRouterPath string
	HasSnapshot   bool
}

// GenerateClientEntry returns the contents of a per-route entry.ts that
// hydrates the Svelte 5 component from the server-injected payload, then
// hands control to the shared SPA router for subsequent navigations.
//
// The generated script reads the JSON payload injected by the server as
// <script id="sveltego-data" type="application/json">, calls Svelte 5's
// mount() to attach the component to document.body with the data and
// form props (#35, #36), exposes the use:enhance helper on
// window.__sveltego__ for user .svelte files (#39), then calls
// startRouter() so click and popstate take over subsequent navigations
// (#37). When opts.HasSnapshot is true, the page's `<script module>`
// snapshot export is forwarded to the router so back/forward navigation
// restores its state (#84).
func GenerateClientEntry(opts ClientEntryOptions) string {
	var b strings.Builder
	b.WriteString("// Code generated by sveltego — DO NOT EDIT.\n\n")
	b.WriteString("import { mount } from 'svelte';\n")
	b.WriteString("import { enhance } from './enhance';\n")
	if opts.HasSnapshot {
		fmt.Fprintf(&b, "import Page, { snapshot } from %q;\n", opts.RelSveltePath)
	} else {
		fmt.Fprintf(&b, "import Page from %q;\n", opts.RelSveltePath)
	}
	fmt.Fprintf(&b, "import { startRouter } from %q;\n", opts.RelRouterPath)
	// `.svelte.ts` (matched via the `.svelte` half here) routes the
	// state module through vite-plugin-svelte so its `$state` runes
	// compile rather than shipping raw to the browser (#471).
	relStatePath := strings.TrimSuffix(opts.RelRouterPath, "/router") + "/state.svelte"
	fmt.Fprintf(&b, "import { _setPage } from %q;\n\n", relStatePath)
	b.WriteString("const el = document.getElementById('sveltego-data');\n")
	b.WriteString("const payload = el ? JSON.parse(el.textContent ?? '{}') : {};\n")
	b.WriteString("(window as any).__sveltego__ = { ...payload, enhance };\n")
	// Seed $app/state before mount so user scripts that read
	// page.url / page.params / etc. on first render see the
	// hydration values rather than the initial defaults.
	b.WriteString("_setPage(payload);\n\n")
	b.WriteString("const component = mount(Page, {\n")
	b.WriteString("  target: document.body,\n")
	b.WriteString("  props: { data: payload.data, form: payload.form ?? null },\n")
	b.WriteString("});\n\n")
	b.WriteString("(window as any).__sveltego_hydrated = true;\n\n")
	if opts.HasSnapshot {
		b.WriteString("startRouter({ component, payload, target: document.body, snapshot });\n")
	} else {
		b.WriteString("startRouter({ component, payload, target: document.body });\n")
	}
	return b.String()
}

// RelativeSveltePath returns the relative path from a generated client
// entry directory to the .svelte source file at svelteSrcFromRoot
// (relative to project root). depth is how many directory levels the
// entry dir sits below the project root (e.g. .gen/client/routes/+page
// → depth=4).
func RelativeSveltePath(svelteSrcFromRoot string, depth int) string {
	prefix := strings.Repeat("../", depth)
	return prefix + svelteSrcFromRoot
}

// GenerateEnhanceRuntime returns the contents of the enhance.ts module
// emitted alongside every route's entry.ts. The module exports a Svelte
// action that intercepts <form> submission, posts the form via fetch
// with the X-Sveltego-Action header, and applies the result envelope
// returned by the server.
//
// The runtime supports the SvelteKit-shaped optional callback so user
// code can wrap or override default behavior:
//
//	use:enhance={({ form, data, action, cancel }) => {
//	    return async ({ result, update }) => {
//	        if (result.type === 'success') update();
//	    };
//	}}
//
// When no callback is provided the default applyResult updates
// window.__sveltego__.form on success/failure or navigates on redirect.
func GenerateEnhanceRuntime() string {
	return enhanceRuntimeSource
}

// enhanceRuntimeSource is the static TS source for the enhance action.
// Kept inline so the generator stays a pure function and the bytes are
// reproducible across builds.
const enhanceRuntimeSource = `// Code generated by sveltego — DO NOT EDIT.

export interface EnhanceEnvelope {
  type: 'success' | 'failure' | 'redirect' | 'error';
  status: number;
  data?: unknown;
  location?: string;
}

export interface SubmitContext {
  form: HTMLFormElement;
  data: FormData;
  action: URL;
  cancel: () => void;
}

export interface ResultContext {
  result: EnhanceEnvelope;
  formElement: HTMLFormElement;
  update: () => void;
}

export type SubmitHandler = (
  ctx: SubmitContext,
) => void | ((rc: ResultContext) => void | Promise<void>) | Promise<void | ((rc: ResultContext) => void | Promise<void>)>;

const ACTION_HEADER = 'X-Sveltego-Action';

function defaultApply(result: EnhanceEnvelope, form: HTMLFormElement) {
  const w = (window as any).__sveltego__ ?? {};
  switch (result.type) {
    case 'success':
    case 'failure':
      w.form = result.data ?? null;
      break;
    case 'redirect':
      if (result.location) {
        const router = (window as any).__sveltego_router__ as
          | { goto?: (href: string) => Promise<void>; matchManifest?: (p: string) => unknown }
          | undefined;
        try {
          const target = new URL(result.location, window.location.href);
          const internal = target.origin === window.location.origin;
          if (
            internal &&
            router?.matchManifest &&
            router.matchManifest(target.pathname) &&
            router.goto
          ) {
            void router.goto(target.href);
            break;
          }
        } catch (_e) {
          // Malformed Location -> fall through to full nav.
        }
        window.location.href = result.location;
      }
      break;
    case 'error':
      // Surface as a console error; user code can override via callback.
      console.error('[sveltego] action error', result);
      break;
  }
  (window as any).__sveltego__ = w;
  form.dispatchEvent(new CustomEvent('sveltego:action', { detail: result }));
}

async function parseEnvelope(res: Response): Promise<EnhanceEnvelope> {
  const ct = res.headers.get('content-type') ?? '';
  if (!ct.includes('application/json')) {
    return { type: 'error', status: res.status, data: await res.text() };
  }
  return (await res.json()) as EnhanceEnvelope;
}

export function enhance(form: HTMLFormElement, callback?: SubmitHandler) {
  const handler = async (e: SubmitEvent) => {
    e.preventDefault();
    const action = new URL(form.action || window.location.href, window.location.href);
    const data = new FormData(form);
    const submitter = e.submitter as HTMLButtonElement | HTMLInputElement | null;
    if (submitter && submitter.name) {
      data.append(submitter.name, (submitter as HTMLInputElement).value);
    }

    let aborted = false;
    const ctx: SubmitContext = {
      form,
      data,
      action,
      cancel: () => {
        aborted = true;
      },
    };

    let resultCb: ((rc: ResultContext) => void | Promise<void>) | void | undefined;
    if (callback) {
      resultCb = await callback(ctx);
    }
    if (aborted) return;

    let result: EnhanceEnvelope;
    try {
      const res = await fetch(action, {
        method: 'POST',
        body: data,
        headers: { [ACTION_HEADER]: '1' },
        credentials: 'same-origin',
      });
      result = await parseEnvelope(res);
    } catch (err) {
      result = {
        type: 'error',
        status: 0,
        data: err instanceof Error ? err.message : String(err),
      };
    }

    const update = () => defaultApply(result, form);
    if (typeof resultCb === 'function') {
      await resultCb({ result, formElement: form, update });
    } else {
      update();
    }
  };
  form.addEventListener('submit', handler);
  return {
    destroy() {
      form.removeEventListener('submit', handler);
    },
  };
}
`
