package vite

import (
	"fmt"
	"strings"
)

// ClientEntryOptions controls the per-route entry.ts emitted by
// GenerateClientEntry. RelSveltePath and RelRouterPath are paths from
// the entry directory; HasSnapshot opts the route into snapshot
// capture/restore via the SPA router (#84).
//
// RelWrapperPath, when non-empty, points at the per-route wrapper.svelte
// emitted by GenerateWrapper (see wrapper.go). The entry mounts the
// wrapper instead of the bare page so SSR-rendered layout markup
// survives hydration (#508). Routes with no _layout.svelte chain leave
// this empty and the generator falls back to mounting Page directly.
//
// LayoutChainKey is the deterministic identifier (SHA-1 prefix) of the
// route's layout chain — see LayoutChainKey. The entry forwards it to
// startRouter so SPA navigation across routes that share a chain can
// avoid unmounting the wrapper.
type ClientEntryOptions struct {
	RelSveltePath  string
	RelRouterPath  string
	RelWrapperPath string
	LayoutChainKey string
	HasSnapshot    bool
}

// GenerateClientEntry returns the contents of a per-route entry.ts that
// hydrates the Svelte 5 component from the server-injected payload, then
// hands control to the shared SPA router for subsequent navigations.
//
// The generated script reads the JSON payload injected by the server as
// <script id="sveltego-data" type="application/json">, then either:
//   - calls hydrate() against document.body when the server already
//     rendered the page (SSR / SSG modes — body holds matching markup), or
//   - calls mount() against the empty <div id="app"> shell injected by
//     renderEmptyShell / renderSvelteShell (SPA / Static modes).
//
// Choosing between hydrate and mount at runtime avoids two failure
// modes: mount-on-SSR appends a duplicate component below the SSR'd
// markup (no event handlers attach to the original DOM, counter stays
// dead); hydrate-on-empty-shell warns about a hydration mismatch and
// rebuilds. Exposes the use:enhance helper on window.__sveltego__ for
// user .svelte files (#39), then calls startRouter() so click and
// popstate take over subsequent navigations (#37). When
// opts.HasSnapshot is true, the page's `<script module>` snapshot
// export is forwarded to the router so back/forward navigation restores
// its state (#84).
func GenerateClientEntry(opts ClientEntryOptions) string {
	var b strings.Builder
	b.WriteString("// Code generated by sveltego — DO NOT EDIT.\n\n")
	b.WriteString("import { hydrate, mount } from 'svelte';\n")
	// Import the shared enhance runtime via the relative path that the
	// router and state modules also use. Vite additionally aliases
	// `$app/forms` to this same file so user code can write
	// `import { enhance } from '$app/forms'` exactly as in SvelteKit.
	relFormsPath := strings.TrimSuffix(opts.RelRouterPath, "/router") + "/forms"
	fmt.Fprintf(&b, "import { enhance } from %q;\n", relFormsPath)
	// When the route has a layout chain, the entry mounts the
	// chainKey-shared wrapper as Root and imports the page module
	// separately so it can seed wrapperState.Page before mount. The
	// shared wrapper renders the page through a dynamic rune slot, so
	// a same-chain SPA nav can swap the page reference without
	// unmounting (#518). When there is no chain we fall back to
	// mounting the page module directly with data/form props.
	useWrapper := opts.RelWrapperPath != ""
	switch {
	case useWrapper:
		fmt.Fprintf(&b, "import Root from %q;\n", opts.RelWrapperPath)
		if opts.HasSnapshot {
			fmt.Fprintf(&b, "import Page, { snapshot } from %q;\n", opts.RelSveltePath)
		} else {
			fmt.Fprintf(&b, "import Page from %q;\n", opts.RelSveltePath)
		}
	case opts.HasSnapshot:
		fmt.Fprintf(&b, "import Root, { snapshot } from %q;\n", opts.RelSveltePath)
	default:
		fmt.Fprintf(&b, "import Root from %q;\n", opts.RelSveltePath)
	}
	fmt.Fprintf(&b, "import { startRouter, afterNavigate } from %q;\n", opts.RelRouterPath)
	// `.svelte.ts` (matched via the `.svelte` half here) routes the
	// state module through vite-plugin-svelte so its `$state` runes
	// compile rather than shipping raw to the browser (#471).
	relStatePath := strings.TrimSuffix(opts.RelRouterPath, "/router") + "/state.svelte"
	fmt.Fprintf(&b, "import { _setPage, _startVersionPoller } from %q;\n", relStatePath)
	if useWrapper {
		// _setWrapperState seeds the chainKey-shared wrapper's rune
		// store before mount/hydrate so the layout chain and dynamic
		// page slot render against populated fields on first paint.
		// Without this seed the wrapper would render against an empty
		// rune (Page=null → SSR sees `<!--[!-->` else-branch markers,
		// client tries to hydrate a real page → mismatch) and trip
		// svelte/e/hydration_mismatch on every wrapped route (#518).
		relStoreFromEntry := strings.TrimSuffix(opts.RelRouterPath, "/router") + "/wrapper-store.svelte"
		fmt.Fprintf(&b, "import { _setWrapperState } from %q;\n", relStoreFromEntry)
	}
	b.WriteString("\n")
	b.WriteString("const el = document.getElementById('sveltego-data');\n")
	b.WriteString("const payload = el ? JSON.parse(el.textContent ?? '{}') : {};\n")
	b.WriteString("(window as any).__sveltego__ = { ...payload, enhance };\n")
	// Seed $app/state before mount so user scripts that read
	// page.url / page.params / etc. on first render see the
	// hydration values rather than the initial defaults. Also kick
	// off the version poller — only the first call has effect, so it
	// is safe to inline in every per-route entry script.
	b.WriteString("_setPage(payload);\n")
	if useWrapper {
		b.WriteString("_setWrapperState({\n")
		b.WriteString("  Page,\n")
		b.WriteString("  data: payload.data,\n")
		b.WriteString("  layoutData: payload.layoutData ?? [],\n")
		b.WriteString("  form: payload.form ?? null,\n")
		b.WriteString("});\n")
	}
	b.WriteString("if (payload.appVersion) _startVersionPoller(payload.appVersion, payload.versionPoll);\n\n")
	// renderEmptyShell + renderSvelteShell inject `<div id="app">` for
	// client-only routes; SSR/SSG render the page body directly so no
	// shell div is present. Pick the matching API at boot.
	b.WriteString("const appShell = document.getElementById('app');\n")
	b.WriteString("const target = appShell ?? document.body;\n")
	b.WriteString("const attach = appShell ? mount : hydrate;\n")
	b.WriteString("const component = attach(Root, {\n")
	b.WriteString("  target,\n")
	if useWrapper {
		// Wrapper takes zero props — it reads everything from the
		// wrapper-state rune that we just seeded above.
		b.WriteString("  props: {},\n")
	} else {
		b.WriteString("  props: { data: payload.data, form: payload.form ?? null },\n")
	}
	b.WriteString("});\n\n")
	// CSRF auto-inject for client-rendered POST forms (#510). The
	// build-time AST splice handles SSR; the runtime sidecar splice
	// handles fallback routes; this third path covers SPA / Static
	// routes whose forms are constructed in the browser. Reads from
	// window.__sveltego__.csrfToken so the value stays current after
	// SPA nav (router rewrites the global on every nav). Registered
	// via afterNavigate so the splicer re-fires on each navigation
	// (#541) — without it the second-and-later page rendered via
	// the client router has no hidden input and the user's first
	// POST returns 403.
	b.WriteString("const __sveltegoInjectCSRF = () => {\n")
	b.WriteString("  const t = (window as any).__sveltego__?.csrfToken;\n")
	b.WriteString("  if (!t) return;\n")
	b.WriteString("  const forms = target.querySelectorAll('form');\n")
	b.WriteString("  forms.forEach((f) => {\n")
	b.WriteString("    const m = (f.getAttribute('method') ?? '').toLowerCase();\n")
	b.WriteString("    if (m !== 'post') return;\n")
	b.WriteString("    if (f.querySelector('input[name=\"_csrf_token\"]')) return;\n")
	b.WriteString("    const input = document.createElement('input');\n")
	b.WriteString("    input.type = 'hidden';\n")
	b.WriteString("    input.name = '_csrf_token';\n")
	b.WriteString("    input.value = t;\n")
	b.WriteString("    f.insertBefore(input, f.firstChild);\n")
	b.WriteString("  });\n")
	b.WriteString("};\n")
	b.WriteString("queueMicrotask(__sveltegoInjectCSRF);\n")
	b.WriteString("afterNavigate(__sveltegoInjectCSRF);\n")
	b.WriteString("(window as any).__sveltego_csrf__ = __sveltegoInjectCSRF;\n\n")
	b.WriteString("(window as any).__sveltego_hydrated = true;\n\n")
	// Forward the layout chain identifier so the SPA router can swap
	// page slots in place when a navigation lands on a route that
	// shares the same chain (#508 acceptance criterion: layout state
	// survives navigation). Empty key means "no wrapper, no chain";
	// router treats every nav as full unmount/mount in that case.
	chainKey := opts.LayoutChainKey
	if opts.HasSnapshot {
		fmt.Fprintf(&b, "startRouter({ component, payload, target, snapshot, chainKey: %q });\n", chainKey)
	} else {
		fmt.Fprintf(&b, "startRouter({ component, payload, target, chainKey: %q });\n", chainKey)
	}
	return b.String()
}

// RelativeSveltePath returns the relative path from a generated client
// entry directory to the .svelte source file at svelteSrcFromRoot
// (relative to project root). depth is how many directory levels the
// entry dir sits below the project root (e.g. .gen/client/routes/+page
// → depth=4).
func RelativeSveltePath(svelteSrcFromRoot string, depth int) string {
	prefix := strings.Repeat("../", depth)
	return prefix + svelteSrcFromRoot
}

// GenerateEnhanceRuntime is a back-compat shim that returns the same
// source as GenerateFormsModule. The runtime now lives in a single
// shared module emitted to .gen/client/__router/forms.ts (#545); this
// alias is kept so existing tests and tooling continue to compile.
//
// Deprecated: import enhance via `$app/forms` (or call
// GenerateFormsModule directly).
func GenerateEnhanceRuntime() string {
	return GenerateFormsModule()
}
