package vite

import (
	"fmt"
	"strings"
)

// ConfigOptions controls what is emitted in the generated vite.config.gen.js.
type ConfigOptions struct {
	// OutDir is the Vite output directory relative to the project root.
	// Defaults to "static/_app".
	OutDir string
	// RouteKeys lists every route entry key, e.g. ["routes/+page",
	// "routes/post/[id]/+page"]. Each becomes a Rollup input so Vite
	// creates per-route chunks.
	RouteKeys []string
	// GenClientDir is the directory (relative to project root) where
	// codegen emitted the client entry .ts files, e.g. ".gen/client".
	GenClientDir string
	// Addons enumerates the build-time addons to wire in. Order is
	// stable: addons emit imports and plugin entries in the order
	// declared by ConfigOptions.Addons.
	Addons []Addon
	// CSSEntry, when non-empty, is added as a Rollup input under the key
	// "app". Required so addons that produce CSS (Tailwind, PostCSS) get
	// a hashed asset filename in the manifest. Path is relative to the
	// project root, e.g. "src/app.css".
	CSSEntry string
	// ServiceWorkerEntry, when non-empty, is the path (relative to the
	// project root) of the user's src/service-worker.ts source. The
	// generator emits a second Rollup build for it that outputs an
	// unhashed `service-worker.js` directly under static/, so the
	// runtime can register it at the document root scope ("/"). Empty
	// disables the service-worker build entirely (#89).
	ServiceWorkerEntry string
}

// GenerateConfig returns the contents of a vite.config.gen.js that
// processes every route in RouteKeys.
func GenerateConfig(opts ConfigOptions) string {
	outDir := opts.OutDir
	if outDir == "" {
		outDir = "static/_app"
	}
	genDir := opts.GenClientDir
	if genDir == "" {
		genDir = ".gen/client"
	}

	var b strings.Builder
	b.WriteString("// Code generated by sveltego — DO NOT EDIT.\n")
	b.WriteString("import { defineConfig } from 'vite';\n")
	b.WriteString("import { svelte } from '@sveltejs/vite-plugin-svelte';\n")
	if hasAddon(opts.Addons, AddonTailwindV4) {
		b.WriteString("import tailwindcss from '@tailwindcss/vite';\n")
	}
	b.WriteString("import { fileURLToPath } from 'url';\n")
	b.WriteString("import path from 'path';\n\n")
	b.WriteString("const __dirname = path.dirname(fileURLToPath(import.meta.url));\n\n")
	b.WriteString("export default defineConfig({\n")
	b.WriteString("  plugins: [svelte()")
	if hasAddon(opts.Addons, AddonTailwindV4) {
		b.WriteString(", tailwindcss()")
	}
	b.WriteString("],\n")
	if hasAddon(opts.Addons, AddonTailwindV3) {
		b.WriteString("  css: { postcss: './postcss.config.js' },\n")
	}
	// Alias the SvelteKit-style `$app/*` virtual modules to the codegen
	// outputs under `<genDir>/__router/`. User code imports `$app/state`
	// and `$app/navigation` exactly as they would on SvelteKit.
	b.WriteString("  resolve: {\n")
	b.WriteString("    alias: {\n")
	fmt.Fprintf(&b, "      %q: path.resolve(__dirname, %q),\n", "$app/state", genDir+"/__router/state")
	fmt.Fprintf(&b, "      %q: path.resolve(__dirname, %q),\n", "$app/navigation", genDir+"/__router/navigation")
	b.WriteString("    },\n")
	b.WriteString("  },\n")
	b.WriteString("  build: {\n")
	fmt.Fprintf(&b, "    outDir: %q,\n", outDir)
	b.WriteString("    manifest: true,\n")
	b.WriteString("    rollupOptions: {\n")
	b.WriteString("      input: {\n")
	for _, key := range opts.RouteKeys {
		entryPath := fmt.Sprintf("%s/%s/entry.ts", genDir, key)
		fmt.Fprintf(&b, "        %q: path.resolve(__dirname, %q),\n", key, entryPath)
	}
	if opts.CSSEntry != "" {
		fmt.Fprintf(&b, "        %q: path.resolve(__dirname, %q),\n", "app", opts.CSSEntry)
	}
	if opts.ServiceWorkerEntry != "" {
		fmt.Fprintf(&b, "        %q: path.resolve(__dirname, %q),\n", "service-worker", opts.ServiceWorkerEntry)
	}
	b.WriteString("      },\n")
	if opts.ServiceWorkerEntry != "" {
		// Keep service-worker.js unhashed and one directory above outDir so
		// it lives at the site root (/service-worker.js). Route chunks keep
		// the default hashed filename pattern.
		b.WriteString("      output: {\n")
		b.WriteString("        entryFileNames: (chunk) => chunk.name === 'service-worker' ? '../service-worker.js' : 'immutable/[name].[hash].js',\n")
		b.WriteString("        chunkFileNames: 'immutable/[name].[hash].js',\n")
		b.WriteString("        assetFileNames: 'immutable/assets/[name].[hash][extname]',\n")
		b.WriteString("      },\n")
	}
	b.WriteString("    },\n")
	b.WriteString("  },\n")
	b.WriteString("});\n")
	return b.String()
}
