package vite

import (
	"fmt"
	"strings"
)

// ConfigOptions controls what is emitted in the generated vite.config.gen.js.
type ConfigOptions struct {
	// OutDir is the Vite output directory relative to the project root.
	// Defaults to "static/_app".
	OutDir string
	// RouteKeys lists every route entry key, e.g. ["routes/+page",
	// "routes/post/[id]/+page"]. Each becomes a Rollup input so Vite
	// creates per-route chunks.
	RouteKeys []string
	// GenClientDir is the directory (relative to project root) where
	// codegen emitted the client entry .ts files, e.g. ".gen/client".
	GenClientDir string
	// Addons enumerates the build-time addons to wire in. Order is
	// stable: addons emit imports and plugin entries in the order
	// declared by ConfigOptions.Addons.
	Addons []Addon
	// CSSEntry, when non-empty, is added as a Rollup input under the key
	// "app". Required so addons that produce CSS (Tailwind, PostCSS) get
	// a hashed asset filename in the manifest. Path is relative to the
	// project root, e.g. "src/app.css".
	CSSEntry string
}

// GenerateConfig returns the contents of a vite.config.gen.js that
// processes every route in RouteKeys.
func GenerateConfig(opts ConfigOptions) string {
	outDir := opts.OutDir
	if outDir == "" {
		outDir = "static/_app"
	}
	genDir := opts.GenClientDir
	if genDir == "" {
		genDir = ".gen/client"
	}

	var b strings.Builder
	b.WriteString("// Code generated by sveltego — DO NOT EDIT.\n")
	b.WriteString("import { defineConfig } from 'vite';\n")
	b.WriteString("import { svelte } from '@sveltejs/vite-plugin-svelte';\n")
	if hasAddon(opts.Addons, AddonTailwindV4) {
		b.WriteString("import tailwindcss from '@tailwindcss/vite';\n")
	}
	b.WriteString("import { fileURLToPath } from 'url';\n")
	b.WriteString("import path from 'path';\n\n")
	b.WriteString("const __dirname = path.dirname(fileURLToPath(import.meta.url));\n\n")
	b.WriteString("export default defineConfig({\n")
	b.WriteString("  plugins: [svelte()")
	if hasAddon(opts.Addons, AddonTailwindV4) {
		b.WriteString(", tailwindcss()")
	}
	b.WriteString("],\n")
	if hasAddon(opts.Addons, AddonTailwindV3) {
		b.WriteString("  css: { postcss: './postcss.config.js' },\n")
	}
	b.WriteString("  build: {\n")
	fmt.Fprintf(&b, "    outDir: %q,\n", outDir)
	b.WriteString("    manifest: true,\n")
	b.WriteString("    rollupOptions: {\n")
	b.WriteString("      input: {\n")
	for _, key := range opts.RouteKeys {
		entryPath := fmt.Sprintf("%s/%s/entry.ts", genDir, key)
		fmt.Fprintf(&b, "        %q: path.resolve(__dirname, %q),\n", key, entryPath)
	}
	if opts.CSSEntry != "" {
		fmt.Fprintf(&b, "        %q: path.resolve(__dirname, %q),\n", "app", opts.CSSEntry)
	}
	b.WriteString("      },\n")
	b.WriteString("    },\n")
	b.WriteString("  },\n")
	b.WriteString("});\n")
	return b.String()
}
