package vite

// GenerateFormsModule returns the contents of the public-facing
// `$app/forms` runtime module emitted to .gen/client/__router/forms.ts.
//
// Mirrors SvelteKit's `$app/forms`: user code imports `enhance` and
// applies it as a Svelte action on a `<form method="post">` to opt
// into AJAX-style submission. The server returns a JSON envelope
// (`{type, status, data}`) when the request carries the
// `X-Sveltego-Action: 1` header that this runtime sets; on success
// or failure the default applier updates `window.__sveltego__.form`
// so the page's `form` prop reflects the action data without a full
// reload. On redirect the SPA router takes over for same-origin
// targets, falling back to a full nav for cross-origin or missing
// route matches.
//
// Without `use:enhance` the same form posts natively; the server
// re-renders the full page HTML with the action's data exposed via
// `form` and the browser performs a full reload — identical to
// SvelteKit's no-JS path.
func GenerateFormsModule() string {
	return formsModuleSource
}

const formsModuleSource = `// Code generated by sveltego — DO NOT EDIT.

export interface EnhanceEnvelope {
  type: 'success' | 'failure' | 'redirect' | 'error';
  status: number;
  data?: unknown;
  location?: string;
}

export interface SubmitContext {
  form: HTMLFormElement;
  data: FormData;
  action: URL;
  cancel: () => void;
}

export interface ResultContext {
  result: EnhanceEnvelope;
  formElement: HTMLFormElement;
  update: () => void;
}

export type SubmitHandler = (
  ctx: SubmitContext,
) => void | ((rc: ResultContext) => void | Promise<void>) | Promise<void | ((rc: ResultContext) => void | Promise<void>)>;

const ACTION_HEADER = 'X-Sveltego-Action';

function defaultApply(result: EnhanceEnvelope, form: HTMLFormElement) {
  const w = (window as any).__sveltego__ ?? {};
  switch (result.type) {
    case 'success':
    case 'failure':
      w.form = result.data ?? null;
      break;
    case 'redirect':
      if (result.location) {
        const router = (window as any).__sveltego_router__ as
          | { goto?: (href: string) => Promise<void>; matchManifest?: (p: string) => unknown }
          | undefined;
        try {
          const target = new URL(result.location, window.location.href);
          const internal = target.origin === window.location.origin;
          if (
            internal &&
            router?.matchManifest &&
            router.matchManifest(target.pathname) &&
            router.goto
          ) {
            void router.goto(target.href);
            break;
          }
        } catch (_e) {
          // Malformed Location -> fall through to full nav.
        }
        window.location.href = result.location;
      }
      break;
    case 'error':
      // Surface as a console error; user code can override via callback.
      console.error('[sveltego] action error', result);
      break;
  }
  (window as any).__sveltego__ = w;
  form.dispatchEvent(new CustomEvent('sveltego:action', { detail: result }));
}

async function parseEnvelope(res: Response): Promise<EnhanceEnvelope> {
  const ct = res.headers.get('content-type') ?? '';
  if (!ct.includes('application/json')) {
    return { type: 'error', status: res.status, data: await res.text() };
  }
  return (await res.json()) as EnhanceEnvelope;
}

export function enhance(form: HTMLFormElement, callback?: SubmitHandler) {
  const handler = async (e: SubmitEvent) => {
    e.preventDefault();
    const action = new URL(form.action || window.location.href, window.location.href);
    const data = new FormData(form);
    const submitter = e.submitter as HTMLButtonElement | HTMLInputElement | null;
    if (submitter && submitter.name) {
      data.append(submitter.name, (submitter as HTMLInputElement).value);
    }

    let aborted = false;
    const ctx: SubmitContext = {
      form,
      data,
      action,
      cancel: () => {
        aborted = true;
      },
    };

    let resultCb: ((rc: ResultContext) => void | Promise<void>) | void | undefined;
    if (callback) {
      resultCb = await callback(ctx);
    }
    if (aborted) return;

    let result: EnhanceEnvelope;
    try {
      const res = await fetch(action, {
        method: 'POST',
        body: data,
        headers: { [ACTION_HEADER]: '1' },
        credentials: 'same-origin',
      });
      result = await parseEnvelope(res);
    } catch (err) {
      result = {
        type: 'error',
        status: 0,
        data: err instanceof Error ? err.message : String(err),
      };
    }

    const update = () => defaultApply(result, form);
    if (typeof resultCb === 'function') {
      await resultCb({ result, formElement: form, update });
    } else {
      update();
    }
  };
  form.addEventListener('submit', handler);
  return {
    destroy() {
      form.removeEventListener('submit', handler);
    },
  };
}
`
