package vite

// GenerateNavigationModule returns the contents of the public-facing
// navigation.ts module that re-exports the $app/navigation surface from
// the shared SPA router. Emitted alongside router.ts at
// .gen/client/__router/navigation.ts so user code (or future preprocess
// step) imports a stable path independent of the router's internals.
func GenerateNavigationModule() string {
	return `// Code generated by sveltego — DO NOT EDIT.

export {
  goto,
  invalidate,
  invalidateAll,
  preloadData,
  preloadCode,
  pushState,
  replaceState,
  beforeNavigate,
  afterNavigate,
  onNavigate,
} from './router';
export type { GotoOpts, Navigation } from './router';
`
}
