package vite

import (
	"fmt"
	"sort"
	"strings"
)

// RouterOptions controls the per-route component map baked into the
// generated SPA router module.
type RouterOptions struct {
	// Routes maps each route's canonical pattern (matching the server's
	// router.Route.Pattern, also surfaced as `routeId` in the hydration
	// payload) to the path of its mount target — either a per-route
	// wrapper.svelte (when the route has a layout chain, see #508) or
	// the bare _page.svelte. Both paths resolve to a Svelte component
	// module relative to the directory containing router.ts.
	//
	// The generated module uses dynamic imports so each route's component
	// remains in its own Vite chunk; navigation only pulls in the chunk
	// for the destination route.
	Routes map[string]string
	// SnapshotRoutes flags route patterns whose _page.svelte exports a
	// `snapshot` from `<script module>`. The generated router pulls the
	// export from the module record returned by the dynamic import and
	// runs capture()/restore() across SPA navigations (#84). Patterns
	// missing from this map are treated as snapshot-free; the router
	// skips the dynamic-import lookup entirely for them.
	SnapshotRoutes map[string]bool
	// ChainKeys maps each route pattern to the deterministic identifier
	// of its layout chain (LayoutChainKey output). Routes with no
	// layout chain map to the empty string. The router compares the
	// destination's chain key against the currently mounted route's
	// chain key on every navigation: equal keys mean the wrapper
	// component is identical, so the router updates the shared
	// wrapper-state rune instead of unmounting (#508).
	ChainKeys map[string]string
}

// GenerateRouter returns the contents of a per-app SPA router module that
// the client entries import. It owns:
//
//   - global click interception with the SvelteKit-style opt-out matrix
//     (modifier keys, target=_blank, external host, download attr,
//     data-sveltego-reload).
//   - history.pushState/popState navigation backed by fetch(__data.json).
//   - swap of the active component via Svelte 5 unmount/mount.
//   - a per-navigation AbortController so rapid clicks cancel in-flight
//     requests cleanly.
//   - the public $app/navigation surface (goto, invalidate, invalidateAll,
//     preloadData, preloadCode, pushState, replaceState, beforeNavigate,
//     afterNavigate, onNavigate) — exported so navigation.ts can re-export
//     a stable user-facing module.
//   - declarative prefetch via data-sveltego-prefetch="hover|tap|viewport"
//     sharing the same payload + chunk cache as click navigation.
//
// The route table is read from the hydration payload at boot
// (window.__sveltego__.manifest); component constructors are loaded via
// the dynamic-import map baked in at codegen time so each chunk stays
// route-scoped.
//
// This file is regenerated whenever the route set changes; deleting a
// route prunes the import, adding one extends the map.
func GenerateRouter(opts RouterOptions) string {
	var b strings.Builder
	b.WriteString("// Code generated by sveltego — DO NOT EDIT.\n\n")
	b.WriteString("import { mount, unmount } from 'svelte';\n")
	// `state.svelte.ts` (with the `.svelte.ts` double extension) routes
	// the module through vite-plugin-svelte so its `$state` runes
	// compile to reactive implementations (#471). The import path keeps
	// the `.svelte` half so Vite's extension resolution lands on the
	// rune-bearing file rather than an unrelated `state.ts`.
	b.WriteString("import { _setPage, _setNavigating, type AppError } from './state.svelte';\n")
	// Same module-extension story for the wrapper-state rune — the
	// SPA router writes into it on every same-chain navigation so the
	// mounted wrapper.svelte reactively re-renders the page slot
	// without tearing down the layout chain (#508).
	b.WriteString("import { _setWrapperState } from './wrapper-store.svelte';\n\n")

	b.WriteString("type Segment = { kind: number; name?: string; value?: string };\n")
	b.WriteString("type ManifestEntry = { pattern: string; segments: Segment[] };\n")
	b.WriteString("export type Payload = {\n")
	b.WriteString("  routeId: string;\n")
	b.WriteString("  data: unknown;\n")
	b.WriteString("  layoutData?: unknown[];\n")
	b.WriteString("  form: unknown;\n")
	b.WriteString("  url: string;\n")
	b.WriteString("  params: Record<string, string>;\n")
	b.WriteString("  status: number;\n")
	b.WriteString("  error: AppError;\n")
	b.WriteString("  manifest?: ManifestEntry[];\n")
	b.WriteString("  deps?: string[];\n")
	b.WriteString("};\n\n")

	// chainKeys baked in at codegen time keys each route pattern to its
	// layout-chain identifier. Empty string = no wrapper (page mounts
	// directly). Routes sharing a key share a wrapper module, which
	// lets the runtime swap pages without unmounting the layout (#508).
	b.WriteString("const chainKeys: Record<string, string> = {\n")
	for _, k := range sortedKeys(opts.ChainKeys) {
		fmt.Fprintf(&b, "  %q: %q,\n", k, opts.ChainKeys[k])
	}
	b.WriteString("};\n\n")

	b.WriteString("export type GotoOpts = {\n")
	b.WriteString("  replaceState?: boolean;\n")
	b.WriteString("  noScroll?: boolean;\n")
	b.WriteString("  keepFocus?: boolean;\n")
	b.WriteString("  invalidateAll?: boolean;\n")
	b.WriteString("  state?: unknown;\n")
	b.WriteString("};\n\n")

	b.WriteString("export type Navigation = {\n")
	b.WriteString("  from: { url: URL } | null;\n")
	b.WriteString("  to: { url: URL };\n")
	b.WriteString("  type: 'link' | 'goto' | 'popstate' | 'form';\n")
	b.WriteString("};\n\n")

	b.WriteString("type Snapshot = { capture?: () => unknown; restore?: (state: unknown) => void };\n")
	// `page` is the wrapper's named re-export of the inner _page.svelte
	// component (see GenerateWrapper). Routes without a layout chain
	// don't ship a wrapper, so `page` is undefined for those and the
	// router falls back to mounting `default` (the page itself) full-tree.
	b.WriteString("type LoadedModule = { default: any; snapshot?: Snapshot; page?: any };\n")
	b.WriteString("type Loader = () => Promise<LoadedModule>;\n\n")

	b.WriteString("const loaders: Record<string, Loader> = {\n")
	for _, k := range sortedKeys(opts.Routes) {
		fmt.Fprintf(&b, "  %q: () => import(%q),\n", k, opts.Routes[k])
	}
	b.WriteString("};\n\n")

	b.WriteString("const snapshotRoutes: Record<string, true> = {\n")
	for _, k := range sortedSnapshotKeys(opts.SnapshotRoutes) {
		fmt.Fprintf(&b, "  %q: true,\n", k)
	}
	b.WriteString("};\n\n")

	b.WriteString(routerRuntime)
	return b.String()
}

func sortedSnapshotKeys(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for k, v := range m {
		if v {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)
	return keys
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// routerRuntime is the static body of the SPA router module — everything
// that does not depend on the per-app route set. Keeping it as a single
// const keeps GenerateRouter readable and lets the Go side hold one
// canonical TS source the codegen wraps around.
//
// Snapshot lifecycle (#84): each history entry can carry a snapshot
// captured from the active page before navigation. snapshots is a Map
// keyed by the leaving entry's history id so back/forward navigation
// can hand the stored value to the destination page's snapshot.restore.
// In-memory storage is required: history.state cannot reliably hold the
// outgoing snapshot because by the time popstate fires the browser has
// already swapped to the destination entry's state — replaceState would
// corrupt it. Storage is bounded by the navigator session; the browser
// imposes no fixed cap, but callers should still keep snapshots small
// (history.state's ~640KB Chromium / ~16MiB Firefox limits are a
// reasonable upper bound to design for if you want forward-compat with
// a future history.state-backed implementation). sveltego does not
// compress. Snapshots survive back/forward but not full reloads —
// reload-persistence is out of scope for v0.3.
const routerRuntime = `let mounted: any = null;
let manifest: ManifestEntry[] = [];
let activeAbort: AbortController | null = null;
const cache = new Map<string, Payload>();
const chunkCache = new Map<string, Promise<LoadedModule>>();
const scrolls = new Map<number, [number, number]>();
const snapshots = new Map<number, unknown>();
let nextHistoryId = 1;
let currentHistoryId = 0;
let currentSnapshot: Snapshot | null = null;
// currentChainKey is the layout-chain identifier of the currently
// mounted wrapper. Same-route reactive refreshes (invalidate(),
// query-string nav) write through the wrapper-state rune so the
// layout chain re-renders without unmounting; navigations to a
// different routeId always go through the unmount + mount path
// because each route owns a wrapper module with a STATIC <Page>
// import — reusing the wrapper instance across routes would render
// the prior route's page against the new payload (#508).
let currentChainKey: string = '';
// currentRouteId tracks the routeId of the currently mounted wrapper
// so the same-chain shortcut fires only on a same-route reactive
// refresh, never on a cross-route navigation within the same chain.
let currentRouteId: string = '';
const PREFETCH_CACHE_MAX = 30;
const PREFETCH_HOVER_DELAY_MS = 150;

const beforeHooks = new Set<(nav: Navigation & { cancel: () => void }) => void>();
const afterHooks = new Set<(nav: Navigation) => void>();
const onNavHooks = new Set<(nav: Navigation) => void | Promise<void>>();

// depRegistry maps each cache key to the set of dependency tags
// declared by that route's Load (via ctx.Depends("…")). invalidate()
// looks up which keys must be evicted.
const depRegistry = new Map<string, Set<string>>();
// activeKey is the cache key of the currently mounted route. invalidate
// uses it to decide which payloads must be refetched immediately
// vs simply evicted.
let activeKey: string = '';
// leaveCallbacks holds OnLeave registrations for the currently mounted
// page/layout. Fired in registration order at the next navigation
// commit, then cleared so a remount does not see prior callbacks.
let leaveCallbacks: Array<() => void> = [];
// MAX_REDIRECTS caps the chain fetchSPA follows so a misconfigured
// server can't loop the SPA router forever. Matches SvelteKit's default.
const MAX_REDIRECTS = 5;

export function startRouter(initial: {
  component: any;
  payload: Payload;
  target: HTMLElement;
  snapshot?: Snapshot;
  chainKey?: string;
}): void {
  mounted = initial.component;
  manifest = initial.payload.manifest ?? [];
  currentSnapshot = initial.snapshot ?? null;
  currentChainKey = initial.chainKey ?? '';
  currentRouteId = initial.payload.routeId ?? '';
  // Take ownership of scroll restoration so back/forward replays the
  // saved offsets instead of letting the browser race the mount.
  if ('scrollRestoration' in history) history.scrollRestoration = 'manual';
  currentHistoryId = nextHistoryId++;
  history.replaceState({ sveltego: 1, id: currentHistoryId }, '', initial.payload.url || location.href);
  const initKey = canonical(location.pathname + location.search);
  cache.set(initKey, initial.payload);
  recordDeps(initKey, initial.payload);
  activeKey = initKey;
  _setPage(initial.payload);

  document.addEventListener('click', onClick);
  window.addEventListener('popstate', onPopState);
  window.addEventListener('beforeunload', saveScroll);

  installPrefetch();

  // Expose programmatic surface to siblings (enhance runtime, user code)
  // without forcing them into the router import graph.
  (window as any).__sveltego_router__ = {
    goto,
    fetchSPA,
    onLeave,
    matchManifest,
    invalidate,
    invalidateAll,
    preloadData,
    preloadCode,
    pushState,
    replaceState,
    beforeNavigate,
    afterNavigate,
    onNavigate,
  };
}

function saveScroll(): void {
  scrolls.set(currentHistoryId, [window.scrollX, window.scrollY]);
}

function onClick(e: MouseEvent): void {
  if (e.defaultPrevented) return;
  if (e.button !== 0) return;
  if (e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
  const a = (e.target as Element | null)?.closest('a[href]') as HTMLAnchorElement | null;
  if (!a) return;
  if (shouldNotIntercept(a)) return;
  const url = new URL(a.href, location.href);
  if (url.origin !== location.origin) return;
  if (!matchManifest(url.pathname)) return;

  e.preventDefault();
  const replace = a.hasAttribute('data-sveltego-replacestate');
  const noscroll = a.hasAttribute('data-sveltego-noscroll');
  void navigate(url, { replace, noscroll, type: 'link' });
}

function onPopState(e: PopStateEvent): void {
  const url = new URL(location.href);
  const id = (e.state && (e.state as { id?: number }).id) || 0;
  void navigate(url, { replace: true, noscroll: true, fromPop: true, restoreId: id, type: 'popstate' });
}

export function shouldNotIntercept(a: HTMLAnchorElement): boolean {
  if (a.hasAttribute('data-sveltego-reload')) return true;
  if (a.hasAttribute('download')) return true;
  const target = a.getAttribute('target');
  if (target && target !== '' && target !== '_self') return true;
  const rel = (a.getAttribute('rel') || '').split(/\s+/);
  if (rel.includes('external')) return true;
  return false;
}

export function matchManifest(pathname: string): ManifestEntry | null {
  for (const entry of manifest) {
    if (matchEntry(entry, pathname)) return entry;
  }
  return null;
}

function matchEntry(entry: ManifestEntry, pathname: string): boolean {
  const parts = pathname.split('/').filter((p) => p !== '');
  const segs = entry.segments;
  let i = 0;
  let j = 0;
  while (j < segs.length) {
    const s = segs[j];
    switch (s.kind) {
      case 0: // static
        if (parts[i] !== s.value) return false;
        i++;
        j++;
        break;
      case 1: // param
        if (i >= parts.length) return false;
        i++;
        j++;
        break;
      case 2: // optional
        if (i < parts.length && (j === segs.length - 1 || !literalAhead(segs, j + 1, parts, i + 1))) {
          i++;
        }
        j++;
        break;
      case 3: // rest
        return true;
      default:
        return false;
    }
  }
  return i === parts.length;
}

function literalAhead(segs: Segment[], from: number, parts: string[], at: number): boolean {
  const next = segs[from];
  if (!next || next.kind !== 0) return false;
  return parts[at] === next.value;
}

type NavigateOpts = {
  replace?: boolean;
  noscroll?: boolean;
  fromPop?: boolean;
  restoreId?: number;
  state?: unknown;
  type?: Navigation['type'];
};

async function navigate(url: URL, opts: NavigateOpts): Promise<void> {
  if (activeAbort) activeAbort.abort();
  // Snapshot the outgoing scroll offset before swapping pages so popstate
  // back/forward can restore it.
  saveScroll();
  captureSnapshot();

  const fromURL = new URL(location.href);
  const navInfo: Navigation = {
    from: { url: fromURL },
    to: { url },
    type: opts.type ?? 'goto',
  };
  if (!runBeforeHooks(navInfo)) return;

  let resolveComplete!: () => void;
  const completePromise = new Promise<void>((res) => {
    resolveComplete = res;
  });
  _setNavigating({
    from: { url: fromURL, params: {}, route: { id: null } },
    to: { url, params: {}, route: { id: null } },
    type: navInfo.type,
    complete: completePromise,
  });
  const finishNavigating = (): void => {
    _setNavigating(null);
    resolveComplete();
  };

  const ctrl = new AbortController();
  activeAbort = ctrl;
  const key = canonical(url.pathname + url.search);

  let payload: Payload | null = cache.get(key) ?? null;
  if (!payload) {
    try {
      payload = await fetchPayload(url, ctrl.signal);
    } catch (err) {
      if ((err as { name?: string }).name === 'AbortError') {
        finishNavigating();
        return;
      }
      finishNavigating();
      location.assign(url.href);
      return;
    }
    if (!payload) {
      finishNavigating();
      location.assign(url.href);
      return;
    }
    cache.set(key, payload);
    recordDeps(key, payload);
  }
  if (activeAbort !== ctrl) {
    finishNavigating();
    return;
  }

  const entry = matchManifest(url.pathname);
  const routeId = entry?.pattern ?? payload.routeId;
  let mod: LoadedModule;
  try {
    mod = await loadChunk(routeId);
  } catch {
    finishNavigating();
    location.assign(url.href);
    return;
  }
  if (activeAbort !== ctrl) {
    finishNavigating();
    return;
  }

  if (!opts.fromPop) {
    currentHistoryId = nextHistoryId++;
    const state = { sveltego: 1, id: currentHistoryId, user: opts.state };
    history[opts.replace ? 'replaceState' : 'pushState'](state, '', url.href);
  } else if (opts.restoreId) {
    currentHistoryId = opts.restoreId;
  }

  const target = document.body;
  fireLeaveCallbacks();
  // Same-route reactive refresh shortcut (#508): when the navigation
  // resolves to the SAME routeId currently mounted (e.g. a goto with
  // a new query string, or invalidate-driven refetch), mutate the
  // wrapper-state rune in place so the layout chain re-renders
  // against the new payload without unmounting. Cross-route
  // navigation — even within the same layout chain — must still go
  // through unmount + mount because each route owns a wrapper module
  // with a STATIC <Page> import (reusing across routes would render
  // the wrong page component).
  const nextChainKey = chainKeys[routeId] ?? '';
  const sameRoute =
    nextChainKey !== '' &&
    nextChainKey === currentChainKey &&
    routeId === currentRouteId &&
    mounted !== null;
  if (sameRoute) {
    _setWrapperState({
      data: payload.data,
      layoutData: payload.layoutData ?? [],
      form: payload.form ?? null,
    });
  } else {
    if (mounted) {
      try {
        unmount(mounted);
      } catch (_e) {
        // mount() returned a non-unmountable value (rare with Svelte 5);
        // fall back to clearing the target so the next mount has a clean slate.
        target.innerHTML = '';
      }
    }
    if (nextChainKey !== '') {
      // Seed the wrapper-state rune BEFORE mount so the new wrapper's
      // layout chain and page render against populated fields on first
      // paint — same hydration parity contract as entry.ts (#508).
      _setWrapperState({
        data: payload.data,
        layoutData: payload.layoutData ?? [],
        form: payload.form ?? null,
      });
      mounted = mount(mod.default, { target, props: {} });
    } else {
      mounted = mount(mod.default, { target, props: { data: payload.data, form: payload.form ?? null } });
    }
    currentChainKey = nextChainKey;
    currentRouteId = routeId;
  }
  (window as any).__sveltego__ = payload;
  _setPage(payload, { state: opts.state as Record<string, unknown> | undefined });
  activeKey = key;
  // Update the active snapshot accessor before any restore call so a
  // page that captures during restore (rare, but allowed) sees its own
  // hooks rather than the previous route's.
  currentSnapshot = snapshotRoutes[routeId] ? mod.snapshot ?? null : null;
  if (opts.fromPop && opts.restoreId) {
    restoreSnapshot(opts.restoreId);
  }

  if (opts.fromPop && opts.restoreId) {
    const saved = scrolls.get(opts.restoreId);
    if (saved) window.scrollTo(saved[0], saved[1]);
  } else if (!opts.noscroll) {
    window.scrollTo(0, 0);
  }
  activeAbort = null;
  finishNavigating();
  runAfterHooks(navInfo);
}

function captureSnapshot(): void {
  if (!currentSnapshot || typeof currentSnapshot.capture !== 'function') return;
  try {
    snapshots.set(currentHistoryId, currentSnapshot.capture());
  } catch (err) {
    console.error('[sveltego] snapshot capture failed:', err);
  }
}

function restoreSnapshot(historyId: number): void {
  if (!currentSnapshot || typeof currentSnapshot.restore !== 'function') return;
  if (!snapshots.has(historyId)) return;
  try {
    currentSnapshot.restore(snapshots.get(historyId));
  } catch (err) {
    console.error('[sveltego] snapshot restore failed:', err);
  }
}

function canonical(pathSearch: string): string {
  return pathSearch.replace(/\/+$/, '') || '/';
}

function dataURLFor(url: URL): string {
  return url.pathname.replace(/\/$/, '') + '/__data.json' + url.search;
}

async function fetchPayload(url: URL, signal?: AbortSignal, speculative = false): Promise<Payload | null> {
  const headers: Record<string, string> = { 'x-sveltego-data': '1' };
  if (speculative) headers['x-sveltego-preload'] = '1';
  const res = await fetch(dataURLFor(url), { signal, headers });
  if (!res.ok) return null;
  return (await res.json()) as Payload;
}

function loadChunk(routeId: string): Promise<LoadedModule> {
  let p = chunkCache.get(routeId);
  if (p) return p;
  const loader = loaders[routeId];
  if (!loader) return Promise.reject(new Error('no loader for ' + routeId));
  p = loader();
  chunkCache.set(routeId, p);
  return p;
}

function recordDeps(key: string, payload: Payload): void {
  if (!payload.deps || payload.deps.length === 0) {
    depRegistry.delete(key);
    return;
  }
  depRegistry.set(key, new Set(payload.deps));
}

function runBeforeHooks(nav: Navigation): boolean {
  let cancelled = false;
  const cancel = (): void => {
    cancelled = true;
  };
  for (const h of beforeHooks) {
    try {
      h({ ...nav, cancel });
    } catch (_e) {
      // hook errors must not break navigation
    }
    if (cancelled) return false;
  }
  return true;
}

function runAfterHooks(nav: Navigation): void {
  for (const h of afterHooks) {
    try {
      h(nav);
    } catch (_e) {
      // hook errors must not break navigation
    }
  }
  for (const h of onNavHooks) {
    try {
      void h(nav);
    } catch (_e) {
      // hook errors must not break navigation
    }
  }
}

// goto programmatically navigates to url. Mirrors SvelteKit's
// $app/navigation.goto. When invalidateAll is true every cached payload
// is dropped before the fetch so stale data cannot serve.
export async function goto(url: string | URL, opts: GotoOpts = {}): Promise<void> {
  const target = typeof url === 'string' ? new URL(url, location.href) : url;
  if (target.origin !== location.origin) {
    location.assign(target.href);
    return;
  }
  if (opts.invalidateAll) {
    invalidateAll();
  }
  await navigate(target, {
    replace: opts.replaceState,
    noscroll: opts.noScroll,
    state: opts.state,
    type: 'goto',
  });
}

// invalidate refetches load data for every cached entry whose dep set
// matches target. Predicate form lets callers express patterns; string
// form is exact-match against the dep tag emitted by ctx.Depends.
export async function invalidate(target: string | ((url: URL) => boolean)): Promise<void> {
  const matchFn: (key: string, deps: Set<string>) => boolean =
    typeof target === 'function'
      ? (key) => target(new URL(key, location.origin))
      : (_k, deps) => deps.has(target);

  const stale: string[] = [];
  for (const [key, deps] of depRegistry) {
    if (matchFn(key, deps)) stale.push(key);
  }
  if (stale.length === 0) return;

  for (const key of stale) {
    cache.delete(key);
    depRegistry.delete(key);
  }

  if (stale.includes(activeKey)) {
    await refetchActive();
  }
}

// invalidateAll drops every cached payload and re-runs the active route.
export async function invalidateAll(): Promise<void> {
  cache.clear();
  depRegistry.clear();
  await refetchActive();
}

async function refetchActive(): Promise<void> {
  const url = new URL(location.href);
  try {
    const payload = await fetchPayload(url);
    if (!payload) return;
    const key = canonical(url.pathname + url.search);
    cache.set(key, payload);
    recordDeps(key, payload);
    // When a wrapper is mounted (#508) the wrapper-state rune is the
    // canonical reactive surface — writing to it propagates to both
    // the page and every layout slot. The legacy $set fallback covers
    // the no-wrapper, page-only mount path.
    if (currentChainKey !== '') {
      _setWrapperState({
        data: payload.data,
        layoutData: payload.layoutData ?? [],
        form: payload.form ?? null,
      });
    } else if (mounted && (mounted as { $set?: (p: unknown) => void }).$set) {
      (mounted as { $set: (p: unknown) => void }).$set({
        data: payload.data,
        form: payload.form ?? null,
      });
    }
    (window as any).__sveltego__ = payload;
    _setPage(payload);
  } catch (_e) {
    // network failure: leave existing payload in place
  }
}

// preloadData fetches and caches the data payload for href without
// navigating. Subsequent goto/click reuses the cached payload.
export async function preloadData(href: string | URL): Promise<void> {
  const url = typeof href === 'string' ? new URL(href, location.href) : href;
  if (url.origin !== location.origin) return;
  const key = canonical(url.pathname + url.search);
  if (cache.has(key)) return;
  if (cache.size >= PREFETCH_CACHE_MAX) {
    const oldest = cache.keys().next().value;
    if (oldest !== undefined) {
      cache.delete(oldest);
      depRegistry.delete(oldest);
    }
  }
  try {
    const payload = await fetchPayload(url, undefined, true);
    if (payload) {
      cache.set(key, payload);
      recordDeps(key, payload);
    }
  } catch (_e) {
    // best-effort prefetch: swallow errors
  }
}

// preloadCode warms the dynamic-import chunk for the route matching href
// so click navigation runs no extra round-trip.
export async function preloadCode(href: string | URL): Promise<void> {
  const url = typeof href === 'string' ? new URL(href, location.href) : href;
  if (url.origin !== location.origin) return;
  const entry = matchManifest(url.pathname);
  if (!entry) return;
  try {
    await loadChunk(entry.pattern);
  } catch (_e) {
    // best-effort prefetch: swallow errors
  }
}

// pushState updates the URL bar and stores per-entry user state without
// re-running Load. Use for shallow routing (modal overlays, tabs).
export function pushState(url: string | URL, state: unknown): void {
  const target = typeof url === 'string' ? new URL(url, location.href) : url;
  currentHistoryId = nextHistoryId++;
  history.pushState({ sveltego: 1, id: currentHistoryId, user: state }, '', target.href);
}

// replaceState updates the URL bar in place without re-running Load.
export function replaceState(url: string | URL, state: unknown): void {
  const target = typeof url === 'string' ? new URL(url, location.href) : url;
  history.replaceState({ sveltego: 1, id: currentHistoryId, user: state }, '', target.href);
}

// beforeNavigate registers fn to run before each navigation. fn may call
// nav.cancel() to abort. Returns an unsubscribe function.
export function beforeNavigate(fn: (nav: Navigation & { cancel: () => void }) => void): () => void {
  beforeHooks.add(fn);
  return () => beforeHooks.delete(fn);
}

// afterNavigate registers fn to run after each successful navigation.
// Returns an unsubscribe function.
export function afterNavigate(fn: (nav: Navigation) => void): () => void {
  afterHooks.add(fn);
  return () => afterHooks.delete(fn);
}

// onNavigate registers fn to run for each successful navigation. fn may
// return a Promise; the router does not await it. Returns an unsubscribe.
export function onNavigate(fn: (nav: Navigation) => void | Promise<void>): () => void {
  onNavHooks.add(fn);
  return () => onNavHooks.delete(fn);
}

// onLeave registers a cleanup callback to fire once when the next
// navigation commits away from the currently mounted page or layout.
// Use it to cancel in-flight subscriptions, clear intervals, or detach
// listeners that the page set up during its lifetime. Mirrors the
// SvelteKit ` + "`onLeave`" + ` proposal (#172).
export function onLeave(fn: () => void): void {
  if (typeof fn !== 'function') return;
  leaveCallbacks.push(fn);
}

function fireLeaveCallbacks(): void {
  const fns = leaveCallbacks;
  leaveCallbacks = [];
  for (const fn of fns) {
    try {
      fn();
    } catch (e) {
      console.error('[sveltego] onLeave callback threw', e);
    }
  }
}

// fetchSPA wraps fetch and follows 3xx responses via the SPA router when
// the Location header points at a known internal route. External
// targets and responses carrying X-Sveltego-Reload: 1 fall back to a
// full document load. Same-origin redirects to non-SPA paths chain
// through fetchSPA up to MAX_REDIRECTS so a server cannot loop the
// client.
export async function fetchSPA(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  const reqInit: RequestInit = { ...(init ?? {}), redirect: 'manual' };
  let current: Response = await fetch(input, reqInit);
  for (let hop = 0; hop < MAX_REDIRECTS; hop++) {
    if (!isRedirect(current.status)) return current;
    const loc = current.headers.get('location');
    if (!loc) return current;
    if (current.headers.get('x-sveltego-reload') === '1') {
      location.assign(loc);
      return current;
    }
    const target = new URL(loc, location.href);
    if (target.origin !== location.origin) {
      location.assign(target.href);
      return current;
    }
    if (matchManifest(target.pathname)) {
      await goto(target);
      return current;
    }
    // Same-origin but not a SPA route — could be another _server.go that
    // itself redirects. Re-fetch to allow chaining; cap protects loops.
    current = await fetch(target.href, reqInit);
  }
  console.warn('[sveltego] fetchSPA exceeded redirect cap (' + String(MAX_REDIRECTS) + ')');
  return current;
}

function isRedirect(status: number): boolean {
  return status === 301 || status === 302 || status === 303 || status === 307 || status === 308;
}

// installPrefetch wires the data-sveltego-prefetch="hover|tap|viewport"
// triggers. Hover and tap react to delegated events on document; viewport
// uses an IntersectionObserver that picks up matching links on first
// scan and on every DOM mutation under <body>.
function installPrefetch(): void {
  const hoverTimers = new WeakMap<HTMLAnchorElement, ReturnType<typeof setTimeout>>();

  document.addEventListener('mouseover', (e) => {
    const a = anchorFor(e.target);
    if (!a) return;
    if (resolvePrefetchMode(a) !== 'hover') return;
    if (hoverTimers.has(a)) return;
    const t = setTimeout(() => {
      hoverTimers.delete(a);
      void prefetchAnchor(a);
    }, PREFETCH_HOVER_DELAY_MS);
    hoverTimers.set(a, t);
  });
  document.addEventListener('mouseout', (e) => {
    const a = anchorFor(e.target);
    if (!a) return;
    const t = hoverTimers.get(a);
    if (t) {
      clearTimeout(t);
      hoverTimers.delete(a);
    }
  });
  document.addEventListener('focusin', (e) => {
    const a = anchorFor(e.target);
    if (!a) return;
    if (resolvePrefetchMode(a) !== 'hover') return;
    void prefetchAnchor(a);
  });
  document.addEventListener('pointerdown', (e) => {
    const a = anchorFor(e.target);
    if (!a) return;
    if (resolvePrefetchMode(a) !== 'tap') return;
    void prefetchAnchor(a);
  });
  document.addEventListener('touchstart', (e) => {
    const a = anchorFor(e.target);
    if (!a) return;
    if (resolvePrefetchMode(a) !== 'tap') return;
    void prefetchAnchor(a);
  }, { passive: true });

  installViewportPrefetch();
}

function installViewportPrefetch(): void {
  if (typeof IntersectionObserver === 'undefined') return;
  const seen = new WeakSet<HTMLAnchorElement>();
  const obs = new IntersectionObserver(
    (entries) => {
      for (const en of entries) {
        if (!en.isIntersecting) continue;
        const a = en.target as HTMLAnchorElement;
        obs.unobserve(a);
        void prefetchAnchor(a);
      }
    },
    { rootMargin: '64px' },
  );

  const scan = (): void => {
    const links = document.querySelectorAll<HTMLAnchorElement>('a[data-sveltego-prefetch="viewport"]');
    links.forEach((a) => {
      if (seen.has(a)) return;
      seen.add(a);
      obs.observe(a);
    });
  };
  scan();
  if (typeof MutationObserver !== 'undefined') {
    const mo = new MutationObserver(scan);
    mo.observe(document.body, { subtree: true, childList: true });
  }
}

function anchorFor(target: EventTarget | null): HTMLAnchorElement | null {
  if (!(target instanceof Element)) return null;
  return target.closest('a[href]') as HTMLAnchorElement | null;
}

type PrefetchMode = 'hover' | 'tap' | 'viewport' | 'off';

function resolvePrefetchMode(a: HTMLAnchorElement): PrefetchMode {
  if (saveDataEnabled()) return 'off';
  if (shouldNotIntercept(a)) return 'off';
  const url = new URL(a.href, location.href);
  if (url.origin !== location.origin) return 'off';
  if (!matchManifest(url.pathname)) return 'off';
  const own = a.dataset.sveltegoPrefetch as PrefetchMode | undefined;
  if (own) return own;
  const body = (document.body.dataset.sveltegoPrefetch as PrefetchMode | undefined) ?? 'hover';
  return body;
}

function saveDataEnabled(): boolean {
  const conn = (navigator as { connection?: { saveData?: boolean } }).connection;
  return !!(conn && conn.saveData);
}

async function prefetchAnchor(a: HTMLAnchorElement): Promise<void> {
  const url = new URL(a.href, location.href);
  await Promise.all([preloadData(url), preloadCode(url)]);
}
`
