package vite

import (
	"fmt"
	"sort"
	"strings"
)

// RouterOptions controls the per-route component map baked into the
// generated SPA router module.
type RouterOptions struct {
	// Routes maps each route's canonical pattern (matching the server's
	// router.Route.Pattern, also surfaced as `routeId` in the hydration
	// payload) to the path of its +page.svelte source relative to the
	// directory that will contain router.ts.
	//
	// The generated module uses dynamic imports so each route's component
	// remains in its own Vite chunk; navigation only pulls in the chunk
	// for the destination route.
	Routes map[string]string
}

// GenerateRouter returns the contents of a per-app SPA router module that
// the client entries import. It owns:
//
//   - global click interception with the SvelteKit-style opt-out matrix
//     (modifier keys, target=_blank, external host, download attr,
//     data-sveltego-reload).
//   - history.pushState/popState navigation backed by fetch(__data.json).
//   - swap of the active component via Svelte 5 unmount/mount.
//   - a per-navigation AbortController so rapid clicks cancel in-flight
//     requests cleanly.
//
// The route table is read from the hydration payload at boot
// (window.__sveltego__.manifest); component constructors are loaded via
// the dynamic-import map baked in at codegen time so each chunk stays
// route-scoped.
//
// This file is regenerated whenever the route set changes; deleting a
// route prunes the import, adding one extends the map.
func GenerateRouter(opts RouterOptions) string {
	var b strings.Builder
	b.WriteString("// Code generated by sveltego — DO NOT EDIT.\n\n")
	b.WriteString("import { mount, unmount } from 'svelte';\n\n")

	b.WriteString("type Segment = { kind: number; name?: string; value?: string };\n")
	b.WriteString("type ManifestEntry = { pattern: string; segments: Segment[] };\n")
	b.WriteString("type Payload = {\n")
	b.WriteString("  routeId: string;\n")
	b.WriteString("  data: unknown;\n")
	b.WriteString("  layoutData?: unknown[];\n")
	b.WriteString("  form: unknown;\n")
	b.WriteString("  url: string;\n")
	b.WriteString("  manifest?: ManifestEntry[];\n")
	b.WriteString("};\n\n")

	b.WriteString("type Loader = () => Promise<{ default: any }>;\n\n")

	b.WriteString("const loaders: Record<string, Loader> = {\n")
	for _, k := range sortedKeys(opts.Routes) {
		fmt.Fprintf(&b, "  %q: () => import(%q),\n", k, opts.Routes[k])
	}
	b.WriteString("};\n\n")

	b.WriteString(routerRuntime)
	return b.String()
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// routerRuntime is the static body of the SPA router module — everything
// that does not depend on the per-app route set. Keeping it as a single
// const keeps GenerateRouter readable and lets the Go side hold one
// canonical TS source the codegen wraps around.
const routerRuntime = `let mounted: any = null;
let manifest: ManifestEntry[] = [];
let activeAbort: AbortController | null = null;
const cache = new Map<string, Payload>();
const scrolls = new Map<number, [number, number]>();
let nextHistoryId = 1;
let currentHistoryId = 0;

export function startRouter(initial: { component: any; payload: Payload; target: HTMLElement }): void {
  mounted = initial.component;
  manifest = initial.payload.manifest ?? [];
  // Take ownership of scroll restoration so back/forward replays the
  // saved offsets instead of letting the browser race the mount.
  if ('scrollRestoration' in history) history.scrollRestoration = 'manual';
  currentHistoryId = nextHistoryId++;
  history.replaceState({ sveltego: 1, id: currentHistoryId }, '', initial.payload.url || location.href);
  cache.set(canonical(location.pathname + location.search), initial.payload);

  document.addEventListener('click', onClick);
  window.addEventListener('popstate', onPopState);
  window.addEventListener('beforeunload', saveScroll);
}

function saveScroll(): void {
  scrolls.set(currentHistoryId, [window.scrollX, window.scrollY]);
}

function onClick(e: MouseEvent): void {
  if (e.defaultPrevented) return;
  if (e.button !== 0) return;
  if (e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
  const a = (e.target as Element | null)?.closest('a[href]') as HTMLAnchorElement | null;
  if (!a) return;
  if (shouldNotIntercept(a)) return;
  const url = new URL(a.href, location.href);
  if (url.origin !== location.origin) return;
  if (!matchManifest(url.pathname)) return;

  e.preventDefault();
  const replace = a.hasAttribute('data-sveltego-replacestate');
  const noscroll = a.hasAttribute('data-sveltego-noscroll');
  void navigate(url, { replace, noscroll });
}

function onPopState(e: PopStateEvent): void {
  const url = new URL(location.href);
  const id = (e.state && (e.state as { id?: number }).id) || 0;
  void navigate(url, { replace: true, noscroll: true, fromPop: true, restoreId: id });
}

export function shouldNotIntercept(a: HTMLAnchorElement): boolean {
  if (a.hasAttribute('data-sveltego-reload')) return true;
  if (a.hasAttribute('download')) return true;
  const target = a.getAttribute('target');
  if (target && target !== '' && target !== '_self') return true;
  const rel = (a.getAttribute('rel') || '').split(/\s+/);
  if (rel.includes('external')) return true;
  return false;
}

export function matchManifest(pathname: string): ManifestEntry | null {
  for (const entry of manifest) {
    if (matchEntry(entry, pathname)) return entry;
  }
  return null;
}

function matchEntry(entry: ManifestEntry, pathname: string): boolean {
  const parts = pathname.split('/').filter((p) => p !== '');
  const segs = entry.segments;
  let i = 0;
  let j = 0;
  while (j < segs.length) {
    const s = segs[j];
    switch (s.kind) {
      case 0: // static
        if (parts[i] !== s.value) return false;
        i++;
        j++;
        break;
      case 1: // param
        if (i >= parts.length) return false;
        i++;
        j++;
        break;
      case 2: // optional
        if (i < parts.length && (j === segs.length - 1 || !literalAhead(segs, j + 1, parts, i + 1))) {
          i++;
        }
        j++;
        break;
      case 3: // rest
        return true;
      default:
        return false;
    }
  }
  return i === parts.length;
}

function literalAhead(segs: Segment[], from: number, parts: string[], at: number): boolean {
  const next = segs[from];
  if (!next || next.kind !== 0) return false;
  return parts[at] === next.value;
}

async function navigate(
  url: URL,
  opts: { replace?: boolean; noscroll?: boolean; fromPop?: boolean; restoreId?: number },
): Promise<void> {
  if (activeAbort) activeAbort.abort();
  // Snapshot the outgoing scroll offset before swapping pages so popstate
  // back/forward can restore it.
  saveScroll();
  const ctrl = new AbortController();
  activeAbort = ctrl;
  const key = canonical(url.pathname + url.search);
  const dataURL = url.pathname.replace(/\/$/, '') + '/__data.json' + url.search;

  let payload: Payload | null = cache.get(key) ?? null;
  if (!payload) {
    try {
      const res = await fetch(dataURL, {
        signal: ctrl.signal,
        headers: { 'x-sveltego-data': '1' },
      });
      if (!res.ok) {
        location.assign(url.href);
        return;
      }
      payload = (await res.json()) as Payload;
      cache.set(key, payload);
    } catch (err) {
      if ((err as { name?: string }).name === 'AbortError') return;
      location.assign(url.href);
      return;
    }
  }
  if (activeAbort !== ctrl) return;

  const entry = matchManifest(url.pathname);
  const routeId = entry?.pattern ?? payload.routeId;
  const loader = loaders[routeId];
  if (!loader) {
    location.assign(url.href);
    return;
  }
  const mod = await loader();
  if (activeAbort !== ctrl) return;

  if (!opts.fromPop) {
    currentHistoryId = nextHistoryId++;
    history[opts.replace ? 'replaceState' : 'pushState']({ sveltego: 1, id: currentHistoryId }, '', url.href);
  } else if (opts.restoreId) {
    currentHistoryId = opts.restoreId;
  }

  const target = document.body;
  if (mounted) {
    try {
      unmount(mounted);
    } catch (_e) {
      // mount() returned a non-unmountable value (rare with Svelte 5);
      // fall back to clearing the target so the next mount has a clean slate.
      target.innerHTML = '';
    }
  }
  mounted = mount(mod.default, {
    target,
    props: { data: payload.data, form: payload.form ?? null },
  });
  (window as any).__sveltego__ = payload;

  if (opts.fromPop && opts.restoreId) {
    const saved = scrolls.get(opts.restoreId);
    if (saved) window.scrollTo(saved[0], saved[1]);
  } else if (!opts.noscroll) {
    window.scrollTo(0, 0);
  }
  activeAbort = null;
}

function canonical(pathSearch: string): string {
  return pathSearch.replace(/\/+$/, '') || '/';
}
`
