package vite

// GenerateStateModule returns the contents of the public-facing
// `$app/state` runtime module emitted to .gen/client/__router/state.ts.
//
// Surface mirrors SvelteKit's `$app/state` (Svelte 5 runes idiom):
//
//   - `page`           — read-only object with url, params, route, status,
//     error, data, form, state.
//   - `navigating`     — null when idle, { from, to, type, complete } during
//     an in-progress navigation.
//   - `updated.current` — boolean signal flipped to true when the version
//     poll detects a new build.
//
// On the server (where Svelte runs at build time for SSG prerender),
// `$state` runes degrade to plain values and `navigating` / `updated`
// stay at their initial null/false. On the client the runes power
// reactive subscribers without requiring stores.
//
// The module exposes _setPage / _setNavigating / _setUpdated setters
// consumed by the generated SPA router so user code only ever reads
// `page`, `navigating`, `updated`. Setters are namespaced with a single
// leading underscore to keep them out of the public surface while still
// being importable from sibling generated modules.
func GenerateStateModule() string {
	return stateModuleSource
}

const stateModuleSource = `// Code generated by sveltego — DO NOT EDIT.

export type AppError = {
  message: string;
  status: number;
} | null;

export type PageRoute = { id: string | null };

export type Page<Data = unknown, FormResult = unknown, State = Record<string, unknown>> = {
  url: URL;
  params: Record<string, string>;
  route: PageRoute;
  status: number;
  error: AppError;
  data: Data;
  form: FormResult;
  state: State;
};

export type NavigationType = 'link' | 'goto' | 'popstate' | 'form' | 'enter';

export type Navigation = {
  from: { url: URL; params: Record<string, string>; route: PageRoute } | null;
  to: { url: URL; params: Record<string, string>; route: PageRoute } | null;
  type: NavigationType;
  complete: Promise<void>;
};

export type HydrationPayload = {
  routeId: string;
  data: unknown;
  form: unknown;
  url: string;
  params: Record<string, string>;
  status: number;
  error: AppError;
};

const initialPage: Page = {
  url: typeof location === 'undefined' ? new URL('http://localhost/') : new URL(location.href),
  params: {},
  route: { id: null },
  status: 200,
  error: null,
  data: {},
  form: null,
  state: {},
};

let pageState = $state<Page>(initialPage);
let navigatingState = $state<Navigation | null>(null);
let updatedFlag = $state(false);

export const page = {
  get url() {
    return pageState.url;
  },
  get params() {
    return pageState.params;
  },
  get route() {
    return pageState.route;
  },
  get status() {
    return pageState.status;
  },
  get error() {
    return pageState.error;
  },
  get data() {
    return pageState.data;
  },
  get form() {
    return pageState.form;
  },
  get state() {
    return pageState.state;
  },
};

export const navigating = {
  get current() {
    return navigatingState;
  },
};

export const updated = {
  get current() {
    return updatedFlag;
  },
  check: async (): Promise<boolean> => updatedFlag,
};

// _setPage hydrates pageState from a server payload. routeId, params,
// and url are pulled from the payload directly; state is read from
// history.state.user when available so pushState({state}) survives
// reloads (and SPA navigations can pass an explicit value).
export function _setPage(payload: HydrationPayload, opts?: { state?: Record<string, unknown> }): void {
  let url: URL;
  try {
    url = new URL(payload.url, typeof location === 'undefined' ? 'http://localhost/' : location.href);
  } catch (_err) {
    url = pageState.url;
  }
  const histState =
    typeof history !== 'undefined' && history.state && typeof history.state === 'object'
      ? ((history.state as { user?: unknown }).user as Record<string, unknown> | undefined)
      : undefined;
  pageState = {
    url,
    params: payload.params ?? {},
    route: { id: payload.routeId ?? null },
    status: payload.status ?? 200,
    error: payload.error ?? null,
    data: payload.data,
    form: payload.form ?? null,
    state: opts?.state ?? histState ?? {},
  };
}

// _setNavigating mutates navigatingState during an in-progress
// navigation. Pass null to clear (after the navigation commits).
export function _setNavigating(nav: Navigation | null): void {
  navigatingState = nav;
}

// _setUpdated flips the version-poll signal. The router calls this when
// a poll detects a new app version.
export function _setUpdated(value: boolean): void {
  updatedFlag = value;
}

// _readState extracts the user portion of history.state, mirroring
// SvelteKit's pushState({state}) survival across navigations.
export function _readState(): Record<string, unknown> {
  if (typeof history === 'undefined' || !history.state) return {};
  const s = history.state as { user?: unknown };
  return (s.user as Record<string, unknown>) ?? {};
}
`
