package vite

// GenerateStateModule returns the contents of the public-facing
// `$app/state` runtime module emitted to
// .gen/client/__router/state.svelte.ts. The `.svelte.ts` extension
// routes the file through vite-plugin-svelte so the `$state` runes
// inside compile to reactive implementations; a plain `.ts` extension
// would ship the literal `$state(...)` calls to the browser, which
// throws `ReferenceError: $state is not defined` at hydration (#471).
//
// Surface mirrors SvelteKit's `$app/state` (Svelte 5 runes idiom):
//
//   - `page`           — read-only object with url, params, route, status,
//     error, data, form, state.
//   - `navigating`     — null when idle, { from, to, type, complete } during
//     an in-progress navigation.
//   - `updated.current` — boolean signal flipped to true when the version
//     poll detects a new build.
//
// On the server (where Svelte runs at build time for SSG prerender),
// `$state` runes degrade to plain values and `navigating` / `updated`
// stay at their initial null/false. On the client the runes power
// reactive subscribers without requiring stores.
//
// The module exposes _setPage / _setNavigating / _setUpdated setters
// consumed by the generated SPA router so user code only ever reads
// `page`, `navigating`, `updated`. Setters are namespaced with a single
// leading underscore to keep them out of the public surface while still
// being importable from sibling generated modules.
func GenerateStateModule() string {
	return stateModuleSource
}

const stateModuleSource = `// Code generated by sveltego — DO NOT EDIT.

export type AppError = {
  message: string;
  status: number;
} | null;

export type PageRoute = { id: string | null };

export type Page<Data = unknown, FormResult = unknown, State = Record<string, unknown>> = {
  url: URL;
  params: Record<string, string>;
  route: PageRoute;
  status: number;
  error: AppError;
  data: Data;
  form: FormResult;
  state: State;
};

export type NavigationType = 'link' | 'goto' | 'popstate' | 'form' | 'enter';

export type Navigation = {
  from: { url: URL; params: Record<string, string>; route: PageRoute } | null;
  to: { url: URL; params: Record<string, string>; route: PageRoute } | null;
  type: NavigationType;
  complete: Promise<void>;
};

export type HydrationPayload = {
  routeId: string;
  data: unknown;
  form: unknown;
  url: string;
  params: Record<string, string>;
  status: number;
  error: AppError;
  appVersion?: string;
  versionPoll?: { intervalMs: number; disabled?: boolean };
};

const initialPage: Page = {
  url: typeof location === 'undefined' ? new URL('http://localhost/') : new URL(location.href),
  params: {},
  route: { id: null },
  status: 200,
  error: null,
  data: {},
  form: null,
  state: {},
};

let pageState = $state<Page>(initialPage);
let navigatingState = $state<Navigation | null>(null);
let updatedFlag = $state(false);

export const page = {
  get url() {
    return pageState.url;
  },
  get params() {
    return pageState.params;
  },
  get route() {
    return pageState.route;
  },
  get status() {
    return pageState.status;
  },
  get error() {
    return pageState.error;
  },
  get data() {
    return pageState.data;
  },
  get form() {
    return pageState.form;
  },
  get state() {
    return pageState.state;
  },
};

export const navigating = {
  get current() {
    return navigatingState;
  },
};

// VERSION_ENDPOINT mirrors the server-side path served by
// Server.serveVersion. Kept inline rather than threaded through the
// payload because the path is a hard-wired contract: the SvelteKit
// equivalent sits at the same spot, and clients running an older bundle
// against a newer server (or vice versa) still need to agree on it.
const VERSION_ENDPOINT = '/_app/version.json';

let buildVersion = '';

// updatedCheck is the on-demand check called by updated.check(). It
// fetches VERSION_ENDPOINT once, compares to buildVersion, flips the
// rune on drift, and returns whether the version differs. Errors and
// non-2xx responses resolve to false rather than throwing — matches
// SvelteKit's swallow-and-return behavior so user UI does not need a
// try/catch around updated.check().
async function updatedCheck(): Promise<boolean> {
  if (typeof fetch === 'undefined' || !buildVersion) return updatedFlag;
  try {
    const res = await fetch(VERSION_ENDPOINT, {
      headers: { pragma: 'no-cache', 'cache-control': 'no-cache' },
      cache: 'no-store',
    });
    if (!res.ok) return false;
    const data = (await res.json()) as { version?: string };
    const drifted = typeof data.version === 'string' && data.version !== buildVersion;
    if (drifted) updatedFlag = true;
    return drifted;
  } catch {
    return false;
  }
}

export const updated = {
  get current() {
    return updatedFlag;
  },
  check: updatedCheck,
};

// _setPage hydrates pageState from a server payload. routeId, params,
// and url are pulled from the payload directly; state is read from
// history.state.user when available so pushState({state}) survives
// reloads (and SPA navigations can pass an explicit value).
export function _setPage(payload: HydrationPayload, opts?: { state?: Record<string, unknown> }): void {
  let url: URL;
  try {
    url = new URL(payload.url, typeof location === 'undefined' ? 'http://localhost/' : location.href);
  } catch (_err) {
    url = pageState.url;
  }
  const histState =
    typeof history !== 'undefined' && history.state && typeof history.state === 'object'
      ? ((history.state as { user?: unknown }).user as Record<string, unknown> | undefined)
      : undefined;
  pageState = {
    url,
    params: payload.params ?? {},
    route: { id: payload.routeId ?? null },
    status: payload.status ?? 200,
    error: payload.error ?? null,
    data: payload.data,
    form: payload.form ?? null,
    state: opts?.state ?? histState ?? {},
  };
}

// _setNavigating mutates navigatingState during an in-progress
// navigation. Pass null to clear (after the navigation commits).
export function _setNavigating(nav: Navigation | null): void {
  navigatingState = nav;
}

// _setUpdated flips the version-poll signal. The router calls this when
// a poll detects a new app version.
export function _setUpdated(value: boolean): void {
  updatedFlag = value;
}

// _startVersionPoller boots the background poller against
// VERSION_ENDPOINT on the cadence supplied by the server (defaults to
// 60s, see kit.DefaultVersionPollInterval). Polling stops permanently
// once the rune flips to true so a stale tab never spams the endpoint.
//
// Errors and non-2xx responses retry with exponential backoff —
// doubling the interval on every consecutive failure up to MAX_BACKOFF
// — so a flapping endpoint or transient network drop does not produce
// a tight retry loop. A successful (2xx) response resets the backoff
// to the configured interval. SvelteKit's upstream poller uses a
// fixed cadence; we deviate intentionally per acceptance criteria
// (see issue #461).
//
// Idempotent: calling it twice is a no-op the second time. The poller
// runs only in browser contexts (the typeof guards below keep the SSR
// build-time evaluation pass from crashing on missing globals).
let pollerStarted = false;
const MAX_BACKOFF_MULT = 32;

export function _startVersionPoller(version: string, opts?: { intervalMs?: number; disabled?: boolean }): void {
  if (pollerStarted) return;
  pollerStarted = true;
  buildVersion = version;
  if (!version) return;
  if (opts?.disabled) return;
  if (typeof window === 'undefined' || typeof fetch === 'undefined') return;
  const baseInterval = Math.max(1000, opts?.intervalMs ?? 60000);
  let backoffMult = 1;
  const tick = async () => {
    let success = false;
    try {
      const res = await fetch(VERSION_ENDPOINT, {
        headers: { pragma: 'no-cache', 'cache-control': 'no-cache' },
        cache: 'no-store',
      });
      if (res.ok) {
        success = true;
        const data = (await res.json()) as { version?: string };
        if (typeof data.version === 'string' && data.version !== buildVersion) {
          updatedFlag = true;
          return;
        }
      }
    } catch {
      // network error; fall through to backoff path below
    }
    if (success) {
      backoffMult = 1;
    } else if (backoffMult < MAX_BACKOFF_MULT) {
      backoffMult *= 2;
    }
    window.setTimeout(tick, baseInterval * backoffMult);
  };
  window.setTimeout(tick, baseInterval);
}

// _readState extracts the user portion of history.state, mirroring
// SvelteKit's pushState({state}) survival across navigations.
export function _readState(): Record<string, unknown> {
  if (typeof history === 'undefined' || !history.state) return {};
  const s = history.state as { user?: unknown };
  return (s.user as Record<string, unknown>) ?? {};
}
`
