package vite

import (
	"crypto/sha1" //nolint:gosec // non-cryptographic identifier; sha1 is sufficient and matches existing codegen
	"encoding/hex"
	"fmt"
	"sort"
	"strings"
)

// ChainWrapperOptions controls the per-chainKey wrapper.svelte emitted
// by GenerateChainWrapper. One wrapper exists per layout chain (not per
// route, see #518): every route that walks the same `_layout.svelte`
// chain mounts the same wrapper module. The page slot is rendered
// dynamically — the wrapper reads `Page` (a Svelte component reference)
// from the shared wrapper-state rune, so a same-chain SPA navigation
// only swaps the rune fields and the wrapper instance is reused. That
// reuse is what preserves any `$state` declared in `_layout.svelte`
// across `/post/1 → /post/2`-shaped navigations.
//
// LayoutImports lists each layout component import path **relative to
// the wrapper file's directory**, ordered outermost → innermost. The
// ancestor `_layout.svelte` is index 0; the leaf-route's own
// `_layout.svelte` (when present) is the last entry. The chain itself
// is fixed per chainKey, so this list is identical across every route
// that shares the wrapper.
//
// StoreImport is the import path of the shared wrapper-store.svelte.ts
// module relative to the wrapper file. The wrapper takes zero props —
// each route's entry.ts seeds the rune store via `_setWrapperState`
// (with the route's Page module reference) before mount runs, so the
// layout chain and page render against populated rune fields on first
// paint. Reactive reads through the same store let the SPA router
// swap pages and refresh data without unmounting any layout instance.
type ChainWrapperOptions struct {
	LayoutImports []string
	StoreImport   string
}

// GenerateChainWrapper returns the contents of a chainKey-shared
// wrapper.svelte that nests the layout chain (outer → inner) around a
// dynamic `<Page>` slot. The slot reads the current page component out
// of the wrapper-state rune so cross-route same-chain SPA navs swap
// the page module without unmounting the wrapper — preserving any
// `$state` declared in `_layout.svelte` (#518 acceptance criterion 1).
//
// Hydration parity: Svelte 5 SSR wraps a dynamic-component slot in
// `<!--[-->...<!--]-->` markers (see svelte/internal/server's
// build_inline_component for `node.metadata.dynamic`). The Go SSR
// pipeline matches by emitting the same markers around the page body
// inside the chain composer (manifest.go's emitChainBody). Without
// matching markers the client hydration walker would trip
// `svelte/e/hydration_mismatch` on first paint.
func GenerateChainWrapper(opts ChainWrapperOptions) string {
	var b strings.Builder
	b.WriteString("<!-- Code generated by sveltego — DO NOT EDIT. -->\n")

	b.WriteString("<script lang=\"ts\">\n")
	for i, layout := range opts.LayoutImports {
		fmt.Fprintf(&b, "  import L%d from %q;\n", i, layout)
	}
	fmt.Fprintf(&b, "  import { wrapperState } from %q;\n", opts.StoreImport)
	// `Page` must be a $derived rune so cross-route same-chain SPA navs
	// (the SPA router writes a new wrapperState.Page) reactively swap
	// the page slot without unmounting the wrapper instance — that
	// reuse is what preserves layout-level $state across `/post/1 →
	// /post/2` navigations (#518).
	b.WriteString("  const Page = $derived(wrapperState.Page);\n")
	b.WriteString("</script>\n\n")

	indent := ""
	for i := range opts.LayoutImports {
		fmt.Fprintf(&b, "%s<L%d data={wrapperState.layoutData[%d] ?? {}}>\n", indent, i, i)
		indent += "  "
	}
	fmt.Fprintf(&b, "%s<Page data={wrapperState.data} form={wrapperState.form} />\n", indent)
	for i := len(opts.LayoutImports) - 1; i >= 0; i-- {
		indent = strings.Repeat("  ", i)
		fmt.Fprintf(&b, "%s</L%d>\n", indent, i)
	}
	return b.String()
}

// GenerateWrapperStoreModule returns the contents of the shared
// wrapper-store module emitted to .gen/client/__router/wrapper-store.svelte.ts.
// Every chainKey-shared wrapper imports `wrapperState` from this module
// to read its current page-component reference, data/layoutData/form
// trio, and form-action result. The SPA router writes to the same rune
// on a same-route reactive refresh AND on a cross-route same-chain
// navigation so the mounted wrapper instance reactively swaps the
// page slot without losing layout state (#518).
//
// The `.svelte.ts` extension routes the module through
// vite-plugin-svelte so its `$state` rune compiles to a reactive
// implementation, mirroring the convention used by state.svelte.ts (#471).
func GenerateWrapperStoreModule() string {
	return wrapperStoreSource
}

const wrapperStoreSource = `// Code generated by sveltego — DO NOT EDIT.

import type { Component } from 'svelte';

// wrapperState backs the chainKey-shared wrapper.svelte's reactivity
// contract (see #518). One wrapper module per layout chain — every
// route in the chain seeds this rune from $props() at mount, and reads
// from it for every render. On a same-route reactive refresh
// (invalidate, query-string change) OR a cross-route same-chain SPA
// nav, the SPA router writes the new payload here instead of
// unmounting; the reactive reads inside the wrapper flow new data and
// a (potentially new) page component reference through the layout
// chain in place, preserving any layout-level $state.
export const wrapperState = $state<{
  Page: Component<any> | null;
  data: unknown;
  layoutData: unknown[];
  form: unknown;
}>({
  Page: null,
  data: undefined,
  layoutData: [],
  form: null,
});

// _setWrapperState replaces the rune fields atomically so multiple
// reads inside the same render see consistent values. Exported with a
// leading underscore to keep it out of the public surface; only the
// generated SPA router and per-route entries call it.
export function _setWrapperState(next: {
  Page: Component<any> | null;
  data: unknown;
  layoutData: unknown[];
  form: unknown;
}): void {
  wrapperState.Page = next.Page;
  wrapperState.data = next.data;
  wrapperState.layoutData = next.layoutData;
  wrapperState.form = next.form;
}
`

// LayoutChainKey returns a deterministic short identifier for a layout
// chain — the SHA-1 of the joined absolute layout-directory paths. Two
// routes that walk the exact same _layout.svelte chain receive the same
// key, so the SPA router can recognise a navigation that stays within
// the same layout cascade and a single chainKey-shared wrapper module
// covers every route in the chain (#518).
//
// An empty chain yields the empty string; callers treat that as "no
// wrapper needed, mount the page component directly" (matching the
// pre-#508 behavior for routes with no layout).
func LayoutChainKey(layoutDirs []string) string {
	if len(layoutDirs) == 0 {
		return ""
	}
	// Order matters — the chain is ancestor→self — but we hash the
	// already-ordered slice as-is; the scanner emits a stable order.
	h := sha1.New() //nolint:gosec // identifier hash, not security-sensitive
	for i, d := range layoutDirs {
		if i > 0 {
			h.Write([]byte{0})
		}
		h.Write([]byte(d))
	}
	sum := h.Sum(nil)
	// 16 hex chars (64 bits) — collision-resistant enough for an
	// identifier space bounded by the number of unique layout chains
	// in a single project.
	return hex.EncodeToString(sum[:8])
}

// SortedChainKeys returns the unique chain keys of m in lexical order
// so generated maps stay deterministic across runs. Used by codegen
// emitters that walk a chainKey → wrapper-path map.
func SortedChainKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
