package vite

import (
	"crypto/sha1" //nolint:gosec // non-cryptographic identifier; sha1 is sufficient and matches existing codegen
	"encoding/hex"
	"fmt"
	"sort"
	"strings"
)

// WrapperOptions controls the per-route wrapper.svelte emitted by
// GenerateWrapper. A wrapper composes the SSR-cascading layout chain
// around the route's _page.svelte so that:
//
//   - The hydrated client tree shape matches the SSR DOM (layout +
//     page), eliminating Svelte's "extra DOM nodes" mismatch which
//     stripped <header>/<nav>/<footer> after first interaction (#508).
//   - SPA navigations that land on a route with the same layout chain
//     can swap only the page slot via a shared $state rune, so
//     layout-level state survives the navigation.
//
// LayoutImports lists each layout component import path **relative to
// the wrapper file's directory**, ordered outermost → innermost. The
// ancestor `_layout.svelte` is index 0; the leaf-route's own
// `_layout.svelte` (when present) is the last entry.
//
// PagePath is the import path for the route's `_page.svelte` (or its
// `_page@.svelte` reset variant) relative to the wrapper file.
//
// HasSnapshot, when true, also re-exports `snapshot` from the page
// module so the SPA router's snapshot capture/restore wiring
// continues to work for wrapped routes.
//
// StoreImport is the import path of the shared wrapper-store.svelte.ts
// module relative to the wrapper file. The wrapper writes its mount
// props into the store at construction so subsequent same-chain SPA
// navigations can reactively update the mounted tree.
type WrapperOptions struct {
	LayoutImports []string
	PagePath      string
	HasSnapshot   bool
	StoreImport   string
}

// GenerateWrapper returns the contents of a route-specific wrapper.svelte
// that nests the layout chain (outer → inner) around the page component.
// See WrapperOptions for the per-input semantics.
//
// Reactivity model: the wrapper reads layout/page/form props from a
// shared $state rune (wrapperState) imported from StoreImport. The
// initial mount seeds the store from $props() so the very first render
// is byte-identical to the SSR HTML; subsequent SPA navigations to a
// route that resolves to the SAME wrapper module simply mutate the
// store, which propagates through Svelte's reactivity into both the
// page and layout subtrees without unmounting any layout instance.
func GenerateWrapper(opts WrapperOptions) string {
	var b strings.Builder
	b.WriteString("<!-- Code generated by sveltego — DO NOT EDIT. -->\n")
	b.WriteString("<script lang=\"ts\">\n")
	for i, layout := range opts.LayoutImports {
		fmt.Fprintf(&b, "  import L%d from %q;\n", i, layout)
	}
	if opts.HasSnapshot {
		fmt.Fprintf(&b, "  import Page, { snapshot } from %q;\n", opts.PagePath)
		b.WriteString("  export { Page as page, snapshot };\n")
	} else {
		fmt.Fprintf(&b, "  import Page from %q;\n", opts.PagePath)
		b.WriteString("  export { Page as page };\n")
	}
	fmt.Fprintf(&b, "  import { wrapperState } from %q;\n\n", opts.StoreImport)
	b.WriteString("  let { data, layoutData = [], form = null, page = Page } = $props();\n\n")
	b.WriteString("  // Seed the shared store with the mount-time payload so the first render\n")
	b.WriteString("  // hydrates against the SSR HTML byte-for-byte. Same-chain SPA navigations\n")
	b.WriteString("  // mutate this store directly, which re-renders the page slot (and layout\n")
	b.WriteString("  // data) without tearing down the surrounding layout components — that is\n")
	b.WriteString("  // how layout-level $state survives navigation (#508).\n")
	b.WriteString("  wrapperState.data = data;\n")
	b.WriteString("  wrapperState.layoutData = layoutData;\n")
	b.WriteString("  wrapperState.form = form;\n")
	b.WriteString("  wrapperState.page = page;\n")
	b.WriteString("</script>\n\n")

	// Compose the layout chain outer→inner around the page slot. Each
	// layer reads its slice of layoutData from the shared store so SPA
	// nav updates propagate. The page slot itself is rendered through
	// a dynamic component reference so a same-chain navigation that
	// swaps `wrapperState.page` re-renders only the inner page —
	// layout components stay mounted, preserving their internal $state.
	indent := ""
	for i := range opts.LayoutImports {
		fmt.Fprintf(&b, "%s<L%d data={wrapperState.layoutData[%d] ?? {}}>\n", indent, i, i)
		indent += "  "
	}
	// `wrapperState.page` is always seeded from the `page = Page`
	// prop default before the first render, so the slot can render
	// unconditionally — no `{#if}` guard. An `{#if}` would inject
	// Svelte comment markers that are absent from the SSR HTML and
	// trip svelte/e/hydration_mismatch warnings on the first paint.
	fmt.Fprintf(&b, "%s{@const PageSlot = wrapperState.page}\n", indent)
	fmt.Fprintf(&b, "%s<PageSlot data={wrapperState.data} form={wrapperState.form} />\n", indent)
	for i := len(opts.LayoutImports) - 1; i >= 0; i-- {
		indent = strings.Repeat("  ", i)
		fmt.Fprintf(&b, "%s</L%d>\n", indent, i)
	}
	return b.String()
}

// GenerateWrapperStoreModule returns the contents of the shared
// wrapper-store module emitted to .gen/client/__router/wrapper-store.svelte.ts.
// Every per-route wrapper imports `wrapperState` from this module to
// read its current data/layoutData/form trio. The SPA router writes
// to the same rune on a same-chain navigation so the mounted wrapper
// instance reactively re-renders the page slot without losing layout
// state.
//
// The `.svelte.ts` extension routes the module through
// vite-plugin-svelte so its `$state` rune compiles to a reactive
// implementation, mirroring the convention used by state.svelte.ts (#471).
func GenerateWrapperStoreModule() string {
	return wrapperStoreSource
}

const wrapperStoreSource = `// Code generated by sveltego — DO NOT EDIT.

// wrapperState backs the per-route wrapper.svelte's reactivity contract
// (see #508). Each wrapper imports this single rune-backed object,
// seeds it from $props() at mount, and reads from it for every render.
// The SPA router mutates the same fields on a same-chain navigation so
// only the page slot (and any layout reading wrapperState.layoutData[i])
// re-renders — layout component instances stay mounted, preserving
// internal $state.
export const wrapperState = $state<{
  data: unknown;
  layoutData: unknown[];
  form: unknown;
  page: any;
}>({
  data: undefined,
  layoutData: [],
  form: null,
  page: null,
});

// _setWrapperState replaces the rune fields atomically so multiple
// reads inside the same render see consistent values. Exported with a
// leading underscore to keep it out of the public surface; only the
// generated SPA router calls it. The page argument is the destination
// route's page component, sourced from the wrapper module's named
// re-export (see GenerateWrapper) — same-chain navigation swaps the
// rendered slot without unmounting the surrounding layout chain.
export function _setWrapperState(next: {
  data: unknown;
  layoutData: unknown[];
  form: unknown;
  page: any;
}): void {
  wrapperState.data = next.data;
  wrapperState.layoutData = next.layoutData;
  wrapperState.form = next.form;
  wrapperState.page = next.page;
}
`

// LayoutChainKey returns a deterministic short identifier for a layout
// chain — the SHA-1 of the joined absolute layout-directory paths. Two
// routes that walk the exact same _layout.svelte chain receive the same
// key, so the SPA router can recognise a cross-route navigation that
// stays within the same layout cascade and swap only the page slot.
//
// An empty chain yields the empty string; callers treat that as "no
// wrapper needed, mount the page component directly" (matching the
// pre-#508 behavior for routes with no layout).
func LayoutChainKey(layoutDirs []string) string {
	if len(layoutDirs) == 0 {
		return ""
	}
	// Order matters — the chain is ancestor→self — but we hash the
	// already-ordered slice as-is; the scanner emits a stable order.
	h := sha1.New() //nolint:gosec // identifier hash, not security-sensitive
	for i, d := range layoutDirs {
		if i > 0 {
			h.Write([]byte{0})
		}
		h.Write([]byte(d))
	}
	sum := h.Sum(nil)
	// 16 hex chars (64 bits) — collision-resistant enough for an
	// identifier space bounded by the number of unique layout chains
	// in a single project.
	return hex.EncodeToString(sum[:8])
}

// SortedChainKeys returns the unique chain keys of m in lexical order
// so generated maps stay deterministic across runs. Used by codegen
// emitters that walk a chainKey → wrapper-path map.
func SortedChainKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
