package vite

import (
	"crypto/sha1" //nolint:gosec // non-cryptographic identifier; sha1 is sufficient and matches existing codegen
	"encoding/hex"
	"fmt"
	"sort"
	"strings"
)

// WrapperOptions controls the per-route wrapper.svelte emitted by
// GenerateWrapper. A wrapper composes the SSR-cascading layout chain
// around the route's _page.svelte so that the hydrated client tree
// shape matches the SSR DOM (layout + page), eliminating Svelte's
// "extra DOM nodes" mismatch which stripped <header>/<nav>/<footer>
// after first interaction (#508).
//
// LayoutImports lists each layout component import path **relative to
// the wrapper file's directory**, ordered outermost → innermost. The
// ancestor `_layout.svelte` is index 0; the leaf-route's own
// `_layout.svelte` (when present) is the last entry.
//
// PagePath is the import path for the route's `_page.svelte` (or its
// `_page@.svelte` reset variant) relative to the wrapper file.
//
// ModuleExports is the sorted list of names exported from the page's
// `<script module>` block (snapshot, plus any user additions). When
// non-empty, the wrapper imports those names alongside Page from the
// page module and re-exports them via its own `<script module>` block,
// keeping any external import that resolves through the wrapper path
// (e.g. entry.ts pulling `snapshot`) working. Re-exports MUST live in a
// `<script module>` block — Svelte 5 only treats module-level exports
// as ESM exports; an `export {…}` inside the instance `<script>` is
// parsed as the legacy props syntax and emits no actual export
// (vite errors with `"snapshot" is not exported by ".../wrapper.svelte"`).
//
// StoreImport is the import path of the shared wrapper-store.svelte.ts
// module relative to the wrapper file. The wrapper writes its mount
// props into the store inside a `$effect` so the rune system tracks
// the prop reads — bare top-level assignments only capture initial
// values and trigger Svelte's `state_referenced_locally` warning.
type WrapperOptions struct {
	LayoutImports []string
	PagePath      string
	ModuleExports []string
	StoreImport   string
}

// GenerateWrapper returns the contents of a route-specific wrapper.svelte
// that nests the layout chain (outer → inner) around the page component.
// See WrapperOptions for the per-input semantics.
//
// Hydration parity contract: the wrapper renders the page through a
// STATIC `<Page>` reference (matching how the Go SSR pipeline emits
// the page body inline inside the layout chain). Dynamic dispatch
// (`{#if}`, `{@const}`, `<svelte:component>`) injects Svelte comment
// anchors that are absent from the SSR HTML and trips
// `svelte/e/hydration_mismatch` warnings on first paint — that
// regression first surfaced on the basic playground's inert
// `_layout.svelte` (CI: hydration-parity job).
//
// Reactivity model: the wrapper writes its mount-time props into a
// shared `$state` rune (wrapperState) at construction time. Reactive
// reads through that store let the SPA router refresh layout/page
// data in place on a same-route navigation (an `invalidate` call,
// query-string change, etc.) without unmounting any layout instance.
// Cross-route navigations within the same chain still go through the
// router's unmount/mount path — wrapper modules are per-route, so
// reusing a wrapper instance across routes would render the prior
// route's statically imported Page against the new payload.
func GenerateWrapper(opts WrapperOptions) string {
	var b strings.Builder
	b.WriteString("<!-- Code generated by sveltego — DO NOT EDIT. -->\n")

	// Module-level re-exports must live in a `<script module>` block.
	// Svelte 5 parses `export {…}` inside the instance `<script>` as the
	// legacy prop syntax and emits no ESM export, so vite then fails with
	// `"snapshot" is not exported by ".../wrapper.svelte"`. The names are
	// imported here (not in the instance script) so the module-context
	// re-export resolves before the instance script runs.
	if len(opts.ModuleExports) > 0 {
		b.WriteString("<script module lang=\"ts\">\n")
		fmt.Fprintf(&b, "  export { %s } from %q;\n", strings.Join(opts.ModuleExports, ", "), opts.PagePath)
		b.WriteString("</script>\n\n")
	}

	b.WriteString("<script lang=\"ts\">\n")
	for i, layout := range opts.LayoutImports {
		fmt.Fprintf(&b, "  import L%d from %q;\n", i, layout)
	}
	fmt.Fprintf(&b, "  import Page from %q;\n", opts.PagePath)
	fmt.Fprintf(&b, "  import { wrapperState } from %q;\n\n", opts.StoreImport)
	b.WriteString("  let { data, layoutData = [], form = null } = $props();\n\n")
	b.WriteString("  // Seed the shared rune store with the mount-time payload. Same-route\n")
	b.WriteString("  // reactive refreshes (invalidate, query-string nav) write back to this\n")
	b.WriteString("  // store so the page and layout chain re-render against the new data\n")
	b.WriteString("  // without remounting (#508). Wrapped in $effect so the rune system\n")
	b.WriteString("  // tracks the prop reads — a bare top-level assignment captures only the\n")
	b.WriteString("  // initial value and trips state_referenced_locally.\n")
	b.WriteString("  $effect(() => {\n")
	b.WriteString("    wrapperState.data = data;\n")
	b.WriteString("    wrapperState.layoutData = layoutData;\n")
	b.WriteString("    wrapperState.form = form;\n")
	b.WriteString("  });\n")
	b.WriteString("</script>\n\n")

	// Compose the layout chain outer→inner around <Page/>. Each layer
	// reads its slice of layoutData from the shared store; the page
	// reads data + form. Static <Page> reference (not a dynamic
	// component) keeps the hydration-parity contract intact.
	indent := ""
	for i := range opts.LayoutImports {
		fmt.Fprintf(&b, "%s<L%d data={wrapperState.layoutData[%d] ?? {}}>\n", indent, i, i)
		indent += "  "
	}
	fmt.Fprintf(&b, "%s<Page data={wrapperState.data} form={wrapperState.form} />\n", indent)
	for i := len(opts.LayoutImports) - 1; i >= 0; i-- {
		indent = strings.Repeat("  ", i)
		fmt.Fprintf(&b, "%s</L%d>\n", indent, i)
	}
	return b.String()
}

// GenerateWrapperStoreModule returns the contents of the shared
// wrapper-store module emitted to .gen/client/__router/wrapper-store.svelte.ts.
// Every per-route wrapper imports `wrapperState` from this module to
// read its current data/layoutData/form trio. The SPA router writes
// to the same rune on a same-route reactive refresh (invalidate,
// query-string change) so the mounted wrapper instance reactively
// updates without losing layout state.
//
// The `.svelte.ts` extension routes the module through
// vite-plugin-svelte so its `$state` rune compiles to a reactive
// implementation, mirroring the convention used by state.svelte.ts (#471).
func GenerateWrapperStoreModule() string {
	return wrapperStoreSource
}

const wrapperStoreSource = `// Code generated by sveltego — DO NOT EDIT.

// wrapperState backs the per-route wrapper.svelte's reactivity contract
// (see #508). Each wrapper imports this single rune-backed object,
// seeds it from $props() at mount, and reads from it for every render.
// On a same-route reactive refresh (an invalidate call, a query-string
// change), the SPA router writes the new payload here instead of
// unmounting; the reactive reads inside the wrapper flow new data
// through both the layout chain and the page in place, preserving any
// layout-level $state.
export const wrapperState = $state<{
  data: unknown;
  layoutData: unknown[];
  form: unknown;
}>({
  data: undefined,
  layoutData: [],
  form: null,
});

// _setWrapperState replaces the rune fields atomically so multiple
// reads inside the same render see consistent values. Exported with a
// leading underscore to keep it out of the public surface; only the
// generated SPA router calls it.
export function _setWrapperState(next: {
  data: unknown;
  layoutData: unknown[];
  form: unknown;
}): void {
  wrapperState.data = next.data;
  wrapperState.layoutData = next.layoutData;
  wrapperState.form = next.form;
}
`

// LayoutChainKey returns a deterministic short identifier for a layout
// chain — the SHA-1 of the joined absolute layout-directory paths. Two
// routes that walk the exact same _layout.svelte chain receive the same
// key, so the SPA router can recognise a navigation that stays within
// the same layout cascade.
//
// An empty chain yields the empty string; callers treat that as "no
// wrapper needed, mount the page component directly" (matching the
// pre-#508 behavior for routes with no layout).
func LayoutChainKey(layoutDirs []string) string {
	if len(layoutDirs) == 0 {
		return ""
	}
	// Order matters — the chain is ancestor→self — but we hash the
	// already-ordered slice as-is; the scanner emits a stable order.
	h := sha1.New() //nolint:gosec // identifier hash, not security-sensitive
	for i, d := range layoutDirs {
		if i > 0 {
			h.Write([]byte{0})
		}
		h.Write([]byte(d))
	}
	sum := h.Sum(nil)
	// 16 hex chars (64 bits) — collision-resistant enough for an
	// identifier space bounded by the number of unique layout chains
	// in a single project.
	return hex.EncodeToString(sum[:8])
}

// SortedChainKeys returns the unique chain keys of m in lexical order
// so generated maps stay deterministic across runs. Used by codegen
// emitters that walk a chainKey → wrapper-path map.
func SortedChainKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
