// Code generated by sveltego typegen. DO NOT EDIT.
// Source: _page.server.go (Load return type)

export interface PageData {
	counts: Record<string, number>;
	labels: Record<string, string>;
}

export const data: PageData;
