// Code generated by sveltego typegen. DO NOT EDIT.
// Source: _page.server.go (Load return type)

export interface PageData {
	greeting: string;
	count: number;
	score: number;
	active: boolean;
}

export const data: PageData;
