// Package adapterlambda provides a build-time adapter that targets AWS
// Lambda. It emits a main package under .gen/lambda/ that wraps the
// user's HTTP handler with aws-lambda-go-api-proxy/httpadapter and a
// SAM template stub for one-command deploys.
//
// The emitted code requires the user to add three dependencies to
// their project's go.mod:
//
//	github.com/aws/aws-lambda-go
//	github.com/awslabs/aws-lambda-go-api-proxy
//
// Those modules are NOT pulled into this package — keeping the
// adapter's dependency surface minimal lets the rest of the workspace
// stay AWS-free for users targeting other platforms.
package adapterlambda

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/binsarjr/sveltego/adapter-lambda/internal/fsutil"
)

// Name is the canonical target name for this adapter.
const Name = "lambda"

// BuildContext describes the inputs the lambda adapter needs.
type BuildContext struct {
	// ProjectRoot is the absolute path of the user's project (the dir
	// containing go.mod). Required.
	ProjectRoot string

	// OutputDir is where the generated lambda main package and SAM
	// template are written. Defaults to ProjectRoot/.gen/lambda when
	// empty.
	OutputDir string

	// ModulePath is the user's Go module path (the value of `module ...`
	// in their go.mod). Required — used to import the user's
	// generated routes/hooks package.
	ModulePath string

	// HandlerName is the SAM logical-id for the function. Defaults to
	// "Sveltego".
	HandlerName string

	// MemoryMB is the SAM memory size. Defaults to 512.
	MemoryMB int

	// TimeoutSeconds is the SAM timeout. Defaults to 30.
	TimeoutSeconds int
}

// Build emits .gen/lambda/main.go and template.yaml.
func Build(ctx context.Context, bc BuildContext) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if bc.ProjectRoot == "" {
		return errors.New("adapter-lambda: ProjectRoot is required")
	}
	if bc.ModulePath == "" {
		return errors.New("adapter-lambda: ModulePath is required")
	}
	bc.applyDefaults()

	if err := os.MkdirAll(bc.OutputDir, 0o755); err != nil {
		return fmt.Errorf("adapter-lambda: create output dir: %w", err)
	}

	mainGo := renderMainGo(bc)
	if err := fsutil.WriteFile(filepath.Join(bc.OutputDir, "main.go"), mainGo, 0o644); err != nil {
		return fmt.Errorf("adapter-lambda: write main.go: %w", err)
	}
	sam := renderSAMTemplate(bc)
	if err := fsutil.WriteFile(filepath.Join(bc.OutputDir, "template.yaml"), sam, 0o644); err != nil {
		return fmt.Errorf("adapter-lambda: write template.yaml: %w", err)
	}
	return nil
}

// Doc returns deploy steps for the lambda target.
func Doc() string {
	return `Lambda target — API Gateway → Lambda → sveltego

Generated artefacts (default OutputDir is <ProjectRoot>/.gen/lambda/):

  main.go        — wraps router.Mux with httpadapter
  template.yaml  — SAM template stub (HTTP API + Function)

Steps:

  1. Add to your project's go.mod:
       go get github.com/aws/aws-lambda-go
       go get github.com/awslabs/aws-lambda-go-api-proxy
  2. sveltego-adapter build --target=lambda --module-path <module>
  3. cd .gen/lambda && GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o bootstrap .
  4. zip lambda.zip bootstrap
  5. sam deploy --template-file template.yaml --stack-name sveltego --resolve-s3

The wrapper expects the user's runtime to expose Mux() *http.ServeMux
(or any http.Handler) on the package generated under
<ModulePath>/.gen. Adjust main.go if your handler lives elsewhere.`
}

func (bc *BuildContext) applyDefaults() {
	if bc.OutputDir == "" {
		bc.OutputDir = filepath.Join(bc.ProjectRoot, ".gen", "lambda")
	}
	if bc.HandlerName == "" {
		bc.HandlerName = "Sveltego"
	}
	if bc.MemoryMB == 0 {
		bc.MemoryMB = 512
	}
	if bc.TimeoutSeconds == 0 {
		bc.TimeoutSeconds = 30
	}
}

const lambdaMainTemplate = `// Code generated by sveltego adapter-lambda. DO NOT EDIT.
package main

import (
	"context"
	"log"
	"net/http"
	"os"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/awslabs/aws-lambda-go-api-proxy/httpadapter"

	gen "{{ModulePath}}/.gen"
	"{{ModulePath}}/exports/kit/params"
	sveltegoserver "github.com/binsarjr/sveltego/server"
)

var adapter *httpadapter.HandlerAdapter

func init() {
	shell, err := os.ReadFile("app.html")
	if err != nil {
		log.Fatalf("adapter-lambda: read app.html: %v", err)
	}
	srv, err := sveltegoserver.New(sveltegoserver.Config{
		Routes:   gen.Routes(),
		Matchers: params.DefaultMatchers(),
		Shell:    string(shell),
		Hooks:    gen.Hooks(),
	})
	if err != nil {
		log.Fatalf("adapter-lambda: server.New: %v", err)
	}
	adapter = httpadapter.New(http.HandlerFunc(srv.ServeHTTP))
}

func handler(ctx context.Context, req events.APIGatewayV2HTTPRequest) (events.APIGatewayV2HTTPResponse, error) {
	resp, err := adapter.ProxyWithContext(ctx, eventToProxy(req))
	if err != nil {
		return events.APIGatewayV2HTTPResponse{}, err
	}
	return proxyToV2(resp), nil
}

func eventToProxy(req events.APIGatewayV2HTTPRequest) events.APIGatewayProxyRequest {
	return events.APIGatewayProxyRequest{
		HTTPMethod:                      req.RequestContext.HTTP.Method,
		Path:                            req.RawPath,
		Headers:                         req.Headers,
		QueryStringParameters:           req.QueryStringParameters,
		Body:                            req.Body,
		IsBase64Encoded:                 req.IsBase64Encoded,
	}
}

func proxyToV2(r events.APIGatewayProxyResponse) events.APIGatewayV2HTTPResponse {
	return events.APIGatewayV2HTTPResponse{
		StatusCode:      r.StatusCode,
		Headers:         r.Headers,
		Body:            r.Body,
		IsBase64Encoded: r.IsBase64Encoded,
	}
}

func main() { lambda.Start(handler) }
`

const samTemplate = `# Generated by sveltego adapter-lambda.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sveltego on AWS Lambda + API Gateway HTTP API

Resources:
  {{HandlerName}}Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures: [arm64]
      MemorySize: {{MemoryMB}}
      Timeout: {{TimeoutSeconds}}
      Events:
        Catchall:
          Type: HttpApi
          Properties:
            Method: ANY
            Path: /{proxy+}
        Root:
          Type: HttpApi
          Properties:
            Method: ANY
            Path: /

Outputs:
  ApiUrl:
    Description: HTTP API endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
`

func renderMainGo(bc BuildContext) string {
	out := lambdaMainTemplate
	out = strings.ReplaceAll(out, "{{ModulePath}}", bc.ModulePath)
	return out
}

func renderSAMTemplate(bc BuildContext) string {
	out := samTemplate
	out = strings.ReplaceAll(out, "{{HandlerName}}", bc.HandlerName)
	out = strings.ReplaceAll(out, "{{MemoryMB}}", strconv.Itoa(bc.MemoryMB))
	out = strings.ReplaceAll(out, "{{TimeoutSeconds}}", strconv.Itoa(bc.TimeoutSeconds))
	return out
}
