package codegen

import (
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"

	"github.com/binsarjr/sveltego/internal/assets"
)

// AssetsEmitOptions configures [GenerateAssetsManifest].
type AssetsEmitOptions struct {
	// PackageName is the package clause for the generated file. Defaults
	// to "gen" when empty.
	PackageName string
}

// GenerateAssetsManifest emits a deterministic, gofmt-clean Go source
// file declaring `var Assets = map[string]string{...}` and an init()
// that registers the table with kit.RegisterAssets so kit.Asset
// resolves hashed URLs at request time.
//
// The map keys are forward-slash relative paths under static/assets/
// (e.g. "logo.png", "img/banner.webp") and values are the hashed URLs
// produced by [assets.Build]. The output is sorted by key so codegen
// stays bit-identical across runs.
func GenerateAssetsManifest(plan assets.Plan, opts AssetsEmitOptions) ([]byte, error) {
	pkg := opts.PackageName
	if pkg == "" {
		pkg = "gen"
	}

	var keys []string
	if len(plan.Sources) > 0 {
		keys = append(keys, plan.Sources...)
	} else {
		keys = make([]string, 0, len(plan.URLs))
		for k := range plan.URLs {
			keys = append(keys, k)
		}
		sort.Strings(keys)
	}

	var b Builder
	b.Line("// Code generated by sveltego. DO NOT EDIT.")
	b.Linef("package %s", pkg)
	b.Line("")
	b.Line(`import "github.com/binsarjr/sveltego/exports/kit"`)
	b.Line("")

	if len(keys) == 0 {
		b.Line("// Assets is empty: no files were discovered under static/assets/.")
		b.Line("var Assets = map[string]string{}")
		b.Line("")
		b.Line("func init() { kit.RegisterAssets(Assets) }")
	} else {
		b.Line("// Assets maps each source path under static/assets/ to its hashed URL.")
		b.Line("var Assets = map[string]string{")
		b.Indent()
		for _, k := range keys {
			b.Linef("%s: %s,", quoteGo(k), quoteGo(plan.URLs[k]))
		}
		b.Dedent()
		b.Line("}")
		b.Line("")
		b.Line("func init() { kit.RegisterAssets(Assets) }")
	}

	if err := b.Err(); err != nil {
		return nil, err
	}
	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: format assets manifest: %w", err)
	}
	return out, nil
}

// emitAssetsManifest stages the asset pipeline and writes
// <projectRoot>/<outDir>/assets.gen.go. It is a thin wrapper that
// composes [assets.Build] and [GenerateAssetsManifest]; callers in
// the build pipeline use it so the orchestration stays in one place.
func emitAssetsManifest(projectRoot, outDir, packageName string) error {
	if !filepath.IsAbs(projectRoot) {
		return errors.New("codegen: emitAssetsManifest requires absolute projectRoot")
	}
	staticDir := filepath.Join(projectRoot, "static")
	plan, err := assets.Build(staticDir)
	if err != nil {
		return fmt.Errorf("codegen: build assets: %w", err)
	}
	src, err := GenerateAssetsManifest(plan, AssetsEmitOptions{PackageName: packageName})
	if err != nil {
		return err
	}
	target := filepath.Join(projectRoot, outDir, "assets.gen.go")
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("codegen: mkdir %s: %w", filepath.Dir(target), err)
	}
	if err := os.WriteFile(target, src, genFileMode); err != nil {
		return fmt.Errorf("codegen: write %s: %w", target, err)
	}
	return nil
}
