package codegen

import (
	"errors"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/binsarjr/sveltego/internal/ast"
)

// Options configures Generate.
type Options struct {
	// PackageName is written verbatim into the generated `package` clause.
	PackageName string
	// ServerFilePath optionally points at a sibling +page.server.go whose
	// Load() inline struct return is used to infer PageData fields.
	ServerFilePath string
	// HasActions is true when the sibling page.server.go declares
	// `var Actions kit.ActionMap`. The page's PageData gains a `Form any`
	// field so action result data can be threaded through the render.
	HasActions bool
	// Filename is the .svelte source path used to seed the CSS scope
	// hash so client and server agree on the `svelte-<hash>` class name.
	// Empty falls back to hashing the CSS body, matching upstream's
	// default cssHash rule.
	Filename string
}

// LayoutOptions configures GenerateLayout.
type LayoutOptions struct {
	// PackageName is written verbatim into the generated `package` clause.
	PackageName string
	// ServerFilePath optionally points at a sibling layout.server.go whose
	// Load() inline struct return is used to infer LayoutData fields.
	ServerFilePath string
	// Filename is the .svelte source path used to seed the CSS scope
	// hash so client and server agree on the `svelte-<hash>` class name.
	Filename string
}

// ErrorPageOptions configures GenerateErrorPage.
type ErrorPageOptions struct {
	// PackageName is written verbatim into the generated `package` clause.
	PackageName string
	// Filename is the .svelte source path used to seed the CSS scope hash.
	Filename string
}

// Generate lowers frag to Go source for a Page.Render method. The returned
// bytes pass through go/format so the caller receives canonically
// formatted Go.
func Generate(frag *ast.Fragment, opts Options) ([]byte, error) {
	if frag == nil {
		return nil, errors.New("codegen: nil fragment")
	}
	if opts.PackageName == "" {
		return nil, errors.New("codegen: empty package name")
	}

	svelteOpts, err := extractSvelteOptions(frag)
	if err != nil {
		return nil, err
	}
	scripts, err := extractScripts(frag)
	if err != nil {
		return nil, err
	}
	if err := validateRunesOption(svelteOpts, scripts); err != nil {
		return nil, err
	}
	style, err := extractStyle(frag, opts.Filename)
	if err != nil {
		return nil, err
	}
	applyScopeClass(frag.Children, style.ScopeClass)
	pageData, err := inferPageData(opts.ServerFilePath)
	if err != nil {
		return nil, err
	}
	if opts.HasActions {
		pageData.Fields = append(pageData.Fields, pageDataField{Name: "Form", Type: "any"})
	}

	imports := mergeImports(scripts.Imports, pageData.Imports)

	var b Builder
	b.Line("// Code generated by sveltego. DO NOT EDIT.")
	b.Linef("package %s", opts.PackageName)
	b.Line("")
	b.Line("import (")
	b.Indent()
	for _, imp := range imports {
		b.Line(imp)
	}
	b.Dedent()
	b.Line(")")
	b.Line("")

	for _, decl := range scripts.Decls {
		b.Line(decl)
		b.Line("")
	}

	b.Line("type Page struct{}")
	b.Line("")
	emitPageDataStruct(&b, pageData.Fields)
	b.Line("")
	if scripts.HasProps {
		emitPropsStruct(&b, scripts.Props)
		b.Line("")
	}
	b.Line("func (p Page) Render(w *render.Writer, ctx *kit.RenderCtx, data PageData) error {")
	b.Indent()
	b.Line("_ = ctx")
	b.Line("_ = data")
	if scripts.HasProps {
		b.Line("var props Props")
		b.Line("defaultProps(&props)")
		b.Line("_ = props")
	}
	emitRuneStmts(&b, scripts.RuneStmts)
	rejectRootConst(&b, frag.Children)
	emitChildren(&b, frag.Children)
	emitStyleBlock(&b, style)
	b.Line("return nil")
	b.Dedent()
	b.Line("}")

	if err := b.Err(); err != nil {
		return nil, err
	}

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: format generated source: %w", err)
	}
	return restoreRunesBytes(out), nil
}

// GenerateLayout lowers frag to Go source for a Layout.Render method.
// The signature mirrors Generate but accepts a `children` callback that
// any <slot /> element in the template lowers to. LayoutData is emitted
// as an empty type alias today; Phase 0k-B introduces real data via
// +layout.server.go.
func GenerateLayout(frag *ast.Fragment, opts LayoutOptions) ([]byte, error) {
	if frag == nil {
		return nil, errors.New("codegen: nil fragment")
	}
	if opts.PackageName == "" {
		return nil, errors.New("codegen: empty package name")
	}

	svelteOpts, err := extractSvelteOptions(frag)
	if err != nil {
		return nil, err
	}
	scripts, err := extractScripts(frag)
	if err != nil {
		return nil, err
	}
	if err := validateRunesOption(svelteOpts, scripts); err != nil {
		return nil, err
	}
	style, err := extractStyle(frag, opts.Filename)
	if err != nil {
		return nil, err
	}
	applyScopeClass(frag.Children, style.ScopeClass)
	layoutData, err := inferPageData(opts.ServerFilePath)
	if err != nil {
		return nil, err
	}

	imports := mergeImports(scripts.Imports, layoutData.Imports)

	var b Builder
	b.hasChildren = true
	b.Line("// Code generated by sveltego. DO NOT EDIT.")
	b.Linef("package %s", opts.PackageName)
	b.Line("")
	b.Line("import (")
	b.Indent()
	for _, imp := range imports {
		b.Line(imp)
	}
	b.Dedent()
	b.Line(")")
	b.Line("")

	for _, decl := range scripts.Decls {
		b.Line(decl)
		b.Line("")
	}

	b.Line("type Layout struct{}")
	b.Line("")
	emitLayoutDataAlias(&b, layoutData.Fields)
	b.Line("")
	if scripts.HasProps {
		emitPropsStruct(&b, scripts.Props)
		b.Line("")
	}
	b.Line("func (l Layout) Render(w *render.Writer, ctx *kit.RenderCtx, data LayoutData, children func(*render.Writer) error) error {")
	b.Indent()
	b.Line("_ = ctx")
	b.Line("_ = data")
	b.Line("_ = children")
	if scripts.HasProps {
		b.Line("var props Props")
		b.Line("defaultProps(&props)")
		b.Line("_ = props")
	}
	emitRuneStmts(&b, scripts.RuneStmts)
	rejectRootConst(&b, frag.Children)
	emitChildren(&b, frag.Children)
	emitStyleBlock(&b, style)
	b.Line("return nil")
	b.Dedent()
	b.Line("}")

	if err := b.Err(); err != nil {
		return nil, err
	}

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: format generated source: %w", err)
	}
	return restoreRunesBytes(out), nil
}

// GenerateErrorPage lowers a +error.svelte fragment to Go source for an
// ErrorPage.Render method. The render parameter binds to kit.SafeError so
// templates reference {data.Code}, {data.Message}, {data.ID} directly.
func GenerateErrorPage(frag *ast.Fragment, opts ErrorPageOptions) ([]byte, error) {
	if frag == nil {
		return nil, errors.New("codegen: nil fragment")
	}
	if opts.PackageName == "" {
		return nil, errors.New("codegen: empty package name")
	}

	svelteOpts, err := extractSvelteOptions(frag)
	if err != nil {
		return nil, err
	}
	scripts, err := extractScripts(frag)
	if err != nil {
		return nil, err
	}
	if err := validateRunesOption(svelteOpts, scripts); err != nil {
		return nil, err
	}
	style, err := extractStyle(frag, opts.Filename)
	if err != nil {
		return nil, err
	}
	applyScopeClass(frag.Children, style.ScopeClass)

	imports := mergeImports(scripts.Imports, nil)

	var b Builder
	b.Line("// Code generated by sveltego. DO NOT EDIT.")
	b.Linef("package %s", opts.PackageName)
	b.Line("")
	b.Line("import (")
	b.Indent()
	for _, imp := range imports {
		b.Line(imp)
	}
	b.Dedent()
	b.Line(")")
	b.Line("")

	for _, decl := range scripts.Decls {
		b.Line(decl)
		b.Line("")
	}

	b.Line("type ErrorPage struct{}")
	b.Line("")
	if scripts.HasProps {
		emitPropsStruct(&b, scripts.Props)
		b.Line("")
	}
	b.Line("func (e ErrorPage) Render(w *render.Writer, ctx *kit.RenderCtx, data kit.SafeError) error {")
	b.Indent()
	b.Line("_ = ctx")
	b.Line("_ = data")
	if scripts.HasProps {
		b.Line("var props Props")
		b.Line("defaultProps(&props)")
		b.Line("_ = props")
	}
	emitRuneStmts(&b, scripts.RuneStmts)
	rejectRootConst(&b, frag.Children)
	emitChildren(&b, frag.Children)
	emitStyleBlock(&b, style)
	b.Line("return nil")
	b.Dedent()
	b.Line("}")

	if err := b.Err(); err != nil {
		return nil, err
	}

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: format generated source: %w", err)
	}
	return restoreRunesBytes(out), nil
}

// emitLayoutDataAlias writes `type LayoutData = struct{...}` mirroring
// the alias-form rationale on emitPageDataStruct: type identity between
// the user's inline struct literal and the LayoutData symbol asserted
// by the manifest adapter must be preserved.
func emitLayoutDataAlias(b *Builder, fields []pageDataField) {
	if len(fields) == 0 {
		b.Line("type LayoutData = struct{}")
		return
	}
	b.Line("type LayoutData = struct {")
	b.Indent()
	for _, fd := range fields {
		b.Linef("%s %s", fd.Name, fd.Type)
	}
	b.Dedent()
	b.Line("}")
}

// mergeImports unions framework imports with script + pagedata imports,
// dedupes by full import path, and returns a stable-sorted slice ready to
// emit between `import (` and `)`.
func mergeImports(scriptImports, pageDataImports []string) []string {
	set := map[string]struct{}{
		`"github.com/binsarjr/sveltego/exports/kit"`: {},
		`"github.com/binsarjr/sveltego/render"`:      {},
	}
	for _, imp := range scriptImports {
		set[imp] = struct{}{}
	}
	for _, imp := range pageDataImports {
		set[imp] = struct{}{}
	}
	out := make([]string, 0, len(set))
	for k := range set {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// emitRuneStmts writes the lowered $state / $derived / $derived.by
// statements at the top of Render's body. $effect entries lower to a
// trailing comment marker so the generated source still records that an
// effect was elided; the marker carries no runtime cost.
func emitRuneStmts(b *Builder, stmts []runeStmt) {
	for _, s := range stmts {
		switch s.Kind {
		case runeEffect:
			b.Line("// $effect elided on SSR")
		default:
			if s.Body == "" {
				continue
			}
			b.Line(s.Body)
			if name := assignLHSName(s.Body); name != "" {
				b.Linef("_ = %s", name)
			}
		}
	}
}

// assignLHSName returns the LHS identifier of a `name := expr` line, or
// "" when src does not start with a short-var-decl. Used to emit a
// trailing `_ = name` so the Go compiler accepts vars that appear only
// in template mustaches the codegen pass has not yet observed.
func assignLHSName(src string) string {
	src = strings.TrimSpace(src)
	idx := strings.Index(src, ":=")
	if idx <= 0 {
		return ""
	}
	head := strings.TrimSpace(src[:idx])
	if !isIdent(head) {
		return ""
	}
	return head
}

// rejectRootConst latches a CodegenError when {@const} appears as a
// direct child of the template root. Svelte requires {@const} to live
// inside a block (e.g. {#each}, {#if}); a root-level declaration has no
// surrounding scope to attach to and is rejected at codegen time.
func rejectRootConst(b *Builder, children []ast.Node) {
	for _, c := range children {
		if cn, ok := c.(*ast.Const); ok {
			b.Fail(&CodegenError{
				Pos: cn.P,
				Msg: "{@const} not allowed at template root; place inside {#each}, {#if}, or another block",
			})
			return
		}
	}
}

// emitChildren walks a sibling list and dispatches by node kind. Adjacent
// Text nodes are merged before iteration so the emitted code has one
// WriteString per run.
func emitChildren(b *Builder, children []ast.Node) {
	merged := mergeAdjacentText(children)
	for _, child := range merged {
		emitNode(b, child)
	}
}

func emitNode(b *Builder, n ast.Node) {
	switch v := n.(type) {
	case *ast.Text:
		emitText(b, v)
	case *ast.Element:
		emitElement(b, v)
	case *ast.Mustache:
		emitMustache(b, v)
	case *ast.IfBlock:
		emitIfBlock(b, v)
	case *ast.EachBlock:
		emitEachBlock(b, v)
	case *ast.AwaitBlock:
		emitAwaitBlock(b, v)
	case *ast.KeyBlock:
		emitKeyBlock(b, v)
	case *ast.SnippetBlock:
		emitSnippetBlock(b, v)
	case *ast.RawHTML:
		emitRawHTML(b, v)
	case *ast.Const:
		emitConst(b, v)
	case *ast.Render:
		emitRender(b, v)
	case *ast.Script:
		// extracted to package scope by extractScripts
	case *ast.Style:
		// TODO: <style> extraction (#16)
	case *ast.Comment:
	}
}
