package codegen

import (
	"errors"
	"fmt"
	"go/format"
	"sort"

	"github.com/binsarjr/sveltego/internal/ast"
)

// Options configures Generate.
type Options struct {
	// PackageName is written verbatim into the generated `package` clause.
	PackageName string
	// ServerFilePath optionally points at a sibling +page.server.go whose
	// Load() inline struct return is used to infer PageData fields.
	ServerFilePath string
	// HasActions is true when the sibling page.server.go declares
	// `var Actions kit.ActionMap`. The page's PageData gains a `Form any`
	// field so action result data can be threaded through the render.
	HasActions bool
}

// LayoutOptions configures GenerateLayout.
type LayoutOptions struct {
	// PackageName is written verbatim into the generated `package` clause.
	PackageName string
	// ServerFilePath optionally points at a sibling layout.server.go whose
	// Load() inline struct return is used to infer LayoutData fields.
	ServerFilePath string
}

// Generate lowers frag to Go source for a Page.Render method. The returned
// bytes pass through go/format so the caller receives canonically
// formatted Go.
func Generate(frag *ast.Fragment, opts Options) ([]byte, error) {
	if frag == nil {
		return nil, errors.New("codegen: nil fragment")
	}
	if opts.PackageName == "" {
		return nil, errors.New("codegen: empty package name")
	}

	scripts, err := extractScripts(frag)
	if err != nil {
		return nil, err
	}
	pageData, err := inferPageData(opts.ServerFilePath)
	if err != nil {
		return nil, err
	}
	if opts.HasActions {
		pageData.Fields = append(pageData.Fields, pageDataField{Name: "Form", Type: "any"})
	}

	imports := mergeImports(scripts.Imports, pageData.Imports)

	var b Builder
	b.Line("// Code generated by sveltego. DO NOT EDIT.")
	b.Linef("package %s", opts.PackageName)
	b.Line("")
	b.Line("import (")
	b.Indent()
	for _, imp := range imports {
		b.Line(imp)
	}
	b.Dedent()
	b.Line(")")
	b.Line("")

	for _, decl := range scripts.Decls {
		b.Line(decl)
		b.Line("")
	}

	b.Line("type Page struct{}")
	b.Line("")
	emitPageDataStruct(&b, pageData.Fields)
	b.Line("")
	b.Line("func (p Page) Render(w *render.Writer, ctx *kit.RenderCtx, data PageData) error {")
	b.Indent()
	b.Line("_ = ctx")
	b.Line("_ = data")
	emitChildren(&b, frag.Children)
	b.Line("return nil")
	b.Dedent()
	b.Line("}")

	if err := b.Err(); err != nil {
		return nil, err
	}

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: format generated source: %w", err)
	}
	return restoreRunesBytes(out), nil
}

// GenerateLayout lowers frag to Go source for a Layout.Render method.
// The signature mirrors Generate but accepts a `children` callback that
// any <slot /> element in the template lowers to. LayoutData is emitted
// as an empty type alias today; Phase 0k-B introduces real data via
// +layout.server.go.
func GenerateLayout(frag *ast.Fragment, opts LayoutOptions) ([]byte, error) {
	if frag == nil {
		return nil, errors.New("codegen: nil fragment")
	}
	if opts.PackageName == "" {
		return nil, errors.New("codegen: empty package name")
	}

	scripts, err := extractScripts(frag)
	if err != nil {
		return nil, err
	}
	layoutData, err := inferPageData(opts.ServerFilePath)
	if err != nil {
		return nil, err
	}

	imports := mergeImports(scripts.Imports, layoutData.Imports)

	var b Builder
	b.hasChildren = true
	b.Line("// Code generated by sveltego. DO NOT EDIT.")
	b.Linef("package %s", opts.PackageName)
	b.Line("")
	b.Line("import (")
	b.Indent()
	for _, imp := range imports {
		b.Line(imp)
	}
	b.Dedent()
	b.Line(")")
	b.Line("")

	for _, decl := range scripts.Decls {
		b.Line(decl)
		b.Line("")
	}

	b.Line("type Layout struct{}")
	b.Line("")
	emitLayoutDataAlias(&b, layoutData.Fields)
	b.Line("")
	b.Line("func (l Layout) Render(w *render.Writer, ctx *kit.RenderCtx, data LayoutData, children func(*render.Writer) error) error {")
	b.Indent()
	b.Line("_ = ctx")
	b.Line("_ = data")
	b.Line("_ = children")
	emitChildren(&b, frag.Children)
	b.Line("return nil")
	b.Dedent()
	b.Line("}")

	if err := b.Err(); err != nil {
		return nil, err
	}

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: format generated source: %w", err)
	}
	return restoreRunesBytes(out), nil
}

// emitLayoutDataAlias writes `type LayoutData = struct{...}` mirroring
// the alias-form rationale on emitPageDataStruct: type identity between
// the user's inline struct literal and the LayoutData symbol asserted
// by the manifest adapter must be preserved.
func emitLayoutDataAlias(b *Builder, fields []pageDataField) {
	if len(fields) == 0 {
		b.Line("type LayoutData = struct{}")
		return
	}
	b.Line("type LayoutData = struct {")
	b.Indent()
	for _, fd := range fields {
		b.Linef("%s %s", fd.Name, fd.Type)
	}
	b.Dedent()
	b.Line("}")
}

// mergeImports unions framework imports with script + pagedata imports,
// dedupes by full import path, and returns a stable-sorted slice ready to
// emit between `import (` and `)`.
func mergeImports(scriptImports, pageDataImports []string) []string {
	set := map[string]struct{}{
		`"github.com/binsarjr/sveltego/exports/kit"`: {},
		`"github.com/binsarjr/sveltego/render"`:      {},
	}
	for _, imp := range scriptImports {
		set[imp] = struct{}{}
	}
	for _, imp := range pageDataImports {
		set[imp] = struct{}{}
	}
	out := make([]string, 0, len(set))
	for k := range set {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// emitChildren walks a sibling list and dispatches by node kind. Adjacent
// Text nodes are merged before iteration so the emitted code has one
// WriteString per run.
func emitChildren(b *Builder, children []ast.Node) {
	merged := mergeAdjacentText(children)
	for _, child := range merged {
		emitNode(b, child)
	}
}

func emitNode(b *Builder, n ast.Node) {
	switch v := n.(type) {
	case *ast.Text:
		emitText(b, v)
	case *ast.Element:
		emitElement(b, v)
	case *ast.Mustache:
		emitMustache(b, v)
	case *ast.IfBlock:
		emitIfBlock(b, v)
	case *ast.EachBlock:
		emitEachBlock(b, v)
	case *ast.AwaitBlock:
		b.Line("// TODO: await block (#48)")
	case *ast.KeyBlock:
		b.Line("// TODO: key block (#48)")
	case *ast.SnippetBlock:
		b.Linef("// TODO: snippet block %q (#14)", v.Name)
	case *ast.RawHTML:
		emitRawHTML(b, v)
	case *ast.Const:
		emitConst(b, v)
	case *ast.Render:
		emitRender(b, v)
	case *ast.Script:
		// extracted to package scope by extractScripts
	case *ast.Style:
		// TODO: <style> extraction (#16)
	case *ast.Comment:
	}
}
