package codegen

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// emitComponentTree integration tests
// ---------------------------------------------------------------------------

// TestEmitComponentTree_SimpleChild verifies that a +page.svelte importing
// one sibling component emits a component.gen.go for that component.
func TestEmitComponentTree_SimpleChild(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "go.mod"), "module example.com/app\n\ngo 1.22\n")

	writeFile(t, filepath.Join(root, "src", "routes", "button.svelte"),
		`<span>{props.Label}</span>`+"\n")
	writeFile(t, filepath.Join(root, "src", "routes", "+page.svelte"),
		`<script lang="go">
import button "./button"
</script>
<button.Button label="OK" />
`)
	if _, err := Build(BuildOptions{ProjectRoot: root}); err != nil {
		t.Fatalf("Build: %v", err)
	}

	genFile := filepath.Join(root, ".gen", "components", "routes", "button", "component.gen.go")
	if _, err := os.Stat(genFile); err != nil {
		t.Errorf("expected %s to exist: %v", genFile, err)
	}
	data, err := os.ReadFile(genFile)
	if err != nil {
		t.Fatalf("read component gen: %v", err)
	}
	for _, want := range []string{
		"// Code generated by sveltego. DO NOT EDIT.",
		"package button",
		"type Button struct{}",
		"type ButtonProps = struct{}",
		"type ButtonSlots struct",
	} {
		if !bytes.Contains(data, []byte(want)) {
			t.Errorf("component.gen.go missing %q:\n%s", want, data)
		}
	}
	assertParsesAsGo(t, genFile)
}

// TestEmitComponentTree_NestedChild verifies that a component importing a
// grandchild results in both being emitted.
func TestEmitComponentTree_NestedChild(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "go.mod"), "module example.com/app\n\ngo 1.22\n")

	// grandchild: icon.svelte
	writeFile(t, filepath.Join(root, "src", "routes", "icon.svelte"),
		`<svg></svg>`+"\n")
	// child: button.svelte imports icon
	writeFile(t, filepath.Join(root, "src", "routes", "button.svelte"),
		`<script lang="go">
import icon "./icon"
</script>
<icon.Icon /><span>{props.Label}</span>
`)
	// page imports button
	writeFile(t, filepath.Join(root, "src", "routes", "+page.svelte"),
		`<script lang="go">
import button "./button"
</script>
<button.Button label="OK" />
`)

	if _, err := Build(BuildOptions{ProjectRoot: root}); err != nil {
		t.Fatalf("Build: %v", err)
	}

	for _, rel := range []string{
		filepath.Join(".gen", "components", "routes", "button", "component.gen.go"),
		filepath.Join(".gen", "components", "routes", "icon", "component.gen.go"),
	} {
		genFile := filepath.Join(root, rel)
		if _, err := os.Stat(genFile); err != nil {
			t.Errorf("expected %s to exist: %v", genFile, err)
		}
		assertParsesAsGo(t, genFile)
	}
}

// TestEmitComponentTree_SharedChild verifies that two routes importing the
// same component result in the component being emitted exactly once.
func TestEmitComponentTree_SharedChild(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "go.mod"), "module example.com/app\n\ngo 1.22\n")

	writeFile(t, filepath.Join(root, "src", "routes", "badge.svelte"),
		`<span>badge</span>`+"\n")
	writeFile(t, filepath.Join(root, "src", "routes", "+page.svelte"),
		`<script lang="go">
import badge "./badge"
</script>
<badge.Badge />
`)
	writeFile(t, filepath.Join(root, "src", "routes", "about", "+page.svelte"),
		`<script lang="go">
import badge "../badge"
</script>
<badge.Badge />
`)

	if _, err := Build(BuildOptions{ProjectRoot: root}); err != nil {
		t.Fatalf("Build: %v", err)
	}

	genFile := filepath.Join(root, ".gen", "components", "routes", "badge", "component.gen.go")
	if _, err := os.Stat(genFile); err != nil {
		t.Errorf("expected badge component.gen.go to exist: %v", err)
	}
	assertParsesAsGo(t, genFile)
}

// TestEmitComponentTree_Cycle verifies that a component cycle (A→B→A) causes
// Build to return a descriptive error.
func TestEmitComponentTree_Cycle(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "go.mod"), "module example.com/app\n\ngo 1.22\n")

	// a.svelte imports b.svelte, b.svelte imports a.svelte
	writeFile(t, filepath.Join(root, "src", "routes", "a.svelte"),
		`<script lang="go">
import b "./b"
</script>
<b.B />
`)
	writeFile(t, filepath.Join(root, "src", "routes", "b.svelte"),
		`<script lang="go">
import a "./a"
</script>
<a.A />
`)
	writeFile(t, filepath.Join(root, "src", "routes", "+page.svelte"),
		`<script lang="go">
import a "./a"
</script>
<a.A />
`)

	_, err := Build(BuildOptions{ProjectRoot: root})
	if err == nil {
		t.Fatal("expected error for component cycle, got nil")
	}
	if !strings.Contains(err.Error(), "cycle") {
		t.Errorf("expected 'cycle' in error, got: %v", err)
	}
}

// TestEmitComponentTree_CasingCollision verifies that two .svelte files
// differing only in case (Card.svelte vs card.svelte) in the same directory
// cause Build to return a casing collision error.
func TestEmitComponentTree_CasingCollision(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "go.mod"), "module example.com/app\n\ngo 1.22\n")

	// On case-insensitive filesystems, creating both files may overwrite one.
	// We simulate the collision by adding them both to the adjacency map via
	// a page that imports both via distinct relative paths.
	// Note: this test is meaningful on case-sensitive filesystems (Linux/CI).
	// On macOS the filesystem may merge them; we guard by checking the error
	// only when both stat as different inodes.
	cardUpper := filepath.Join(root, "src", "routes", "Card.svelte")
	cardLower := filepath.Join(root, "src", "routes", "card.svelte")

	writeFile(t, cardUpper, `<div>Card</div>`+"\n")
	// Try to write the second file; if they resolve to the same path (case-
	// insensitive FS), the test is moot.
	writeFile(t, cardLower, `<div>card</div>`+"\n")

	infoUpper, errU := os.Stat(cardUpper)
	infoLower, errL := os.Stat(cardLower)
	if errU != nil || errL != nil {
		t.Skip("cannot stat both casing variants")
	}
	if os.SameFile(infoUpper, infoLower) {
		t.Skip("case-insensitive filesystem: Card.svelte and card.svelte are the same file")
	}

	writeFile(t, filepath.Join(root, "src", "routes", "+page.svelte"),
		`<script lang="go">
import card1 "./Card"
import card2 "./card"
</script>
<card1.Card />
<card2.Card />
`)

	_, err := Build(BuildOptions{ProjectRoot: root})
	if err == nil {
		t.Fatal("expected casing collision error, got nil")
	}
	if !strings.Contains(err.Error(), "casing collision") && !strings.Contains(err.Error(), "collision") {
		t.Errorf("expected 'casing collision' in error, got: %v", err)
	}
}

// TestEmitComponentTree_RelativeImportResolution verifies that a +page.svelte
// at a nested route depth resolves `"./button"` to the correct sibling.
func TestEmitComponentTree_RelativeImportResolution(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "go.mod"), "module example.com/app\n\ngo 1.22\n")

	writeFile(t, filepath.Join(root, "src", "routes", "dashboard", "widgets", "button.svelte"),
		`<button>{props.Label}</button>`+"\n")
	writeFile(t, filepath.Join(root, "src", "routes", "dashboard", "widgets", "+page.svelte"),
		`<script lang="go">
import button "./button"
</script>
<button.Button label="OK" />
`)

	if _, err := Build(BuildOptions{ProjectRoot: root}); err != nil {
		t.Fatalf("Build: %v", err)
	}

	genFile := filepath.Join(root, ".gen", "components", "routes", "dashboard", "widgets", "button", "component.gen.go")
	if _, err := os.Stat(genFile); err != nil {
		t.Errorf("expected %s to exist: %v", genFile, err)
	}
	assertParsesAsGo(t, genFile)
}

// TestEmitComponentTree_NoComponents verifies that Build succeeds normally
// when no .svelte pages contain component imports.
func TestEmitComponentTree_NoComponents(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	scaffoldProject(t, root, "example.com/app")

	if _, err := Build(BuildOptions{ProjectRoot: root}); err != nil {
		t.Fatalf("Build: %v", err)
	}
	// No components directory should be created.
	compDir := filepath.Join(root, ".gen", "components")
	if _, err := os.Stat(compDir); err == nil {
		t.Errorf(".gen/components/ created when no components were referenced")
	}
}

// ---------------------------------------------------------------------------
// Unit tests for helper functions
// ---------------------------------------------------------------------------

func TestEncodeComponentPath(t *testing.T) {
	t.Parallel()
	cases := []struct {
		projectRoot string
		absPath     string
		want        string
	}{
		{
			projectRoot: "/app",
			absPath:     "/app/src/routes/button.svelte",
			want:        "routes/button",
		},
		{
			projectRoot: "/app",
			absPath:     "/app/src/routes/foo/bar/MyCard.svelte",
			want:        "routes/foo/bar/mycard",
		},
		{
			projectRoot: "/app",
			absPath:     "/app/src/routes/[id]/Widget.svelte",
			want:        "routes/_id_/widget",
		},
		{
			projectRoot: "/app",
			absPath:     "/app/src/lib/ui/Button.svelte",
			want:        "lib/ui/button",
		},
	}
	for _, tc := range cases {
		got := encodeComponentPath(tc.projectRoot, tc.absPath)
		if got != tc.want {
			t.Errorf("encodeComponentPath(%q, %q) = %q, want %q", tc.projectRoot, tc.absPath, got, tc.want)
		}
	}
}

func TestEncodeSegment(t *testing.T) {
	t.Parallel()
	cases := []struct {
		in   string
		want string
	}{
		{"button", "button"},
		{"Button", "button"},
		{"[id]", "_id_"},
		{"(group)", "_group_"},
		{"MyCard", "mycard"},
	}
	for _, tc := range cases {
		got := encodeSegment(tc.in)
		if got != tc.want {
			t.Errorf("encodeSegment(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestComponentNameFromPath(t *testing.T) {
	t.Parallel()
	cases := []struct {
		path string
		want string
	}{
		{"/app/src/routes/button.svelte", "Button"},
		{"/app/src/routes/my-card.svelte", "MyCard"},
		{"/app/src/routes/data_table.svelte", "DataTable"},
		{"/app/src/routes/Widget.svelte", "Widget"},
	}
	for _, tc := range cases {
		got := componentNameFromPath(tc.path)
		if got != tc.want {
			t.Errorf("componentNameFromPath(%q) = %q, want %q", tc.path, got, tc.want)
		}
	}
}

func TestIsRelativePath(t *testing.T) {
	t.Parallel()
	cases := []struct {
		path string
		want bool
	}{
		{"./button", true},
		{"../lib/card", true},
		{"example.com/pkg", false},
		{"$lib/ui", false},
		{"", false},
	}
	for _, tc := range cases {
		got := isRelativePath(tc.path)
		if got != tc.want {
			t.Errorf("isRelativePath(%q) = %v, want %v", tc.path, got, tc.want)
		}
	}
}

func TestSvelteImportsFromSource_NoScript(t *testing.T) {
	t.Parallel()
	src := []byte("<h1>Hello</h1>\n")
	imps, err := svelteImportsFromSource("/tmp/page.svelte", src)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(imps) != 0 {
		t.Errorf("expected no imports, got %v", imps)
	}
}

func TestSvelteImportsFromSource_NonRelativeIgnored(t *testing.T) {
	t.Parallel()
	src := []byte(`<script lang="go">
import "fmt"
import db "example.com/app/lib/db"
</script>
<h1>Hi</h1>
`)
	imps, err := svelteImportsFromSource("/tmp/page.svelte", src)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(imps) != 0 {
		t.Errorf("expected no component imports for non-relative paths, got %v", imps)
	}
}
