package codegen

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

// emitHooks writes two files when the user authored src/hooks.server.go:
//   - <outDir>/hookssrc/hooks_server.go: build-tag-stripped, package-rewritten
//     mirror of the user file, importable by the gen tree.
//   - <outDir>/hooks.gen.go: a hooks adapter exposing `Hooks() kit.Hooks`
//     in the gen package; missing hook fields fall through to the kit
//     identity defaults.
//
// When no user file exists, only the hooks.gen.go stub is emitted so
// downstream consumers (server config, generated main) can call
// gen.Hooks() unconditionally.
func emitHooks(projectRoot, outDir, modulePath, genPackage string, set HookSet) error {
	if genPackage == "" {
		genPackage = "gen"
	}
	outAbs := filepath.Join(projectRoot, outDir)

	if set.Present() && set.Any() {
		mirrorPath := filepath.Join(outAbs, "hookssrc", "hooks_server.go")
		if err := mirrorUserSource(&userSourceFile{
			UserPath:    set.SourcePath,
			MirrorPath:  mirrorPath,
			PackageName: "hookssrc",
		}); err != nil {
			return err
		}
	}

	body, err := generateHooksAdapter(genPackage, modulePath, outDir, set)
	if err != nil {
		return err
	}
	target := filepath.Join(outAbs, "hooks.gen.go")
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("codegen: mkdir %s: %w", filepath.Dir(target), err)
	}
	if err := os.WriteFile(target, body, genFileMode); err != nil {
		return fmt.Errorf("codegen: write %s: %w", target, err)
	}
	return nil
}

// generateHooksAdapter emits the gen package's hooks.gen.go body. The
// file declares `func Hooks() kit.Hooks` returning a value populated
// with the user's hook references when set.Present(); missing entries
// default to kit identity helpers via Hooks.WithDefaults.
func generateHooksAdapter(genPackage, modulePath, outDir string, set HookSet) ([]byte, error) {
	useUsersrc := set.Present() && set.Any()

	var b Builder
	b.Line("// Code generated by sveltego. DO NOT EDIT.")
	b.Linef("package %s", genPackage)
	b.Line("")
	b.Line("import (")
	b.Indent()
	b.Line(`"github.com/binsarjr/sveltego/exports/kit"`)
	if useUsersrc {
		b.Line("")
		b.Linef(`hookssrc %q`, modulePath+"/"+outDir+"/hookssrc")
	}
	b.Dedent()
	b.Line(")")
	b.Line("")

	b.Line("// Hooks returns the user-authored hook bundle, with identity")
	b.Line("// defaults filled in for every hook the user did not declare.")
	b.Line("func Hooks() kit.Hooks {")
	b.Indent()
	if !useUsersrc {
		b.Line("return kit.DefaultHooks()")
		b.Dedent()
		b.Line("}")
		if err := b.Err(); err != nil {
			return nil, err
		}
		out, err := format.Source(b.Bytes())
		if err != nil {
			return nil, fmt.Errorf("codegen: format hooks adapter: %w", err)
		}
		return out, nil
	}

	b.Line("h := kit.Hooks{")
	b.Indent()
	if set.Handle {
		b.Line("Handle: hookssrc.Handle,")
	}
	if set.HandleError {
		b.Line("HandleError: hookssrc.HandleError,")
	}
	if set.HandleFetch {
		b.Line("HandleFetch: hookssrc.HandleFetch,")
	}
	if set.Reroute {
		b.Line("Reroute: hookssrc.Reroute,")
	}
	if set.Init {
		b.Line("Init: hookssrc.Init,")
	}
	b.Dedent()
	b.Line("}")
	b.Line("return h.WithDefaults()")
	b.Dedent()
	b.Line("}")

	if err := b.Err(); err != nil {
		return nil, err
	}
	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: format hooks adapter: %w", err)
	}
	return out, nil
}
