package codegen

import (
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/binsarjr/sveltego/internal/routescan"
	"github.com/binsarjr/sveltego/runtime/router"
)

// LinkEmitOptions configures [GenerateLinks].
type LinkEmitOptions struct {
	// PackageName is the package clause for the generated file. Defaults
	// to "links" when empty.
	PackageName string
}

// LinkRoute summarizes one entry in the generated links package: the
// canonical SvelteKit-style pattern, the Go-ident helper name, and the
// HTTP method label printed by `sveltego routes` ("GET" for pages and
// servers; "POST", etc. when a +server.go advertises specific methods).
type LinkRoute struct {
	Pattern string
	Helper  string
	Method  string
	Params  []LinkParam
}

// LinkParam describes one parameter slot in a LinkRoute. Kind mirrors
// router.SegmentKind for non-static segments; Field is the PascalCase
// struct field name on the emitted *Params type.
type LinkParam struct {
	Field string
	Name  string
	Kind  router.SegmentKind
}

// GenerateLinks emits a deterministic, gofmt-clean Go source file
// declaring one *Params struct + URL-builder func per linkable route in
// the scan result. Routes without a +page.svelte or +server.go are
// skipped; the manifest emitter applies the same filter.
func GenerateLinks(scan *routescan.ScanResult, opts LinkEmitOptions) ([]byte, error) {
	if scan == nil {
		return nil, errors.New("codegen: nil scan result")
	}
	pkg := opts.PackageName
	if pkg == "" {
		pkg = "links"
	}

	routes := CollectLinkRoutes(scan)

	var b Builder
	b.Line("// Code generated by sveltego. DO NOT EDIT.")
	b.Linef("package %s", pkg)
	b.Line("")

	hasParams := false
	for _, r := range routes {
		if len(r.Params) > 0 {
			hasParams = true
			break
		}
	}
	if hasParams {
		b.Line(`import "strings"`)
		b.Line("")
	}

	if len(routes) == 0 {
		// Keep the package compilable when no routes register.
		b.Line("// No linkable routes discovered.")
	}

	for _, r := range routes {
		emitLinkHelper(&b, r)
	}

	if err := b.Err(); err != nil {
		return nil, err
	}
	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: format links source: %w", err)
	}
	return out, nil
}

// CollectLinkRoutes walks scan.Routes in scanner order and returns one
// LinkRoute per linkable route (HasPage or HasServer). Helper names are
// disambiguated when two routes lower to the same identifier.
func CollectLinkRoutes(scan *routescan.ScanResult) []LinkRoute {
	if scan == nil {
		return nil
	}
	var routes []LinkRoute
	used := make(map[string]int)
	for _, r := range scan.Routes {
		if !r.HasPage && !r.HasServer {
			continue
		}
		base := routeIdent(r.Segments)
		helper := base
		if n, ok := used[base]; ok {
			n++
			used[base] = n
			helper = fmt.Sprintf("%s_%d", base, n)
		} else {
			used[base] = 1
		}
		routes = append(routes, LinkRoute{
			Pattern: r.Pattern,
			Helper:  helper,
			Method:  linkMethod(r),
			Params:  collectParams(r.Segments),
		})
	}
	return routes
}

func linkMethod(r routescan.ScannedRoute) string {
	if r.HasPage {
		return "GET"
	}
	if r.HasServer {
		return "ANY"
	}
	return ""
}

func collectParams(segs []router.Segment) []LinkParam {
	var out []LinkParam
	used := make(map[string]int)
	for _, s := range segs {
		switch s.Kind {
		case router.SegmentParam, router.SegmentOptional, router.SegmentRest:
			field := pascal(s.Name)
			if n, ok := used[field]; ok {
				n++
				used[field] = n
				field = fmt.Sprintf("%s%d", field, n)
			} else {
				used[field] = 1
			}
			out = append(out, LinkParam{Field: field, Name: s.Name, Kind: s.Kind})
		}
	}
	return out
}

// routeIdent lowers a slice of segments into a PascalCase Go identifier.
// Static segments contribute their literal value; dynamic segments
// contribute the parameter name. The empty slice (root route) maps to
// "Index".
func routeIdent(segs []router.Segment) string {
	if len(segs) == 0 {
		return "Index"
	}
	var b strings.Builder
	for _, s := range segs {
		switch s.Kind {
		case router.SegmentStatic:
			b.WriteString(pascal(s.Value))
		case router.SegmentParam, router.SegmentOptional, router.SegmentRest:
			b.WriteString(pascal(s.Name))
		}
	}
	if b.Len() == 0 {
		return "Index"
	}
	return b.String()
}

// pascal lowers an arbitrary identifier-like string to PascalCase. Runs
// of non-letter/non-digit characters split words; each word is
// title-cased. Leading digits are prefixed with "_" so the output stays
// a valid Go identifier.
func pascal(s string) string {
	if s == "" {
		return ""
	}
	var b strings.Builder
	upper := true
	for _, r := range s {
		switch {
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r)
			upper = false
		case r >= 'a' && r <= 'z':
			if upper {
				b.WriteRune(r - ('a' - 'A'))
			} else {
				b.WriteRune(r)
			}
			upper = false
		case r >= '0' && r <= '9':
			if b.Len() == 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r)
			upper = true
		default:
			upper = true
		}
	}
	return b.String()
}

func emitLinkHelper(b *Builder, r LinkRoute) {
	b.Linef("// %sParams binds the typed parameters for %s.", r.Helper, r.Pattern)
	b.Linef("type %sParams struct {", r.Helper)
	b.Indent()
	for _, p := range r.Params {
		b.Linef("%s string", p.Field)
	}
	b.Dedent()
	b.Line("}")
	b.Line("")

	b.Linef("// %s builds the URL for %s.", r.Helper, r.Pattern)
	if len(r.Params) == 0 {
		b.Linef("func %s(_ %sParams) string {", r.Helper, r.Helper)
		b.Indent()
		b.Linef("return %s", quoteGo(r.Pattern))
		b.Dedent()
		b.Line("}")
		b.Line("")
		return
	}

	b.Linef("func %s(p %sParams) string {", r.Helper, r.Helper)
	b.Indent()
	b.Line("var b strings.Builder")
	emitLinkBuild(b, r)
	b.Line("return b.String()")
	b.Dedent()
	b.Line("}")
	b.Line("")
}

func emitLinkBuild(b *Builder, r LinkRoute) {
	// We re-walk the pattern's segments so the codegen output mirrors
	// path layout exactly. Splitting on '/' keeps us stdlib-only.
	parts := splitPattern(r.Pattern)
	pi := 0
	for _, part := range parts {
		switch {
		case isStaticPart(part):
			b.Linef("b.WriteString(%s)", quoteGo("/"+part))
		case strings.HasPrefix(part, "[[") && strings.HasSuffix(part, "]]"):
			p := r.Params[pi]
			pi++
			b.Linef("if p.%s != \"\" {", p.Field)
			b.Indent()
			b.Linef("b.WriteByte('/')")
			b.Linef("b.WriteString(p.%s)", p.Field)
			b.Dedent()
			b.Line("}")
		case strings.HasPrefix(part, "[...") && strings.HasSuffix(part, "]"):
			p := r.Params[pi]
			pi++
			b.Linef("if p.%s != \"\" {", p.Field)
			b.Indent()
			b.Linef("b.WriteByte('/')")
			b.Linef("b.WriteString(strings.TrimPrefix(p.%s, %q))", p.Field, "/")
			b.Dedent()
			b.Line("}")
		case strings.HasPrefix(part, "[") && strings.HasSuffix(part, "]"):
			p := r.Params[pi]
			pi++
			b.Linef("b.WriteByte('/')")
			b.Linef("b.WriteString(p.%s)", p.Field)
		}
	}
	if len(parts) == 0 {
		b.Linef("b.WriteByte('/')")
	}
}

func splitPattern(pattern string) []string {
	trimmed := strings.TrimPrefix(pattern, "/")
	if trimmed == "" {
		return nil
	}
	return strings.Split(trimmed, "/")
}

func isStaticPart(part string) bool {
	return !strings.ContainsAny(part, "[]")
}

// SortLinkRoutes returns routes sorted by pattern. Useful for the CLI
// listing where deterministic output is mandatory.
func SortLinkRoutes(in []LinkRoute) []LinkRoute {
	out := make([]LinkRoute, len(in))
	copy(out, in)
	sort.SliceStable(out, func(i, j int) bool {
		return out[i].Pattern < out[j].Pattern
	})
	return out
}

// EmitLinksFile scans projectRoot/src/routes and writes a single
// links.go file under projectRoot/<outDir>/links containing the typed
// helpers for every linkable route. Callers must invoke this after
// [Build] so the gen directory already exists.
func EmitLinksFile(projectRoot, outDir string) error {
	if !filepath.IsAbs(projectRoot) {
		return fmt.Errorf("codegen: ProjectRoot must be absolute (got %q)", projectRoot)
	}
	if outDir == "" {
		outDir = ".gen"
	}
	routesDir := filepath.Join(projectRoot, "src", "routes")
	if info, err := os.Stat(routesDir); err != nil {
		return fmt.Errorf("codegen: src/routes/ not found at %s: %w", routesDir, err)
	} else if !info.IsDir() {
		return fmt.Errorf("codegen: %s is not a directory", routesDir)
	}
	paramsDir := filepath.Join(projectRoot, "src", "params")
	if _, err := os.Stat(paramsDir); err != nil {
		paramsDir = ""
	}
	scan, err := routescan.Scan(routescan.ScanInput{RoutesDir: routesDir, ParamsDir: paramsDir})
	if err != nil {
		return fmt.Errorf("codegen: scan routes: %w", err)
	}
	src, err := GenerateLinks(scan, LinkEmitOptions{})
	if err != nil {
		return fmt.Errorf("codegen: generate links: %w", err)
	}
	target := filepath.Join(projectRoot, outDir, "links", "links.go")
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("codegen: mkdir %s: %w", filepath.Dir(target), err)
	}
	if err := os.WriteFile(target, src, genFileMode); err != nil {
		return fmt.Errorf("codegen: write %s: %w", target, err)
	}
	return nil
}
