package codegen

import (
	"errors"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/binsarjr/sveltego/internal/routescan"
	"github.com/binsarjr/sveltego/runtime/router"
)

// ManifestOptions configures [GenerateManifest].
type ManifestOptions struct {
	// PackageName is the package clause for the generated file. Defaults to
	// "gen" when empty.
	PackageName string
	// ModulePath is the user app's module path; per-route imports are
	// composed as ModulePath + "/" + GenRoot + "/" + per-route subpath.
	ModulePath string
	// GenRoot is the gen-output root relative to the user module root, e.g.
	// ".gen". Trailing slashes are stripped.
	GenRoot string
}

// GenerateManifest emits a deterministic, gofmt-clean Go source file
// declaring `func Routes() []router.Route` from a [routescan.ScanResult].
//
// Routes with neither a +page.svelte nor a +server.go are skipped (e.g.
// orphan +page.server.go directories — the scanner already emits a
// diagnostic for these). Page routes emit Page: <pkg>.Page{}.Render and
// optionally Load / Actions when a +page.server.go is present alongside.
// API-only routes emit Server: <pkg>.Handlers; the generated package's
// +server.go is expected to declare `var Handlers map[string]http.HandlerFunc`.
//
// Symbol existence is not verified — Load / Actions / Handlers are emitted
// unconditionally on file presence and `go build` surfaces the missing
// declaration. The trade-off keeps the emitter free of a Go AST pass over
// user code at codegen time.
func GenerateManifest(scan *routescan.ScanResult, opts ManifestOptions) ([]byte, error) {
	if scan == nil {
		return nil, errors.New("codegen: nil scan result")
	}
	if opts.ModulePath == "" {
		return nil, errors.New("codegen: empty module path")
	}
	pkg := opts.PackageName
	if pkg == "" {
		pkg = "gen"
	}
	genRoot := strings.TrimRight(strings.TrimSpace(opts.GenRoot), "/")
	if genRoot == "" {
		genRoot = ".gen"
	}

	// Filter routes the manifest can register, preserving scanner order.
	type entry struct {
		route routescan.ScannedRoute
		alias string
	}
	var entries []entry
	aliasSet := make(map[string]struct{})
	for _, r := range scan.Routes {
		if !r.HasPage && !r.HasServer {
			continue
		}
		alias := packageAlias(r.PackagePath)
		// On the rare case two routes resolve to the same alias (impossible
		// today given path uniqueness, but cheap to defend), append a digit.
		base := alias
		for i := 2; ; i++ {
			if _, dup := aliasSet[alias]; !dup {
				break
			}
			alias = fmt.Sprintf("%s_%d", base, i)
		}
		aliasSet[alias] = struct{}{}
		entries = append(entries, entry{route: r, alias: alias})
	}

	var b Builder
	b.Line("// Code generated by sveltego. DO NOT EDIT.")
	b.Linef("package %s", pkg)
	b.Line("")

	// Surface scanner diagnostics in the generated source so users see them
	// when they open .gen/manifest.gen.go.
	for _, d := range scan.Diagnostics {
		b.Linef("// SCANNER DIAGNOSTIC: %s", d.String())
	}
	if len(scan.Diagnostics) > 0 {
		b.Line("")
	}

	b.Line("import (")
	b.Indent()
	b.Line(`"github.com/binsarjr/sveltego/runtime/router"`)
	if len(entries) > 0 {
		b.Line("")
		// Sort imports alphabetically by alias for deterministic output.
		ordered := make([]entry, len(entries))
		copy(ordered, entries)
		sort.Slice(ordered, func(i, j int) bool { return ordered[i].alias < ordered[j].alias })
		for _, e := range ordered {
			importPath := opts.ModulePath + "/" + genRoot + "/" + strings.TrimPrefix(e.route.PackagePath, ".gen/")
			b.Linef("%s %q", e.alias, importPath)
		}
	}
	b.Dedent()
	b.Line(")")
	b.Line("")

	b.Line("// Routes returns the route table consumed by router.NewTree.")
	b.Line("func Routes() []router.Route {")
	b.Indent()
	if len(entries) == 0 {
		b.Line("return nil")
	} else {
		b.Line("return []router.Route{")
		b.Indent()
		for _, e := range entries {
			emitRouteEntry(&b, e.route, e.alias)
		}
		b.Dedent()
		b.Line("}")
	}
	b.Dedent()
	b.Line("}")

	if err := b.Err(); err != nil {
		return nil, err
	}

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: format manifest source: %w", err)
	}
	return out, nil
}

// packageAlias derives the per-route import alias from a ScannedRoute
// PackagePath. The leading ".gen/" prefix is stripped, the remainder is
// split on "/" and joined with "_", and the result is prefixed with
// "page_". Example: ".gen/routes/posts/_slug_" -> "page_routes_posts__slug_".
func packageAlias(packagePath string) string {
	rel := strings.TrimPrefix(packagePath, ".gen/")
	if rel == "" || rel == ".gen" {
		return "page_routes"
	}
	parts := strings.Split(rel, "/")
	return "page_" + strings.Join(parts, "_")
}

func emitRouteEntry(b *Builder, r routescan.ScannedRoute, alias string) {
	b.Line("{")
	b.Indent()
	b.Linef("Pattern: %s,", quoteGo(r.Pattern))
	emitSegments(b, r.Segments)
	switch {
	case r.HasServer:
		b.Linef("Server: %s.Handlers,", alias)
	case r.HasPage:
		b.Linef("Page: %s.Page{}.Render,", alias)
	}
	if r.HasPageServer {
		b.Linef("Load: %s.Load,", alias)
		b.Linef("Actions: %s.Actions,", alias)
	}
	b.Dedent()
	b.Line("},")
}

func emitSegments(b *Builder, segs []router.Segment) {
	if len(segs) == 0 {
		b.Line("Segments: []router.Segment{},")
		return
	}
	b.Line("Segments: []router.Segment{")
	b.Indent()
	for _, s := range segs {
		b.Line(formatSegment(s))
	}
	b.Dedent()
	b.Line("},")
}

func formatSegment(s router.Segment) string {
	var sb strings.Builder
	sb.WriteString("{Kind: ")
	sb.WriteString(segmentKindIdent(s.Kind))
	if s.Value != "" {
		sb.WriteString(", Value: ")
		sb.WriteString(quoteGo(s.Value))
	}
	if s.Name != "" {
		sb.WriteString(", Name: ")
		sb.WriteString(quoteGo(s.Name))
	}
	if s.Matcher != "" {
		sb.WriteString(", Matcher: ")
		sb.WriteString(quoteGo(s.Matcher))
	}
	sb.WriteString("},")
	return sb.String()
}

func segmentKindIdent(k router.SegmentKind) string {
	switch k {
	case router.SegmentStatic:
		return "router.SegmentStatic"
	case router.SegmentParam:
		return "router.SegmentParam"
	case router.SegmentOptional:
		return "router.SegmentOptional"
	case router.SegmentRest:
		return "router.SegmentRest"
	}
	return "router.SegmentStatic"
}
