package codegen

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"

	"github.com/binsarjr/sveltego/packages/sveltego/internal/routescan"
)

// matchersGenFile is the filename emitted under <outDir>/ that exposes
// `func Matchers() router.Matchers`. The bootstrap (init scaffold)
// imports the gen package and passes gen.Matchers() into server.Config
// so the runtime gets the user matcher map without manual wiring.
const matchersGenFile = "matchers.gen.go"

// emitMatchers writes two artifacts:
//
//   - One mirror file per discovered matcher under
//     <outDir>/paramssrc/<name>/<name>.go. The mirror is a build-tag-
//     stripped, package-rewritten copy of the user file so the gen tree
//     can import it without a `//go:build sveltego` constraint blocking
//     the standard Go toolchain.
//   - <outDir>/matchers.gen.go: a `func Matchers() router.Matchers`
//     that starts from params.DefaultMatchers() and overlays each user
//     matcher. User matchers whose name shadows a built-in are still
//     installed; the routescan diagnostic surfaces a build-time warning.
//
// The matchers file is emitted unconditionally so callers can reference
// `gen.Matchers()` even when src/params/ is empty — the call simply
// returns the built-in defaults in that case.
func emitMatchers(projectRoot, outDir, modulePath, genPackage string, matchers []routescan.DiscoveredMatcher) error {
	if genPackage == "" {
		genPackage = "gen"
	}
	outAbs := filepath.Join(projectRoot, outDir)

	// Mirror each user matcher into <outDir>/paramssrc/<name>/<name>.go.
	// The mirror keeps the user's package clause (already <name>) and
	// strips any leading `//go:build` constraint so the standard
	// toolchain compiles it. Mirrors are written before the registry
	// file so a parse error in a single matcher fails the build before
	// the registry references the missing symbol.
	for _, m := range matchers {
		mirrorPath := filepath.Join(outAbs, "paramssrc", m.Name, m.Name+".go")
		if err := mirrorUserSource(&userSourceFile{
			UserPath:    m.Path,
			MirrorPath:  mirrorPath,
			PackageName: m.PackageName,
		}); err != nil {
			return err
		}
	}

	body, err := generateMatchersAdapter(genPackage, modulePath, outDir, matchers)
	if err != nil {
		return err
	}
	target := filepath.Join(outAbs, matchersGenFile)
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("codegen: mkdir %s: %w", filepath.Dir(target), err)
	}
	if err := os.WriteFile(target, body, genFileMode); err != nil {
		return fmt.Errorf("codegen: write %s: %w", target, err)
	}
	return nil
}

// generateMatchersAdapter emits the gen package's matchers.gen.go body.
// The file declares `func Matchers() router.Matchers` returning a fresh
// map seeded with params.DefaultMatchers(); each user matcher overwrites
// the entry, with a one-line `log.Printf` warning at runtime when a
// built-in is shadowed (acceptance criterion: built-in matchers can be
// overridden by a user matcher of the same name with a warning).
func generateMatchersAdapter(genPackage, modulePath, outDir string, matchers []routescan.DiscoveredMatcher) ([]byte, error) {
	// Sort defensively even though discoverMatchers already returns
	// sorted output — the registry's import list and assignment order
	// must be deterministic across runs for golden-test stability.
	sorted := make([]routescan.DiscoveredMatcher, len(matchers))
	copy(sorted, matchers)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	hasShadow := false
	for _, mc := range sorted {
		if _, isBuiltin := builtinMatcherNames[mc.Name]; isBuiltin {
			hasShadow = true
			break
		}
	}

	var b Builder
	b.Line("// Code generated by sveltego. DO NOT EDIT.")
	b.Linef("package %s", genPackage)
	b.Line("")
	b.Line("import (")
	b.Indent()
	if hasShadow {
		b.Line(`"log"`)
		b.Line("")
	}
	b.Line(`"github.com/binsarjr/sveltego/packages/sveltego/exports/kit/params"`)
	b.Line(`"github.com/binsarjr/sveltego/packages/sveltego/runtime/router"`)
	if len(sorted) > 0 {
		b.Line("")
		for _, m := range sorted {
			b.Linef(`%s %q`, matcherImportAlias(m.Name), modulePath+"/"+outDir+"/paramssrc/"+m.Name)
		}
	}
	b.Dedent()
	b.Line(")")
	b.Line("")

	b.Line("// Matchers returns the param-matcher registry the runtime should")
	b.Line("// install on the route tree. The map starts from")
	b.Line("// params.DefaultMatchers() (int, uuid, slug); each user matcher")
	b.Line("// discovered under src/params/<name>/<name>.go is then installed,")
	b.Line("// overwriting any built-in entry of the same name. Shadowing a")
	b.Line("// built-in is allowed but emits a one-line log.Printf warning.")
	b.Line("func Matchers() router.Matchers {")
	b.Indent()
	b.Line("m := params.DefaultMatchers()")
	for _, mc := range sorted {
		// Built-in shadowing is named explicitly so the warning text
		// names the matcher; for non-shadowing matchers the assignment
		// is unconditional.
		if _, isBuiltin := builtinMatcherNames[mc.Name]; isBuiltin {
			b.Line(`log.Printf("sveltego: user matcher %q overrides built-in matcher of the same name", ` + fmt.Sprintf("%q", mc.Name) + `)`)
		}
		b.Linef(`m[%q] = router.MatcherFunc(%s.Match)`, mc.Name, matcherImportAlias(mc.Name))
	}
	b.Line("return m")
	b.Dedent()
	b.Line("}")

	if err := b.Err(); err != nil {
		return nil, err
	}
	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: format matchers adapter: %w", err)
	}
	return out, nil
}

// matcherImportAlias returns the local alias used in the matchers.gen.go
// import block. We always alias to `_<name>` so a matcher named after a
// predeclared identifier (e.g. `int`) does not shadow the type in the
// surrounding gen package, and a matcher whose name collides with the
// `params` or `router` import never trips the import block.
func matcherImportAlias(name string) string {
	return "matcher_" + name
}

// builtinMatcherNames mirrors routescan.builtinMatchers. Keeping a copy
// here avoids exposing the routescan-internal map; the codegen-side
// shadow check is read-only.
var builtinMatcherNames = map[string]struct{}{
	"int":  {},
	"uuid": {},
	"slug": {},
}
