// Provenance format — public contract (do not change casually; LLM tools
// and the future LSP (#69) will parse these comments).
//
// Header banner emitted at the top of every .gen/*.go file:
//
//	// Code generated by sveltego v<version> — DO NOT EDIT.
//	// Source: <relpath>
//	// Template-hash: sha256:<12-hex-chars>
//	// Generated: <RFC3339-UTC>
//
// Per-span comment emitted before each render call when Provenance is true:
//
//	// gen: source=<relpath>:<line> kind=<kind>
//
// <kind> is one of: text element mustache if each await key snippet
// render rawhtml const.
package codegen

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"time"
)

// provenanceVersion is the generator version embedded in header banners.
// It is overridden by build info when the binary is built with a module
// version tag; the fallback "dev" is used in test and local invocations.
var provenanceVersion = "dev"

// headerComment returns the banner that opens every .gen/*.go file.
// srcPath is the relative path to the .svelte source (forward slashes);
// content is the raw template bytes used to compute the hash (nil omits the
// hash line); version is the generator version string; ts is the generation
// timestamp.
func headerComment(srcPath string, content []byte, version string, ts time.Time) string {
	stamp := ts.UTC().Format(time.RFC3339)
	if len(content) == 0 {
		return fmt.Sprintf(
			"// Code generated by sveltego %s — DO NOT EDIT.\n// Source: %s\n// Generated: %s",
			version, srcPath, stamp,
		)
	}
	sum := sha256.Sum256(content)
	short := hex.EncodeToString(sum[:])[:12]
	return fmt.Sprintf(
		"// Code generated by sveltego %s — DO NOT EDIT.\n// Source: %s\n// Template-hash: sha256:%s\n// Generated: %s",
		version, srcPath, short, stamp,
	)
}

// spanComment returns the single-line provenance comment that precedes each
// emitted render span.  srcPath is the relative .svelte path; line is the
// 1-based source line of the span's opening node; kind is one of the
// documented kind tokens.
func spanComment(srcPath string, line int, kind string) string {
	if line <= 0 {
		return fmt.Sprintf("// gen: source=%s kind=%s", srcPath, kind)
	}
	return fmt.Sprintf("// gen: source=%s:%d kind=%s", srcPath, line, kind)
}
