package codegen

import (
	"strings"
	"testing"
	"time"

	"github.com/binsarjr/sveltego/packages/sveltego/internal/ast"
	"github.com/binsarjr/sveltego/packages/sveltego/internal/parser"
)

// fixedTS is a deterministic timestamp used in all provenance tests.
var fixedTS = time.Date(2026, 4, 30, 14, 33, 21, 0, time.UTC)

func TestHeaderComment_WithContent(t *testing.T) {
	content := []byte("<p>hello</p>")
	got := headerComment("src/routes/_page.svelte", content, "v1.0.0", fixedTS)

	want := []string{
		"// Code generated by sveltego v1.0.0 — DO NOT EDIT.",
		"// Source: src/routes/_page.svelte",
		"// Template-hash: sha256:",
	}
	for _, w := range want {
		if !strings.Contains(got, w) {
			t.Errorf("headerComment missing %q\ngot:\n%s", w, got)
		}
	}
}

func TestHeaderComment_WithoutContent(t *testing.T) {
	got := headerComment("src/routes/_page.svelte", nil, "dev", fixedTS)

	if strings.Contains(got, "Template-hash") {
		t.Errorf("headerComment should omit hash when content is nil\ngot:\n%s", got)
	}
	if !strings.Contains(got, "// Source: src/routes/_page.svelte") {
		t.Errorf("headerComment should include Source line\ngot:\n%s", got)
	}
	if strings.Contains(got, "Generated:") {
		t.Errorf("headerComment must not include Generated timestamp (breaks idempotency)\ngot:\n%s", got)
	}
}

func TestHeaderComment_Deterministic(t *testing.T) {
	content := []byte("<p>{Name}</p>")
	a := headerComment("src/routes/_page.svelte", content, "dev", fixedTS)
	b := headerComment("src/routes/_page.svelte", content, "dev", fixedTS)
	if a != b {
		t.Errorf("headerComment not deterministic:\na: %s\nb: %s", a, b)
	}
}

func TestHeaderComment_HashShortForm(t *testing.T) {
	content := []byte("abc")
	got := headerComment("x.svelte", content, "dev", fixedTS)
	// extract the hash from "// Template-hash: sha256:<12chars>"
	const prefix = "// Template-hash: sha256:"
	idx := strings.Index(got, prefix)
	if idx < 0 {
		t.Fatalf("no hash line in:\n%s", got)
	}
	hashLine := got[idx+len(prefix):]
	// hash is at start of the remainder, terminated by newline
	end := strings.IndexByte(hashLine, '\n')
	if end < 0 {
		end = len(hashLine)
	}
	hash := hashLine[:end]
	if len(hash) != 12 {
		t.Errorf("expected 12 hex chars, got %q (len=%d)", hash, len(hash))
	}
}

func TestSpanComment_WithLine(t *testing.T) {
	got := spanComment("src/routes/_page.svelte", 42, "mustache")
	want := "// gen: source=src/routes/_page.svelte:42 kind=mustache"
	if got != want {
		t.Errorf("spanComment:\n got: %q\nwant: %q", got, want)
	}
}

func TestSpanComment_ZeroLine(t *testing.T) {
	got := spanComment("src/routes/_page.svelte", 0, "text")
	want := "// gen: source=src/routes/_page.svelte kind=text"
	if got != want {
		t.Errorf("spanComment zero-line:\n got: %q\nwant: %q", got, want)
	}
}

// TestGenerate_ProvenanceHeader verifies the rich header is emitted when
// Filename is set and that the simple banner is used otherwise.
func TestGenerate_ProvenanceHeader(t *testing.T) {
	frag := &ast.Fragment{}
	src := []byte("<p>hi</p>")

	t.Run("rich header with filename", func(t *testing.T) {
		out, err := Generate(frag, Options{
			PackageName:   "page",
			Filename:      "src/routes/_page.svelte",
			SourceContent: src,
			GeneratedAt:   fixedTS,
		})
		if err != nil {
			t.Fatalf("Generate: %v", err)
		}
		s := string(out)
		if !strings.Contains(s, "// Code generated by sveltego dev — DO NOT EDIT.") {
			t.Errorf("missing rich header first line\ngot:\n%s", s)
		}
		if !strings.Contains(s, "// Source: src/routes/_page.svelte") {
			t.Errorf("missing Source line\ngot:\n%s", s)
		}
		if strings.Contains(s, "// Generated:") {
			t.Errorf("Generated timestamp must be absent (breaks idempotency)\ngot:\n%s", s)
		}
	})

	t.Run("simple banner without filename", func(t *testing.T) {
		out, err := Generate(frag, Options{PackageName: "page"})
		if err != nil {
			t.Fatalf("Generate: %v", err)
		}
		s := string(out)
		if !strings.Contains(s, "// Code generated by sveltego. DO NOT EDIT.") {
			t.Errorf("missing simple banner\ngot:\n%s", s)
		}
		if strings.Contains(s, "// Source:") {
			t.Errorf("unexpected Source line in simple banner\ngot:\n%s", s)
		}
	})
}

// TestGenerate_ProvenanceSpans verifies per-span comments are emitted when
// Provenance is true, and absent when false.
func TestGenerate_ProvenanceSpans(t *testing.T) {
	src := []byte("<p>{Name}</p>")
	frag, errs := parser.Parse(src)
	if len(errs) > 0 {
		t.Fatalf("parse: %v", errs)
	}

	t.Run("spans present when Provenance true", func(t *testing.T) {
		out, err := Generate(frag, Options{
			PackageName: "page",
			Provenance:  true,
			Filename:    "src/routes/_page.svelte",
			GeneratedAt: fixedTS,
		})
		if err != nil {
			t.Fatalf("Generate: %v", err)
		}
		s := string(out)
		if !strings.Contains(s, "// gen: source=") {
			t.Errorf("expected span comments when Provenance=true\ngot:\n%s", s)
		}
		if !strings.Contains(s, "kind=element") {
			t.Errorf("expected kind=element\ngot:\n%s", s)
		}
		if !strings.Contains(s, "kind=mustache") {
			t.Errorf("expected kind=mustache\ngot:\n%s", s)
		}
	})

	t.Run("spans absent when Provenance false", func(t *testing.T) {
		out, err := Generate(frag, Options{
			PackageName: "page",
			Provenance:  false,
			Filename:    "src/routes/_page.svelte",
			GeneratedAt: fixedTS,
		})
		if err != nil {
			t.Fatalf("Generate: %v", err)
		}
		s := string(out)
		if strings.Contains(s, "// gen: source=") {
			t.Errorf("unexpected span comments when Provenance=false\ngot:\n%s", s)
		}
	})
}

// TestGenerate_ProvenanceDeterministic verifies that same input → same output
// when GeneratedAt is pinned.
func TestGenerate_ProvenanceDeterministic(t *testing.T) {
	src := []byte("<p>{Name}</p>")
	frag, errs := parser.Parse(src)
	if len(errs) > 0 {
		t.Fatalf("parse: %v", errs)
	}
	opts := Options{
		PackageName:   "page",
		Provenance:    true,
		Filename:      "src/routes/_page.svelte",
		SourceContent: src,
		GeneratedAt:   fixedTS,
	}
	a, err := Generate(frag, opts)
	if err != nil {
		t.Fatalf("Generate first: %v", err)
	}
	b, err := Generate(frag, opts)
	if err != nil {
		t.Fatalf("Generate second: %v", err)
	}
	if string(a) != string(b) {
		t.Errorf("output not deterministic:\na:\n%s\n\nb:\n%s", a, b)
	}
}

// TestGenerateLayout_Provenance checks that the rich header is emitted for
// layout files when Filename is set.
func TestGenerateLayout_Provenance(t *testing.T) {
	src := []byte("<slot />")
	frag, errs := parser.Parse(src)
	if len(errs) > 0 {
		t.Fatalf("parse: %v", errs)
	}
	out, err := GenerateLayout(frag, LayoutOptions{
		PackageName:   "routes",
		Filename:      "src/routes/_layout.svelte",
		SourceContent: src,
		GeneratedAt:   fixedTS,
	})
	if err != nil {
		t.Fatalf("GenerateLayout: %v", err)
	}
	s := string(out)
	if !strings.Contains(s, "// Code generated by sveltego dev — DO NOT EDIT.") {
		t.Errorf("missing rich header\ngot:\n%s", s)
	}
	if !strings.Contains(s, "// Source: src/routes/_layout.svelte") {
		t.Errorf("missing Source\ngot:\n%s", s)
	}
}

// TestGenerateErrorPage_Provenance checks that the rich header is emitted for
// error pages when Filename is set.
func TestGenerateErrorPage_Provenance(t *testing.T) {
	src := []byte("<p>error</p>")
	frag, errs := parser.Parse(src)
	if len(errs) > 0 {
		t.Fatalf("parse: %v", errs)
	}
	out, err := GenerateErrorPage(frag, ErrorPageOptions{
		PackageName:   "routes",
		Filename:      "src/routes/_error.svelte",
		SourceContent: src,
		GeneratedAt:   fixedTS,
	})
	if err != nil {
		t.Fatalf("GenerateErrorPage: %v", err)
	}
	s := string(out)
	if !strings.Contains(s, "// Code generated by sveltego dev — DO NOT EDIT.") {
		t.Errorf("missing rich header\ngot:\n%s", s)
	}
}
