package codegen

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/binsarjr/sveltego/packages/sveltego/internal/routescan"
)

// emitRESTRoute writes the user-source mirror for one server.go and
// the adjacent server.gen.go that the manifest references via Handlers.
//
// Mirror lies at <projectRoot>/<outDir>/usersrc/<encoded>/server.go
// (sibling of the optional page mirror) so a route directory containing
// both server.go and page.server.go does not generate two files in the
// same package.
//
// The dispatcher emits a `var Handlers map[string]http.HandlerFunc`
// populated with one wrapper per declared HTTP verb function. Each
// wrapper builds a fresh kit.RequestEvent, invokes the user verb, and
// flushes the returned *kit.Response to the http.ResponseWriter using
// the same write order as server/pipeline.go's writeResponse: cookies,
// headers, status, body.
func emitRESTRoute(projectRoot, outDir, modulePath string, route routescan.ScannedRoute) error {
	if !route.HasServer {
		return nil
	}
	verbs, err := scanRESTHandlers(filepath.Join(route.Dir, "server.go"))
	if err != nil {
		return err
	}
	if len(verbs.Verbs) == 0 {
		return fmt.Errorf("codegen: %s/server.go declares no HTTP verb handlers", route.Dir)
	}

	encodedSub := strings.TrimPrefix(route.PackagePath, ".gen/")

	mirror := userSourceFile{
		UserPath:    filepath.Join(route.Dir, "server.go"),
		MirrorPath:  filepath.Join(projectRoot, outDir, "usersrc", filepath.FromSlash(encodedSub), "server.go"),
		PackageName: route.PackageName,
	}
	if err := mirrorUserSource(&mirror); err != nil {
		return err
	}

	importPath := modulePath + "/" + outDir + "/usersrc/" + encodedSub
	out, err := generateRESTDispatcher(route.PackageName, importPath, verbs.Verbs)
	if err != nil {
		return err
	}

	dir := filepath.Join(projectRoot, outDir, filepath.FromSlash(encodedSub))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("codegen: mkdir %s: %w", dir, err)
	}
	target := filepath.Join(dir, "server.gen.go")
	if err := os.WriteFile(target, out, genFileMode); err != nil {
		return fmt.Errorf("codegen: write %s: %w", target, err)
	}
	return nil
}

// generateRESTDispatcher renders one server.gen.go body. The verbs slice
// is assumed to be sorted in canonical order (GET, POST, ..., HEAD).
func generateRESTDispatcher(packageName, importPath string, verbs []string) ([]byte, error) {
	var b Builder
	b.Line("// Code generated by sveltego. DO NOT EDIT.")
	b.Linef("package %s", packageName)
	b.Line("")
	b.Line("import (")
	b.Indent()
	b.Line(`"net/http"`)
	b.Line("")
	b.Line(`"github.com/binsarjr/sveltego/packages/sveltego/exports/kit"`)
	b.Line("")
	b.Linef(`usersrc %q`, importPath)
	b.Dedent()
	b.Line(")")
	b.Line("")

	b.Line("// dispatch wraps a user-authored HTTP verb function so it satisfies")
	b.Line("// http.HandlerFunc. The wrapper builds a fresh kit.RequestEvent and")
	b.Line("// flushes the returned *kit.Response in the canonical order: cookies,")
	b.Line("// headers, status, body.")
	b.Line("func dispatch(verb func(*kit.RequestEvent) *kit.Response) http.HandlerFunc {")
	b.Indent()
	b.Line("return func(w http.ResponseWriter, r *http.Request) {")
	b.Indent()
	b.Line("ev := kit.NewRequestEvent(r, nil)")
	b.Line("res := verb(ev)")
	b.Line("if res == nil {")
	b.Indent()
	b.Line("res = kit.NewResponse(http.StatusNoContent, nil)")
	b.Dedent()
	b.Line("}")
	b.Line("if ev.Cookies != nil {")
	b.Indent()
	b.Line("ev.Cookies.Apply(w)")
	b.Dedent()
	b.Line("}")
	b.Line("for k, vs := range res.Headers {")
	b.Indent()
	b.Line("w.Header()[k] = vs")
	b.Dedent()
	b.Line("}")
	b.Line("status := res.Status")
	b.Line("if status == 0 {")
	b.Indent()
	b.Line("status = http.StatusOK")
	b.Dedent()
	b.Line("}")
	b.Line("w.WriteHeader(status)")
	b.Line("if len(res.Body) > 0 {")
	b.Indent()
	b.Line("_, _ = w.Write(res.Body)")
	b.Dedent()
	b.Line("}")
	b.Dedent()
	b.Line("}")
	b.Dedent()
	b.Line("}")
	b.Line("")

	b.Line("// Handlers is the method dispatch table the manifest wires into")
	b.Line("// router.Route.Server. The router's pipeline picks the matching")
	b.Line("// entry and emits 405 with an Allow header for unmapped verbs.")
	b.Line("var Handlers = map[string]http.HandlerFunc{")
	b.Indent()
	for _, v := range verbs {
		b.Linef(`%q: dispatch(usersrc.%s),`, v, v)
	}
	b.Dedent()
	b.Line("}")

	if err := b.Err(); err != nil {
		return nil, err
	}
	return format.Source(b.Bytes())
}
