package codegen

import (
	"errors"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/binsarjr/sveltego/packages/sveltego/internal/ast"
)

// ComponentOptions configures GenerateComponent.
type ComponentOptions struct {
	// PackageName is written verbatim into the generated `package` clause.
	PackageName string
	// ComponentName is the exported Go type name for the component (e.g.
	// "Card"). The generated file declares <ComponentName>Props,
	// <ComponentName>Slots, and a Render method on a value receiver.
	ComponentName string
}

// ComponentResult is the byte output plus codegen-time metadata gathered
// during a component lowering. Diagnostics carry the deprecation warning
// emitted for legacy slot syntax (#49) so the build orchestrator can
// surface it through its logger.
type ComponentResult struct {
	Source      []byte
	Diagnostics []Diagnostic
}

// Diagnostic is a non-fatal codegen finding. Severity is informational
// only at the moment; the build pipeline logs Info and treats Warning as
// a soft notice.
type Diagnostic struct {
	Pos      ast.Pos
	Severity DiagnosticSeverity
	Message  string
}

// DiagnosticSeverity tiers a Diagnostic as informational, advisory, or
// fatal. Codegen currently emits Info for legacy-syntax notes; fatal
// findings still surface as CodegenError values.
type DiagnosticSeverity int

const (
	DiagInfo DiagnosticSeverity = iota
	DiagWarning
)

// String renders the severity as a stable lowercase token.
func (s DiagnosticSeverity) String() string {
	switch s {
	case DiagInfo:
		return "info"
	case DiagWarning:
		return "warning"
	default:
		return "unknown"
	}
}

// slotOutlet records one <slot> outlet site so GenerateComponent can
// build the matching Slots struct field. Field is the PascalCase Go
// identifier (e.g. "Default" for the unnamed slot, "Header" for
// `<slot name="header"/>`); Props lists the slot prop bindings the
// outlet exposes via `key={value}` attributes.
type slotOutlet struct {
	Pos   ast.Pos
	Name  string // raw slot name, "" for default
	Field string // PascalCase Go identifier
	Props []slotProp
}

// slotProp captures one slot prop: `<slot count={total}/>` records
// Ident="count" (the prop key the caller binds via `let:count`) and
// Expr="total" (the Go expression the producer passes through to the
// slot closure).
type slotProp struct {
	Ident string
	Expr  string
}

// GenerateComponent lowers frag to Go source for a Svelte component. The
// receiver Render method takes Props, Slots, and a *render.Writer; slot
// outlets dispatch to closure fields on Slots. Slot-prop signatures are
// inferred from `<slot key={value}/>` attributes in the template.
//
// Generated source uses `any` for slot prop types because component
// templates do not declare type information; downstream Go compilation
// validates the caller's let-binding usage against the prop's actual
// runtime shape. This matches issue #50's "type inference flows from
// the slot declaration site" intent without forcing a separate Go type
// extraction pass.
func GenerateComponent(frag *ast.Fragment, opts ComponentOptions) (*ComponentResult, error) {
	if frag == nil {
		return nil, errors.New("codegen: nil fragment")
	}
	if opts.PackageName == "" {
		return nil, errors.New("codegen: empty package name")
	}
	if opts.ComponentName == "" {
		return nil, errors.New("codegen: empty component name")
	}

	scripts, err := extractScripts(frag)
	if err != nil {
		return nil, err
	}

	imports := mergeImports(scripts.Imports, nil)

	var b Builder
	b.componentMode = true

	var bodyB Builder
	bodyB.componentMode = true
	rejectRootConst(&bodyB, frag.Children)
	emitChildren(&bodyB, frag.Children)
	if err := bodyB.Err(); err != nil {
		return nil, err
	}

	slots := dedupeSlots(bodyB.slots)
	diags := slotDiagnostics(slots)

	b.Line("// Code generated by sveltego. DO NOT EDIT.")
	b.Linef("package %s", opts.PackageName)
	b.Line("")
	b.Line("import (")
	b.Indent()
	for _, imp := range imports {
		b.Line(imp)
	}
	b.Dedent()
	b.Line(")")
	b.Line("")

	for _, decl := range scripts.Decls {
		b.Line(decl)
		b.Line("")
	}

	b.Linef("type %s struct{}", opts.ComponentName)
	b.Line("")
	b.Linef("type %sProps = struct{}", opts.ComponentName)
	b.Line("")
	emitSlotsStruct(&b, opts.ComponentName, slots)
	b.Line("")
	b.Linef("func (c %s) Render(w *render.Writer, ctx *kit.RenderCtx, props %sProps, slots %sSlots) error {",
		opts.ComponentName, opts.ComponentName, opts.ComponentName)
	b.Indent()
	b.Line("_ = ctx")
	b.Line("_ = props")
	b.Line("_ = slots")
	b.buf.WriteString(bodyB.buf.String())
	b.Line("return nil")
	b.Dedent()
	b.Line("}")

	if err := b.Err(); err != nil {
		return nil, err
	}

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: format generated source: %w", err)
	}
	return &ComponentResult{Source: restoreRunesBytes(out), Diagnostics: diags}, nil
}

func emitSlotsStruct(b *Builder, comp string, slots []slotOutlet) {
	b.Linef("type %sSlots struct {", comp)
	b.Indent()
	if len(slots) == 0 {
		b.Line("Default func(w *render.Writer) error")
	} else {
		for _, s := range slots {
			b.Linef("%s %s", s.Field, slotClosureType(s))
		}
	}
	b.Dedent()
	b.Line("}")
}

// slotClosureType renders the Go function type for one slot field.
// `<slot/>` lowers to `func(w *render.Writer) error`; `<slot
// item={item}/>` lowers to `func(item any, w *render.Writer) error`.
// The trailing `w` parameter mirrors the layout `children` shape so
// callers always know where the writer is.
func slotClosureType(s slotOutlet) string {
	if len(s.Props) == 0 {
		return "func(w *render.Writer) error"
	}
	var b strings.Builder
	b.WriteString("func(")
	for _, p := range s.Props {
		b.WriteString(p.Ident)
		b.WriteString(" any, ")
	}
	b.WriteString("w *render.Writer) error")
	return b.String()
}

// emitComponentSlotOutlet lowers <slot/>, <slot name="header"/>, or a
// slot-prop variant on the receiving (component) side. The Builder must
// already be in componentMode. Fallback content lives in e.Children and
// is emitted in the else branch when slots.<Name> is nil.
func emitComponentSlotOutlet(b *Builder, e *ast.Element) {
	name, props, fallback := scanSlotOutlet(e)
	field := slotFieldName(name)
	out := slotOutlet{Pos: e.P, Name: name, Field: field, Props: props}
	b.slots = append(b.slots, out)

	args := slotCallArgs(props)
	b.Linef("if slots.%s != nil {", field)
	b.Indent()
	b.Linef("if err := slots.%s(%s); err != nil {", field, args)
	b.Indent()
	b.Line("return err")
	b.Dedent()
	b.Line("}")
	b.Dedent()
	if !fallback {
		b.Line("}")
		return
	}
	b.Line("} else {")
	b.Indent()
	emitChildren(b, e.Children)
	b.Dedent()
	b.Line("}")
}

func slotCallArgs(props []slotProp) string {
	if len(props) == 0 {
		return "w"
	}
	var b strings.Builder
	for _, p := range props {
		b.WriteString(p.Expr)
		b.WriteString(", ")
	}
	b.WriteString("w")
	return b.String()
}

// scanSlotOutlet inspects an outlet's attributes to derive the slot's
// name (default = "") and any slot-prop bindings. Slot-prop syntax is
// `<slot key={expr}/>` (key is the prop name, expr is the Go value
// expression). Returns the name, the props in source order, and
// whether the body holds non-empty fallback content.
func scanSlotOutlet(e *ast.Element) (string, []slotProp, bool) {
	name := ""
	var props []slotProp
	for i := range e.Attributes {
		a := &e.Attributes[i]
		if a.Kind != ast.AttrStatic {
			continue
		}
		if a.Name == "name" {
			if sv, ok := a.Value.(*ast.StaticValue); ok {
				name = sv.Value
			}
			continue
		}
		ident, expr, ok := slotPropParts(a)
		if !ok {
			continue
		}
		props = append(props, slotProp{Ident: ident, Expr: expr})
	}
	return name, props, hasNonEmptyBody(e.Children)
}

func slotPropParts(a *ast.Attribute) (string, string, bool) {
	if !isIdent(a.Name) {
		return "", "", false
	}
	if v, ok := a.Value.(*ast.DynamicValue); ok {
		// `<slot count={total}/>` — explicit name + Go expression.
		return a.Name, v.Expr, true
	}
	return "", "", false
}

// slotFieldName converts a raw slot name to its PascalCase Go field
// identifier on the Slots struct. Empty or "default" both map to
// "Default" so the unnamed slot has a stable accessor. Hyphens and
// underscores are camelized.
func slotFieldName(name string) string {
	if name == "" || name == "default" {
		return "Default"
	}
	parts := splitSlotIdent(name)
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteByte(upperByte(p[0]))
		b.WriteString(p[1:])
	}
	if b.Len() == 0 {
		return "Default"
	}
	return b.String()
}

func splitSlotIdent(name string) []string {
	parts := []string{}
	cur := strings.Builder{}
	for i := range len(name) {
		c := name[i]
		if c == '-' || c == '_' {
			parts = append(parts, cur.String())
			cur.Reset()
			continue
		}
		cur.WriteByte(c)
	}
	parts = append(parts, cur.String())
	return parts
}

func upperByte(c byte) byte {
	if c >= 'a' && c <= 'z' {
		return c - ('a' - 'A')
	}
	return c
}

// dedupeSlots collapses repeat slot references onto a single Slots
// field, preserving first occurrence order. Slot prop signatures must
// agree across mentions of the same name; conflicting prop sets surface
// later as Go compile errors when the closure type is inconsistent.
func dedupeSlots(in []slotOutlet) []slotOutlet {
	seen := map[string]int{}
	var out []slotOutlet
	for _, s := range in {
		if i, ok := seen[s.Field]; ok {
			if len(out[i].Props) == 0 && len(s.Props) > 0 {
				out[i].Props = s.Props
			}
			continue
		}
		seen[s.Field] = len(out)
		out = append(out, s)
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Field == "Default" {
			return false
		}
		if out[j].Field == "Default" {
			return true
		}
		return out[i].Field < out[j].Field
	})
	return out
}

// slotDiagnostics emits the legacy-syntax informational diagnostic on
// behalf of #49: one Info per template that uses any slot at all,
// pointing the user toward the snippet alternative shipped via #48.
func slotDiagnostics(slots []slotOutlet) []Diagnostic {
	if len(slots) == 0 {
		return nil
	}
	var first ast.Pos
	for _, s := range slots {
		if !first.IsValid() || s.Pos.Offset < first.Offset {
			first = s.Pos
		}
	}
	return []Diagnostic{{
		Pos:      first,
		Severity: DiagInfo,
		Message:  "<slot> is legacy syntax; consider {#snippet}/{@render} (#48) for new code",
	}}
}

// emitComponentCall lowers a component invocation `<Card>...</Card>` on
// the caller side. Slot lifting follows Phase 0bb's contract: every
// child element with a `slot="name"` attribute peels into its own
// closure assigned to <pkg>.<Comp>Slots.<PascalName>; the residual
// children form the default slot. Caller-side `let:foo` attributes
// rebind the slot closure parameters into the user-named locals before
// the body emits.
//
// The package alias is derived from the component name (lowercase
// initial char). Component-import resolution and Props composition are
// out of scope for #49/#50; this emitter assumes the user's <script>
// imports the component package under that conventional alias.
//
// For components without any slot lifting (no slot= children, no
// child content) the call collapses to a stub TODO so existing
// component-placeholder fixtures keep their behavior until #10 lands.
func emitComponentCall(b *Builder, e *ast.Element) {
	pkg := componentPackageAlias(e.Name)
	letBindings := collectLetBindings(e.Attributes)
	defaultBody, named := liftSlotChildren(e.Children)

	if len(named) == 0 && !hasNonEmptyBody(defaultBody) {
		b.Linef("// TODO: component <%s> (#10 component nesting)", e.Name)
		b.Line("_ = w")
		return
	}

	b.Linef("{")
	b.Indent()
	b.Linef("_slots := %s.%sSlots{}", pkg, e.Name)
	if hasNonEmptyBody(defaultBody) {
		emitSlotClosure(b, "_slots.Default", letBindings, defaultBody)
	}
	for _, ns := range named {
		field := slotFieldName(ns.name)
		emitSlotClosure(b, "_slots."+field, ns.lets, ns.body)
	}
	b.Linef("if err := (%s.%s{}).Render(w, ctx, %s.%sProps{}, _slots); err != nil {", pkg, e.Name, pkg, e.Name)
	b.Indent()
	b.Line("return err")
	b.Dedent()
	b.Line("}")
	b.Dedent()
	b.Line("}")
}

func componentPackageAlias(name string) string {
	if name == "" {
		return "comp"
	}
	c := name[0]
	if c >= 'A' && c <= 'Z' {
		c += 'a' - 'A'
	}
	return string(c) + name[1:]
}

type liftedSlot struct {
	name string
	lets []letBinding
	body []ast.Node
}

type letBinding struct {
	// Ident is the slot's prop name (closure parameter): for `let:item`
	// the param is `item`; for `let:item={alias}` the param is still
	// `item` because that's the prop key the producer passed.
	Ident string
	// Local is the body-local name when the user chose a different
	// identifier via `let:item={alias}`. Empty (or equal to Ident) when
	// the shorthand form is used and no aliasing is required.
	Local string
}

// liftSlotChildren splits a component's children into the residual
// default-slot body and a list of named-slot bodies. A child element
// carrying `slot="name"` is moved into the named bucket with the
// attribute stripped; everything else falls through to the default.
func liftSlotChildren(nodes []ast.Node) ([]ast.Node, []liftedSlot) {
	var def []ast.Node
	var named []liftedSlot
	for _, n := range nodes {
		el, ok := n.(*ast.Element)
		if !ok {
			def = append(def, n)
			continue
		}
		slotName, lets, stripped := splitSlotAttrs(el)
		if slotName == "" {
			def = append(def, n)
			continue
		}
		clone := *el
		clone.Attributes = stripped
		named = append(named, liftedSlot{
			name: slotName,
			lets: lets,
			body: []ast.Node{&clone},
		})
	}
	return def, named
}

// splitSlotAttrs scans an element's attributes for a slot="name" target
// and any let:foo bindings. The returned attribute slice has both
// removed so the element can render normally inside its closure body.
func splitSlotAttrs(el *ast.Element) (string, []letBinding, []ast.Attribute) {
	slotName := ""
	var lets []letBinding
	kept := el.Attributes[:0:0]
	for i := range el.Attributes {
		a := &el.Attributes[i]
		if a.Kind == ast.AttrStatic && a.Name == "slot" {
			if sv, ok := a.Value.(*ast.StaticValue); ok {
				slotName = sv.Value
			}
			continue
		}
		if a.Kind == ast.AttrLet {
			lets = append(lets, letFromAttr(a))
			continue
		}
		kept = append(kept, *a)
	}
	return slotName, lets, kept
}

func letFromAttr(a *ast.Attribute) letBinding {
	ident := a.Modifier
	if ident == "" {
		ident = a.Name
	}
	if v, ok := a.Value.(*ast.DynamicValue); ok {
		return letBinding{Ident: ident, Local: v.Expr}
	}
	return letBinding{Ident: ident, Local: ident}
}

// collectLetBindings extracts let:foo bindings declared on the
// component's own opening tag (i.e. the default-slot scope). They flow
// into the closure produced for the default slot.
func collectLetBindings(attrs []ast.Attribute) []letBinding {
	var out []letBinding
	for i := range attrs {
		a := &attrs[i]
		if a.Kind != ast.AttrLet {
			continue
		}
		out = append(out, letFromAttr(a))
	}
	return out
}

// emitSlotClosure renders one slot field assignment. Closure parameters
// match the slot's prop names so the receiver call site `slots.X(item,
// w)` lines up positionally; let bindings introduce a body-local alias
// when the user chose a different name (`let:item={alias}` produces
// `alias := item`). Slot props type as `any` (see GenerateComponent
// godoc); user code recovers the concrete shape through normal Go type
// inference at the receiver site.
func emitSlotClosure(b *Builder, field string, lets []letBinding, body []ast.Node) {
	params := slotClosureParams(lets)
	b.Linef("%s = func(%sw *render.Writer) error {", field, params)
	b.Indent()
	for _, lb := range lets {
		if lb.Local != "" && lb.Local != lb.Ident {
			b.Linef("%s := %s", lb.Local, lb.Ident)
			b.Linef("_ = %s", lb.Local)
		}
	}
	emitChildren(b, body)
	b.Line("return nil")
	b.Dedent()
	b.Line("}")
}

// slotClosureParams renders the slot closure's parameter list prefix
// (everything before the trailing `w *render.Writer`). The trailing
// comma is included when at least one let-binding is present.
func slotClosureParams(lets []letBinding) string {
	if len(lets) == 0 {
		return ""
	}
	var b strings.Builder
	for _, lb := range lets {
		b.WriteString(lb.Ident)
		b.WriteString(" any, ")
	}
	return b.String()
}
