// Code generated by sveltego typegen. DO NOT EDIT.
// Source: _page.server.go (Load return type)

export interface PageData {
	greeting: string;
	userCount: number;
	display_name: string;
}

export const data: PageData;
