package router

import (
	"net/http"

	"github.com/binsarjr/sveltego/packages/sveltego/exports/kit"
	"github.com/binsarjr/sveltego/packages/sveltego/render"
)

// PageHandler renders a _page.svelte for the given context and load data.
type PageHandler func(w *render.Writer, ctx *kit.RenderCtx, data any) error

// PageHeadHandler renders a page's <svelte:head> contributions into a
// side buffer. The pipeline gathers the layout chain's head outputs and
// the page's head into one buffer that injects between <head> and
// </head>. nil entries denote pages without any head content.
type PageHeadHandler func(w *render.Writer, ctx *kit.RenderCtx, data any) error

// LayoutHandler renders a _layout.svelte. It composes outer layouts around
// inner content by writing its template up to <slot />, invoking children,
// then writing the rest. children is non-nil; layout templates dispatch
// the slot lowering through it.
//
// LayoutHandler values are no longer stored on Route; per-route layout
// composition is baked into the generated RenderChain / RenderError
// functions. The type stays exported because emitted code still references
// it as the closure signature for individual layout templates.
type LayoutHandler func(w *render.Writer, ctx *kit.RenderCtx, data any, children func(*render.Writer) error) error

// LayoutHeadHandler renders a layout's <svelte:head> contributions into
// a side buffer. Slice entries on Route.LayoutHeads run outer→inner;
// nil entries denote layouts without any head content.
type LayoutHeadHandler func(w *render.Writer, ctx *kit.RenderCtx, data any) error

// ErrorHandler renders a _error.svelte. It receives the SafeError produced
// by HandleError and writes the error template into w. The type stays
// exported because emitted code references it as the closure signature
// for individual error templates; route storage is via RenderError.
type ErrorHandler func(w *render.Writer, ctx *kit.RenderCtx, safe kit.SafeError) error

// RenderChainFn composes a route's layout chain (outer→inner) around its
// page handler at compile time. Generated by codegen per-route; the
// pipeline calls it with the page handler, the page data, and the
// layoutDatas slice that ran in lockstep with LayoutLoaders. nil when
// the route has no layouts; the pipeline then calls Page directly.
type RenderChainFn func(w *render.Writer, ctx *kit.RenderCtx, page PageHandler, pageData any, layoutDatas []any) error

// RenderErrorFn composes the surviving outer-layout prefix around the
// route's _error.svelte handler. The boundary depth is baked into the
// generated function — the pipeline does not pass it. nil when no error
// boundary applies; the pipeline falls back to the plain-text writer
// in that case.
type RenderErrorFn func(w *render.Writer, ctx *kit.RenderCtx, safe kit.SafeError, layoutDatas []any) error

// ServerHandlers maps HTTP methods to handlers emitted from _server.go.
type ServerHandlers map[string]http.HandlerFunc

// LoadHandler runs the user-written Load() from _page.server.go and
// returns the data threaded into the page render.
type LoadHandler func(ctx *kit.LoadCtx) (any, error)

// LayoutLoadHandler runs the user-written Load() from _layout.server.go.
// One handler per layout in the chain; nil entries denote layouts without
// a sibling layout.server.go and are skipped by the pipeline.
type LayoutLoadHandler func(ctx *kit.LoadCtx) (any, error)

// ActionsHandler returns the typed Actions value declared in
// _page.server.go. The router keeps it as `any` to remain type-erased;
// the dispatcher casts back to the concrete type.
type ActionsHandler func() any

// Route is one entry in the route table built from the codegen-emitted
// manifest. The router never invokes the handler refs; that is the
// dispatcher's job.
type Route struct {
	// ID is an 8-char hex tag derived from an FNV-1a 32-bit hash of Pattern,
	// populated by NewTree. It is a tag for logging and manifest correlation,
	// NOT a collision-free identity. Use Pattern as the unique key.
	ID string
	// Pattern is the SvelteKit-style canonical path, e.g. "/post/[id]/[...rest]".
	Pattern string
	// Segments is the parsed form of Pattern.
	Segments []Segment
	// Page is non-nil when the route owns a _page.svelte.
	Page PageHandler
	// Server holds method handlers when the route owns a _server.go.
	Server ServerHandlers
	// Load is non-nil when the route owns a _page.server.go with Load().
	Load LoadHandler
	// Actions is non-nil when _page.server.go declares Actions().
	Actions ActionsHandler
	// RenderChain composes the route's layout chain (outer→inner) around
	// the page handler at compile time. nil when the route has no
	// layouts; the pipeline calls Page directly in that case. Generated
	// by codegen per-route so no per-request closure allocation is
	// needed to wrap layouts.
	RenderChain RenderChainFn
	// LayoutLoaders carries the per-layout load handlers in outer→inner
	// order. Index i holds the loader for the i-th layout in the chain
	// or nil when that layout has no _layout.server.go. The pipeline
	// invokes them outer→inner before the page Load and pushes each
	// result onto the LoadCtx parent stack. len(LayoutLoaders) is the
	// authoritative layout count for the route.
	LayoutLoaders []LayoutLoadHandler
	// Head is non-nil when the page contributes <svelte:head> content.
	// The pipeline calls it after the layout chain's head handlers and
	// before injecting the merged buffer into the document <head>.
	Head PageHeadHandler
	// LayoutHeads runs in lockstep with LayoutLoaders. Index i holds the
	// head handler for the i-th layout or nil when that layout has no
	// <svelte:head> content.
	LayoutHeads []LayoutHeadHandler
	// Options carries the route's effective page options after the
	// codegen-time cascade resolves layout overrides into a single
	// PageOptions value. The pipeline reads SSR/CSR/TrailingSlash
	// directly from this field; no per-request layout walk is needed.
	Options kit.PageOptions
	// RenderError composes the surviving outer-layout prefix around the
	// route's _error.svelte handler. The boundary depth is baked into
	// the generated function — the pipeline passes the full layoutDatas
	// slice and the function reads only the outer-N entries it needs.
	// nil when no error boundary applies; the pipeline falls back to a
	// plain-text response in that case.
	RenderError RenderErrorFn
	// ClientKey is the Vite manifest input key for this route's client
	// entry, e.g. "routes/_page". The server uses it for asset tag injection.
	// Empty for server-only routes.
	ClientKey string
}
