// Code generated by sveltego typegen. DO NOT EDIT.
// Source: _page.server.go (Load return type)

export interface User {
	name: string;
}

export interface PageData {
	owner: User | null;
	tags: string[];
	backup: string | null;
}

export const data: PageData;
