// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/attr-helper

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/attr-helper.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<input")
	payload.Push(server.Attr("value", data.value, false))
	payload.Push(" />")
}
