// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/class-directive

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/class-directive.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<span class=\"")
	payload.Push(server.Clsx("base", data.classes))
	payload.Push("\"></span>")
}
