// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/each-destructure

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/each-destructure.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	each_array := server.EnsureArrayLike(data.items)
	ssvar_length := len(each_array)
	for ssvar_index := 0; ssvar_index < ssvar_length; ssvar_index++ {
		entry := each_array[ssvar_index]
		payload.Push("<li>")
		payload.Push(server.EscapeHTML(entry.name))
		payload.Push(" x ")
		payload.Push(server.EscapeHTML(entry.count))
		payload.Push("</li>")
	}
}
