// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/each-with-index

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/each-with-index.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	each_array := server.EnsureArrayLike(data.items)
	ssvar_length := len(each_array)
	for ssvar_index := 0; ssvar_index < ssvar_length; ssvar_index++ {
		item := each_array[ssvar_index]
		payload.Push("<li>")
		payload.Push(server.EscapeHTML(item.title))
		payload.Push(" (")
		payload.Push(server.EscapeHTML(ssvar_index))
		payload.Push(")</li>")
	}
}
