// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/else-if-chain

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/else-if-chain.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	if data.status == "ok" {
		payload.Push("<p>ok</p>")
	} else if data.status == "warn" {
		payload.Push("<p>warn</p>")
	} else {
		payload.Push("<p>error</p>")
	}
}
