// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/for-of

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/for-of.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	for _, item := range data.items {
		payload.Push("<li>")
		payload.Push(server.EscapeHTML(item.title))
		payload.Push("</li>")
	}
}
