// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/multi-line-template

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/multi-line-template.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<div>\n  <p>line one</p>\n  <p>")
	payload.Push(server.EscapeHTML(data.body))
	payload.Push("</p>\n  <p>line three</p>\n</div>")
}
