// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/nested-for-if

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/nested-for-if.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	for _, group := range data.groups {
		if server.Truthy(group.visible) {
			for _, item := range group.items {
				payload.Push("<li>")
				payload.Push(server.EscapeHTML(item.name))
				payload.Push("</li>")
			}
		}
	}
}
