// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/render-snippet

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/render-snippet.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	card := func(item any) {
		payload.Push("<article></article>")
	}
	card(data.item)
}
