// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/slot-named

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/slot-named.
func Render(payload *server.Payload, props map[string]any) {
	ssvar_props, _ := props["$$props"].(map[string]any)
	server.Slot(payload, toMapStringAny(ssvar_props), "header", toMapStringAny(map[string]any{"title": "welcome"}), nil)
}
