// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/snippet-closure

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/snippet-closure.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	card := func(item any) {
		payload.Push("<article>")
		payload.Push(server.EscapeHTML(item.name))
		payload.Push("</article>")
	}
}
