// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/spread-attrs

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/spread-attrs.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<div")
	payload.Push(server.SpreadAttributes(toMapStringAny(data.attrs)))
	payload.Push("></div>")
}
