// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/static-attr

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/static-attr.
func Render(payload *server.Payload, props map[string]any) {
	payload.Push("<button class=\"btn\">click</button>")
}
