// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/svelte-head

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/svelte-head.
func Render(payload *server.Payload, props map[string]any) {
	server.Head(payload, "h1", func(payload *server.Payload) {
		payload.Push("<title>About</title>")
	})
}
