// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/tagged-template-literal

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/tagged-template-literal.
func Render(payload *server.Payload, props map[string]any) {
	payload.Push("<section>only static</section>")
}
