// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/ternary-in-template

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/ternary-in-template.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<span class=\"")
	payload.Push(func() any {
		if server.Truthy(data.active) {
			return "on"
		}
		return "off"
	}())
	payload.Push("\"></span>")
}
