// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /each-list

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /each-list.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<ul><!--[-->")
	each_array := server.EnsureArrayLike(data.items)
	ssvar_length := len(each_array)
	for ssvar_index := 0; ssvar_index < ssvar_length; ssvar_index++ {
		item := each_array[ssvar_index]
		payload.Push("<li>")
		payload.Push(server.EscapeHTML(item.title))
		payload.Push("</li>")
	}
	payload.Push("<!--]--></ul>")
}
