// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /hello-world

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /hello-world.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<h1>Hello ")
	payload.Push(server.EscapeHTML(data.name))
	payload.Push("</h1>")
}
