// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/arrow-with-statement

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/arrow-with-statement.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	inner := func(v any) {
		if server.Truthy(v) {
			payload.Push("<p>truthy</p>")
		} else {
			payload.Push("<p>falsy</p>")
		}
	}
	inner(data.flag)
}
