// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/atconst-string

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/atconst-string.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	greeting := ("hi, " + data.name)
	payload.Push("<p>")
	payload.Push(server.EscapeHTML(greeting))
	payload.Push("</p>")
}
