// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/atconst-multi

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/atconst-multi.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	a := len(data.a)
	b := len(data.b)
	payload.Push("<p>")
	payload.Push(server.EscapeHTML(a))
	payload.Push(" / ")
	payload.Push(server.EscapeHTML(b))
	payload.Push("</p>")
}
