// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/atconst-with-fn

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/atconst-with-fn.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	upper := data.name.toUpperCase()
	payload.Push("<p>")
	payload.Push(server.EscapeHTML(upper))
	payload.Push("</p>")
}
