// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/attr-string-literal-value

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/attr-string-literal-value.
func Render(payload *server.Payload, props map[string]any) {
	payload.Push("<button")
	payload.Push(server.Attr("data-action", "submit", false))
	payload.Push(">click</button>")
}
