// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/binary-mod

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/binary-mod.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	if (data.n % 2) == 0 {
		payload.Push("<p>even</p>")
	}
}
