// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/binary-lt

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/binary-lt.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	if data.count < 10 {
		payload.Push("<p>few</p>")
	}
}
