// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/each-nested

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/each-nested.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	each_array := server.EnsureArrayLike(data.groups)
	ssvar_length := len(each_array)
	for ssvar_index := 0; ssvar_index < ssvar_length; ssvar_index++ {
		group := each_array[ssvar_index]
		for _, item := range group.items {
			payload.Push("<li>")
			payload.Push(server.EscapeHTML(item.title))
			payload.Push("</li>")
		}
	}
}
