// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/escape-of-conditional

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/escape-of-conditional.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<p>")
	payload.Push(server.EscapeHTML(func() any {
		if server.Truthy(data.loggedIn) {
			return "welcome"
		}
		return "guest"
	}()))
	payload.Push("</p>")
}
