// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/escape-attr-position

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/escape-attr-position.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<input value=\"")
	payload.Push(server.EscapeHTMLAttr(data.value))
	payload.Push("\" />")
}
