// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/escape-of-binary

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/escape-of-binary.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<span>")
	payload.Push(server.EscapeHTML((data.first + data.last)))
	payload.Push("</span>")
}
