// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/for-of-bare-array

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/for-of-bare-array.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	for _, name := range []any{"a", "b", "c"} {
		payload.Push("<li>")
		payload.Push(server.EscapeHTML(name))
		payload.Push("</li>")
	}
}
