// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/helper-exclude-from-object

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/helper-exclude-from-object.
func Render(payload *server.Payload, props map[string]any) {
	ssvar_props, _ := props["$$props"].(map[string]any)
	trimmed := server.ExcludeFromObject(toMapStringAny(ssvar_props), "internal")
	payload.Push("<div")
	payload.Push(server.SpreadAttributes(toMapStringAny(trimmed)))
	payload.Push("></div>")
}
