// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/helper-spread-props

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/helper-spread-props.
func Render(payload *server.Payload, props map[string]any) {
	ssvar_props, _ := props["$$props"].(map[string]any)
	payload.Push("<div")
	payload.Push(server.SpreadProps(toMapStringAny(ssvar_props), toMapStringAny(map[string]any{"class": "extra"})))
	payload.Push("></div>")
}
