// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/helper-sanitize-props

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/helper-sanitize-props.
func Render(payload *server.Payload, props map[string]any) {
	ssvar_props, _ := props["$$props"].(map[string]any)
	safe := server.SanitizeProps(toMapStringAny(ssvar_props))
	payload.Push("<div")
	payload.Push(server.SpreadAttributes(toMapStringAny(safe)))
	payload.Push("></div>")
}
