// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/helper-rest-props

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/helper-rest-props.
func Render(payload *server.Payload, props map[string]any) {
	ssvar_props, _ := props["$$props"].(map[string]any)
	rest := server.RestProps(toMapStringAny(ssvar_props), "class", "style")
	payload.Push("<div")
	payload.Push(server.SpreadAttributes(toMapStringAny(rest)))
	payload.Push("></div>")
}
