// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/helper-fallback

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/helper-fallback.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	name := server.Fallback(data.name, "guest")
	payload.Push("<p>")
	payload.Push(server.EscapeHTML(name))
	payload.Push("</p>")
}
