// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/if-with-empty-alt

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/if-with-empty-alt.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	if data.toggle {
		payload.Push("<p>on</p>")
	} else {
	}
}
