// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/logical-mixed

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/logical-mixed.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	if (data.a && data.b) || data.c {
		payload.Push("<p>true</p>")
	}
}
