// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/merge-styles-multi

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/merge-styles-multi.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<div style=\"")
	payload.Push(server.MergeStyles("color: red", "font-size: 12px", data.style))
	payload.Push("\"></div>")
}
