// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/nested-if-if

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/nested-if-if.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	if data.a {
		if data.b {
			payload.Push("<p>both</p>")
		}
	}
}
