// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/render-with-string

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/render-with-string.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	greet := func(name any) {
		payload.Push("<p>hello ")
		payload.Push(server.EscapeHTML(name))
		payload.Push("</p>")
	}
	greet("world")
}
