// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/slot-with-fallback

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/slot-with-fallback.
func Render(payload *server.Payload, props map[string]any) {
	ssvar_props, _ := props["$$props"].(map[string]any)
	server.Slot(payload, toMapStringAny(ssvar_props), "default", toMapStringAny(ssvar_props), func(payload *server.Payload) {
		payload.Push("<p>fallback</p>")
	})
}
