// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/snippet-no-args

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/snippet-no-args.
func Render(payload *server.Payload, props map[string]any) {
	header := func() {
		payload.Push("<h2>header</h2>")
	}
	header()
}
