// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/snippet-multi-args

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/snippet-multi-args.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	row := func(name any, count any) {
		payload.Push("<tr><td>")
		payload.Push(server.EscapeHTML(name))
		payload.Push("</td><td>")
		payload.Push(server.EscapeHTML(count))
		payload.Push("</td></tr>")
	}
	row(data.name, data.count)
}
