// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/snippet-then-render

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/snippet-then-render.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	link := func(href any, text any) {
		payload.Push("<a href=\"")
		payload.Push(server.EscapeHTML(href))
		payload.Push("\">")
		payload.Push(server.EscapeHTML(text))
		payload.Push("</a>")
	}
	link(("/post/" + data.id), data.title)
}
