// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/stringify-helper

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/stringify-helper.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<p>")
	payload.Push(server.Stringify(data.count))
	payload.Push("</p>")
}
