// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/svelte-element-no-attrs

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/svelte-element-no-attrs.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	server.Element(payload, data.tag, func(payload *server.Payload) {
	}, func(payload *server.Payload) {
		payload.Push("body")
	})
}
