// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/template-leading-expr

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/template-leading-expr.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push(server.EscapeHTML(data.a))
	payload.Push(" trail")
}
