// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/template-no-exprs

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/template-no-exprs.
func Render(payload *server.Payload, props map[string]any) {
	payload.Push("<section>plain</section>")
}
