// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/template-many-exprs

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/template-many-exprs.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<p>")
	payload.Push(server.EscapeHTML(data.a))
	payload.Push(" ")
	payload.Push(server.EscapeHTML(data.b))
	payload.Push(" ")
	payload.Push(server.EscapeHTML(data.c))
	payload.Push(" ")
	payload.Push(server.EscapeHTML(data.d))
	payload.Push("</p>")
}
