// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/ternary-nested

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/ternary-nested.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<span>")
	payload.Push(func() any {
		if server.Truthy(data.a) {
			return "x"
		}
		return func() any {
			if server.Truthy(data.b) {
				return "y"
			}
			return "z"
		}()
	}())
	payload.Push("</span>")
}
