// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/to-class-with-hash

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/to-class-with-hash.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<span class=\"")
	payload.Push(server.ToClass(data.klass, "svelte-abc123", nil))
	payload.Push("\"></span>")
}
