// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/to-class-with-directives

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/to-class-with-directives.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<span class=\"")
	payload.Push(server.ToClass(data.klass, "", toMapStringBool(data.directives)))
	payload.Push("\"></span>")
}
