// Code generated by sveltego svelte_js2go. DO NOT EDIT.
// route: /test/to-style-with-styles

package gen

import (
	server "github.com/binsarjr/sveltego/packages/sveltego/runtime/svelte/server"
)

// Render mirrors the Svelte component's compiled server output.
// Generated from route /test/to-style-with-styles.
func Render(payload *server.Payload, props map[string]any) {
	data, _ := props["data"].(map[string]any)
	payload.Push("<div style=\"")
	payload.Push(server.ToStyle(data.style, toMapStringString(data.dirs)))
	payload.Push("\"></div>")
}
